### ISSUE TITLE
[ECP-9257] System.IO Exception from adyen client

### ISSUE THREAD

**Issue by JuanOG-Kyo** [Adyen/adyen-dotnet-api-library#1007]
We have noticed many times in production when the adyen client just randomly throws a 500 exception with
Error Type: System.IO
Error Message: The response ended prematurely.

I am not sure as this occurs at random times on random days

**Expected behavior**
A request made using the adyen client should complete the request and on any errors it should throw more meaningful exceptions or a properly structured response.

**Context on how we use the client**
We run our app in a linux environment and we create a new adyen client on every request but we proved the httpclient from the http client factory. The primary message handler is the one produced by adyens createmessagehandler function. Which seems to be to aid with terminal requests.

**Screenshot**
![Screenshot_20240411-000102.png](https://github.com/Adyen/adyen-dotnet-api-library/assets/66722253/d18606cf-29a5-46a0-a673-3cdb8721cbc0)

**Comment by DjoykeAbyah** [comment]
Hi @JuanOG-Kyo! 

Creating a new http client for every request is not recommended. You would rather re-use the HttpClient. Perhaps [this closed git issue](https://github.com/Adyen/adyen-dotnet-api-library/issues/817) would be of use. They had a similar issue to yours.

Regards,

Djoyke
Adyen

**Comment by JuanOG-Kyo** [comment]
> Hi @JuanOG-Kyo! 
> 
> Creating a new http client for every request is not recommended. You would rather re-use the HttpClient. Perhaps [this closed git issue](https://github.com/Adyen/adyen-dotnet-api-library/issues/817) would be of use. They had a similar issue to yours.
> 
> Regards,
> 
> Djoyke
> Adyen
> 
> 

We actually use the Microsoft recommended way of using the http client factory which will reuse the connections, so i don't see how that would cause the issue.

**Comment by DjoykeAbyah** [comment]
@JuanOG-Kyo,

My apologies I wasn't aware of that! Then it's indeed very strange that you receive these error messages. I'll need to look into this a bit deeper to see what's going on. Could you maybe provide a code snippet so I can try to recreate the process?

**Comment by JuanOG-Kyo** [comment]
![image](https://github.com/Adyen/adyen-dotnet-api-library/assets/66722253/94c9bf8d-3e0a-4be8-8172-3166d13bfdcc)
![image](https://github.com/Adyen/adyen-dotnet-api-library/assets/66722253/4014fa23-2088-4a4d-b621-0d06f23317f1)

@DjoykeAbyah This is a sample of the code we use to call TerminalRequestAsynchronousAsync() which seems to have had a couple of these exceptions occur.
_Note: this doesn't occur that frequently, maybe 5 times out of 3000 requests (Rough estimates)._

**Comment by DjoykeAbyah** [comment]
@JuanOG-Kyo 

Thank you for providing the snippet! I'll dive into it and get back to you!

**Comment by DjoykeAbyah** [comment]
@JuanOG-Kyo,

Thank you for your patience while we investigated this issue.

There are a few potential reasons why this exception may be occurring.

One cause could be a non-graceful shutdown, such as forcefully killing an application during deployment.

Also, to handle timeouts more gracefully, ensure that you are passing the CancellationToken correctly. You can refer to this example in our codebase: [Adyen TerminalCloudApi.cs](https://github.com/Adyen/adyen-dotnet-api-library/blob/main/Adyen/Service/TerminalCloudApi.cs#L102).

Additionally, make sure you have configured the timeout settings appropriately. The HttpClientFactory offers a variety of options for configuring timeouts. For more information on configuring timeout intervals to prevent mismatches, please refer to this documentation: [POS Timeouts - Processing Time Out](https://docs.adyen.com/point-of-sale/error-scenarios/pos-timeouts/#processing-time-out).

If you have any further questions, please feel free to reach out.

Best regards,
Djoyke
Adyen
