### ISSUE TITLE
Publish The Xml Document

### ISSUE THREAD

**Issue by stofancy** [Adyen/adyen-dotnet-api-library#1014]
**Is your feature request related to a problem? Please describe.**
When reference the Adyen NuGet package, and developing, There's no document, comment, an any method/arguments description shown up. It's hard to understand the details of every filed in the request, expecially when payment/balance related integration, I have to search the Adyen API document, dive into the Adyen source code to check what's the mean of every fileds and methods.
![image](https://github.com/Adyen/adyen-dotnet-api-library/assets/43318667/fe7bef76-9880-43a9-a313-f7b9ff89ba5b)

![image](https://github.com/Adyen/adyen-dotnet-api-library/assets/43318667/110f5e9d-aae0-42ad-b614-d72ae678a146)

**Describe the solution you'd like**
Could you please generate and release the Xml document when publishing the NuGet package? bellow is want I see after I build from sorce code with the Xml document:
![image](https://github.com/Adyen/adyen-dotnet-api-library/assets/43318667/16ddd3dc-c5c7-4f81-9eb3-48da5961154b)

![image](https://github.com/Adyen/adyen-dotnet-api-library/assets/43318667/269295c6-8cf8-457e-b4bb-f8d173062694)

**Comment by jillingk** [comment]
Hi @stofancy,

I quickly added support for this through this #1021 PR.

Best, Jilling
Adyen
