### ISSUE TITLE
Add support for Click To Pay

### ISSUE THREAD

**Issue by jeppzone** [Adyen/adyen-dotnet-api-library#1020]
**Is your feature request related to a problem? Please describe.**
When making a [Click To Pay](https://docs.adyen.com/payment-methods/cards/click-to-pay/) payment using Adyen's web component, a couple of additional properties (`srcTokenReference`, `srcCorrelationId` for example) are sent in the paymentData from the web component. These are currently not mapped in the `CardDetails` model from what I can see. Are there any plans on adding these properties to support the Click To Pay flow in this library?

**Describe the solution you'd like**
`srcTokenReference`
`srcCorrelationId`
`srcDigitalCardId`
`srcScheme` 
mapped in the CardDetails model
 
**Describe alternatives you've considered**
We are currently rolling our own integration towards the checkout API for the card payment flow to support Click To Pay, and not using this library.

**Comment by ajagelund** [comment]
I need this too!

**Comment by jillingk** [comment]
Hi @jeppzone & @ajagelund,

Thanks for reaching out here, I'm going to look into it! If there are other parameters you are receiving from the web component let me know so we can add them all at once.  

Best, Jilling
Adyen

**Comment by jeppzone** [comment]
Hi @jillingk,

Thanks for your response! I think `srcDigitalCardId` and `srcScheme` are part of the click to pay flow as well which I forgot to mention. 

Best regards,
Jesper

**Comment by jillingk** [comment]
Hi @jeppzone,

Thanks for checking and letting me know! I contacted the respective team and they are working on it. I'll let you all know as soon as they managed to add it.

Best, Jilling
Adyen

**Comment by jeppzone** [comment]
Hi @jillingk,

I can see that some of the fields were added in #1024, but ```srcDigitalCardId``` seems to be missing from that PR.

Any plans on adding that as well? I think it's always present when it's a MasterCard ClickToPay payment.

Best regards,
Jesper

**Comment by jillingk** [comment]
Hi @jeppzone,

I just checked and it seems we're still working on it to also open up these fields!

Best, Jilling
Adyen

**Comment by jeppzone** [comment]
Hi,

Any updates on this?

Best regards,

Jesper

**Comment by wboereboom** [comment]
Hey everyone,

Sorry for the lack of response!
We're digging into the `srcDigitalCardId` field for CardDetails, and we'll get it to be available as soon as possible.

Kind Regards,
Wouter
Adyen

**Comment by DjoykeAbyah** [comment]
Hi @jeppzone and @ajagelund!

I just wanted to quickly notify you that the latest release has srcDigitalCardId included in [Adyen/Model/Checkout/CardDetails.cs](https://github.com/Adyen/adyen-dotnet-api-library/pull/1037/files#diff-bea9ccce909fdb96fff69a5aa48620571aae661badbd870e57d5cbb7c6a620b2) and [Adyen/Model/Checkout/CardDonations.cs](https://github.com/Adyen/adyen-dotnet-api-library/pull/1037/files#diff-55b1f84c1bc82ca68365d1cb1c22f5d7361e8eb6de89f809b69cafdff7a37861)!

Kind Regards,
Djoyke
Adyen
