### ISSUE TITLE
dotnet SDK prior to 16.2.0 not compatible with Webhook transfer with delined transfer

### ISSUE THREAD

**Issue by cedricmel** [Adyen/adyen-dotnet-api-library#1035]
**Describe the bug**
dotnet SDK prior to 16.2.0 not compatible with Webhook transfer with declined transfer

**To Reproduce**
1. Create a refused payment (generating a declined reason)
2. Consume transfer API in test or live with SDK prior to 16.2.0
3. You will get a parsing Error, declined does not exist

you can also use linked payload

**Expected behavior**
Parsing does not fail

**Screenshots**

**Desktop (please complete the following information):**
 - dotnet 
[payload-qa.json](https://github.com/user-attachments/files/16099694/payload-qa.json)
SDK version prior to 16.2.0

**Additional context**

I'm working webhook integration and I'm facing an issue.
On test env there was a change on week 25, where suddenly I received a 'declined' reason value on transfer webhook payload and that was not compatible with SDK version (from 14.2.1 to 16.1.0 th latest version at the moment)

Since then you've published the 16.2.0 who works well in test env, but has some breaking changes with 14.2.1 on PaymentInsttrument StatusEnum where some values have been removed
https://github.com/Adyen/adyen-dotnet-api-library/blob/v16.2.0/Adyen/Model/ConfigurationWebhooks/PaymentInstrument.cs
https://github.com/Adyen/adyen-dotnet-api-library/blob/v14.2.1/Adyen/Model/ConfigurationWebhooks/PaymentInstrument.cs

I need to know if, in live environnement, you still have those values sent in webhook or not, because otherwise it will break integration.

On one hand with 16.2.0 I think it ok in test, but what about live ? and I quite confident in the fact taht their might be a problem between 16.2.0 and Configuration Webhook in live env.

Adyen support is redirecting me to GitHub for answer and I really need help for this case.

**Comment by cedricmel** [comment]
The issue is related with an exchange with support, and is now in live env. I migrated to 16.2.0 yesterday following release from your side.

**Comment by jillingk** [comment]
Hi @cedricmel,

I understand your concern, however you can be rest assured that the difference between test vs live will be non-existent as it is designed that way.

Were you able to check with our support team that the available enum values are indeed the only ones returned?

Best, Jilling
Adyen

**Comment by cedricmel** [comment]
Sorry for the delay, 
actually we moved from 14.2.1 to 16.2.0 and everything seems working fine and I can close this issue.

But still, you might have some issue with other integration as transfer webhook is not compatible with prior SDK.

Regards
