### ISSUE TITLE
Invalid URL generated for possdk session request

### ISSUE THREAD

**Issue by jnischler** [Adyen/adyen-dotnet-api-library#1041]
Dear Adyen Team,

we are facing a problem with this C# library (v18.0.0).

The PosMobileService.cs is building an invalid url:
expected:
https://{prefix}.adyenpayments.com/checkout/possdk/v68/sessions
created:
https://{prefix}.adyenpayments.com/checkout/checkout/possdk/v68/sessions

See:
https://docs.adyen.com/api-explorer/possdk/latest/post/sessions

regards
Julian

**Comment by jillingk** [comment]
Hi @jnischler,

Thanks for reaching out to us here, we will look into this.

For now as a temporary fix you can implement the service and override the base url like this. Apologies for the inconvenience!

Best, Jilling
Adyen

**Comment by jnischler** [comment]
Hey ,

thanks for the reply.
We already did this ;)

regards
Julian

**Comment by mayankst** [comment]
@jnischler Any update regarding this? This is a pretty major bug and have existed for months now. We just wasted two days just because of this.

**Comment by jillingk** [comment]
Hi @mayankst,

This was fixed in #1062.

Best, Jilling
Adyen

**Comment by mayankst** [comment]
@jillingk When will this fix be released?

**Comment by jillingk** [comment]
It was released last weeks version: 21.0.0
