### ISSUE TITLE
PaymentDetails class should support optional issuer field

### ISSUE THREAD

**Issue by roopemerikukka** [Adyen/adyen-dotnet-api-library#1061]
**Is your feature request related to a problem? Please describe.**

We are using Online banking Finland as one of our payment methods. The method supports `issuer` field similarly like the iDEAL method:

```
"paymentMethod": {
    "type": "ebanking_FI",
    "issuer": "nordea"
  }
```

Unfortunately this feature is not documented in the Adyen docs nor supported via the .NET library.

**Describe the solution you'd like**

A solution for the issue would be to allow setting optional `issuer` string field for the [`PaymentDetails`](https://github.com/Adyen/adyen-dotnet-api-library/blob/main/Adyen/Model/Checkout/PaymentDetails.cs) class or create own class for the `ebanking_FI` payment method.

**Describe alternatives you've considered**

The only alternative would be to send the request as JSON as we are not able to easily extend the classes provided by Adyen .NET library.

**Comment by jillingk** [comment]
Hi @roopemerikukka,

Thanks for reaching out here! I'm following up internally to check why this `issuer` field is not available.

Best, Jilling
Adyen

**Comment by roopemerikukka** [comment]
> Hi @roopemerikukka,
> 
> Thanks for reaching out here! I'm following up internally to check why this `issuer` field is not available.
> 
> Best, Jilling Adyen

Hi @jillingk, any news on this matter? :)

**Comment by DjoykeAbyah** [comment]
Hi @roopemerikukka !

You can expect the fix in the upcoming release next week. See pull request #1076 for progress. [Adyen/Model/Checkout/EBankingFinlandDetails.cs](https://github.com/Adyen/adyen-dotnet-api-library/pull/1076/files#diff-61d91fbe191efcb77cca0fd93d1e9b3927a67db3325deb68be36d0c969173d30).

Kind regards,

Djoyke
Adyen

**Comment by DjoykeAbyah** [comment]
Hi @roopemerikukka,

I just wanted to inform you the .NET library has been released and contains the fix in [Adyen/Model/Checkout/EBankingFinlandDetails.cs](https://github.com/Adyen/adyen-dotnet-api-library/pull/1080/files#diff-61d91fbe191efcb77cca0fd93d1e9b3927a67db3325deb68be36d0c969173d30)!

Kind regards,

Djoyke
Adyen
