### ISSUE TITLE
Missing Result Codes for Checkout API

### ISSUE THREAD

**Issue by jaw64** [Adyen/adyen-dotnet-api-library#108]
The [documentation for the Checkout API](https://docs.adyen.com/checkout/payment-result-codes/) lists the following as possible result codes for the `/payments` and `/payments/details` endpoints:

- `AuthenticationFinished`
- `Authorised`
- `Cancelled`
- `ChallengeShopper`
- `Error`
- `IdentifyShopper`
- `Pending`
- `PresentToShopper` (not included in the referenced doc, but I have seen it mentioned elsewhere on the site)
- `Received`
- `RedirectShopper`
- `Refused`

The result codes currently in the [Checkout model `PaymentsResponse.ResultCodeEnum`](https://github.com/Adyen/adyen-dotnet-api-library/blob/cb07fd51cd9e5e6827f461eda1a485b07a10da6a/Adyen/Model/Checkout/PaymentsResponse.cs#L24) are as follows:

- `Authorised`
- `Cancelled`
- `ChallengeShopper`
- `Error`
- `IdentifyShopper`
- `PartiallyAuthorised`
- `PresentToShopper`
- `Received`
- `RedirectShopper`
- `Refused`

Most of documented result codes are included in this .NET SDK (and even an extra one which is not documented -- i.e. `PartiallyAuthorised`) but there are some discrepancies between the two. All of the documented result codes for Checkout API should be in the `PaymentsResponse.ResultCodeEnum`.

**Comment by rikterbeek** [comment]
Hi @jaw64,

The list here could reflect checkout and classic integration.

We have as well this enumClass for classic integration: https://github.com/Adyen/adyen-dotnet-api-library/blob/cb07fd51cd9e5e6827f461eda1a485b07a10da6a/Adyen/Model/Enum/ResultCodeEnum.cs


Regards,
Rik
Adyen

**Comment by jaw64** [comment]
Hi @rikterbeek,

The enum you've referenced is also missing the `Pending` result code.

Regards,
Jordan

**Comment by AlexandrosMor** [comment]
Hello @jaw64,

We are going to review the ResultCodeEnum soon as we are going to move the library to api version v49
