### ISSUE TITLE
OrderAttemptNumber

### ISSUE THREAD

**Issue by jorgenkarlsson** [Adyen/adyen-dotnet-api-library#11]
Hi,

In the documentation:
https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v32/payments

It says:
"When providing the merchantOrderReference value, we also recommend you submit retry.orderAttemptNumber, retry.chainAttemptNumber, and retry.skipRetry values."

I can't find these properties in the library.
Am I missing something or does the library not support these properties?

**Comment by AlexandrosMor** [comment]
Hello @jorgenkarlsson,
 
The retry.orderAttemptNumber, retry.chainAttemptNumber, and retry.skipRetry are keys for the additionalData Dictionary in PaymentRequest. In the PaymentRequest there is  the Dictionary<string, string> AdditionalData field.

Kind regards, 
Alexandros Moraitis

**Comment by AlexandrosMor** [comment]
Hello @jorgenkarlsson 

Did the explanation helped? Do you have more questions about this issue? 

Thank you in advance,
Alexandros Moraitis

**Comment by jorgenkarlsson** [comment]
Hi,

Sorry for the late response. Yes the explanation helped, thank you!
