### ISSUE TITLE
Library compatibility with API v49

### ISSUE THREAD

**Issue by BenjaminFeenstra** [Adyen/adyen-dotnet-api-library#115]
Implementing the new [drop-in solution](https://docs.adyen.com/checkout/drop-in-web) requires API version 49. This .NET library still targets v40 however and renders it incompatible with the drop-in solution. This is because the `/payments` endpoint response has been changed in v49.

**Comment by FrancisYergeau** [comment]
I'm working to install v3.0.2 to use the Drop-In and the API Version is still "v40" I get a Timeout is it the reason?

**Comment by FrancisYergeau** [comment]
I've contacted the support they tell me that the URL is wrong when trying to get the list of paymentMethods:
----
https://checkout-test.adyen.com/checkout//checkout/PaymentSetupAndVerification/paymentMethods/v49 (wrong)
https://checkout-test.adyen.com/checkout/paymentMethods/v49 (correct)
----

Can someone check why?

**Comment by rikterbeek** [comment]
Hi @BenjaminFeenstra,

Thanks for your comment. We will investigate what changes this will bring across  the models. We let you know. For a short term fix you can manually update the version.

Regards,
Rik
Adyen

**Comment by mattsage1991** [comment]
Is there any updates on this? I'm having the same problem where I'm trying to send a payment through the /payments endpoint but the API version in the client library is still v40.

**Comment by yang-xiaodong** [comment]
We also encountered the same problem, I can't find the `action` object in the returned result.

![image](https://user-images.githubusercontent.com/8205994/61436550-9e11b200-a96d-11e9-86e6-7edd336a161e.png)
![image](https://user-images.githubusercontent.com/8205994/61436561-a1a53900-a96d-11e9-9808-fcaa2ef8df88.png)

**Comment by mattsage1991** [comment]
after doing a few tests I realised that the action only gets returned when the api version is set to v49. Anything lower and no action is returned.

**Comment by mattsage1991** [comment]
@yang-xiaodong I ended up cloning the repository and changing the ApiVersion in the ConfigConstants.cs in the end. If you don't want to do that, you could always send the request yourself via HttpClient as you mentioned.

**Comment by Recio** [comment]
Just updated to 3.2.0
Action property is still not available on the response object.

Fiddler shows the comm going to v49 and returning an action object. If you're missing this feature don't update just yet

**Comment by AlexandrosMor** [comment]
Hello @Recio 
Can you check this PR? https://github.com/Adyen/adyen-dotnet-api-library/pull/132

**Comment by Recio** [comment]
I'll test it locally, thanks @AlexandrosMor !

**Comment by AlexandrosMor** [comment]
We will release a new version asap

**Comment by AlexandrosMor** [comment]
The new version 3.2.1 is released.
