### ISSUE TITLE
Services/Checkout.cs and Model/Checkout naming conventions

### ISSUE THREAD

**Issue by tddouglas** [Adyen/adyen-dotnet-api-library#119]
Per merchant feedback, it is confusing to have a Checkout class in Checkout.cs as well as a Checkout directory. Could be worth refactoring the name of checkout.cs

**Comment by rikterbeek** [comment]
Hi @tddouglas,

We have this with more items. I don't see a big problem with this as well we are consistent through all libraries we offer so we want to keep it like this for now.

Regards,
Rik
Adyen
