### ISSUE TITLE
Shopper Interaction serialization serializing incorrectly

### ISSUE THREAD

**Issue by GonathanJawecki** [Adyen/adyen-dotnet-api-library#122]
Hey,

Found an issue with the serialization for the getCostEstimate call in BinLookup.

When making a call to BinLookup -> CostEstimate the field shopperInteraction is getting converted to the enum value and not the string representation.

Example: 
``` json
{
  "amount": {
    "currency": "EUR",
    "value": 1000
  },
  "assumptions": {
    "assume3DSecureAuthenticated": true,
    "assumeLevel3Data": true
  },
  "cardNumber": "4111111111111111",
  "merchantAccount": "<MERCHANT_ACCOUNT>",
  "merchantDetails": {
    "countryCode": "NL",
    "enrolledIn3DSecure": true,
    "mcc": "7411"
  },
  "shopperInteraction": 0
}
```

As you can see the example above serializes the shopperInteraction to 0, this errors out when calling the api endpoint `https://pal-test.adyen.com/pal/servlet/BinLookup/getCostEstimate`, returning:

``` json
{
    "status": 422,
    "errorCode": "000",
    "message": "Invalid shopperInteraction provided",
    "errorType": "validation"
}
```

It should be the following:

``` json
{
  "amount": {
    "currency": "EUR",
    "value": 1000
  },
  "assumptions": {
    "assume3DSecureAuthenticated": true,
    "assumeLevel3Data": true
  },
  "cardNumber": "4111111111111111",
  "merchantAccount": "<MERCHANT_ACCOUNT>",
  "merchantDetails": {
    "countryCode": "NL",
    "enrolledIn3DSecure": true,
    "mcc": "7411"
  },
  "shopperInteraction": "Ecommerce"
}
```

As this returns a valid getCostEstimate response:

```` json
{
    "cardBin": {
        "bin": "411111",
        "issuingBank": "ADYEN TEST BANK",
        "issuingCountry": "NL",
        "paymentMethod": "visa"
    },
    "resultCode": "Unsupported",
    "surchargeType": "ZERO"
}

**Comment by GonathanJawecki** [comment]
Pull request to fix issue here, https://github.com/Adyen/adyen-dotnet-api-library/pull/123

**Comment by martinsrenato** [comment]
Hi @GonathanJawecki ,

Thanks for the pull request. We are going to review it and include on the next release once approved.

Cheers,
Renato Martins
Adyen

**Comment by AlexandrosMor** [comment]
The PR #123 is merged to develop
