### ISSUE TITLE
Missing properties from /payments Request/Response

### ISSUE THREAD

**Issue by bsulliva** [Adyen/adyen-dotnet-api-library#126]
Hello, in the 3DS2 /payments response, I don't see any properties to store the action and authentication objects.

Example:
{"resultCode":"IdentifyShopper","action":{"paymentData":"","paymentMethodType":"scheme","token":"","type":"threeDS2Fingerprint"},"authentication":{"threeds2.fingerprintToken":""},"details":[{"key":"threeds2.fingerprint","type":"text"}],"paymentData":""}

Also, I don't see any properties to store the data for payment methods like Giropay, Sepa, or Ideal for example.

Here is a sample request for Giropay,

"paymentMethod":{
"type":"giropay",
"bic":"DEUTDE2H"
},

And I'm assuming the Github class I should use to post to the /payments API is DefaultPaymentMethodDetails. But I don't see any properties there that reference "bic".

And same thing for Sepa payments,

{ type: "sepadirectdebit", "sepa.ownerName": "A. Klaassen", "sepa.ibanNumber": "NL13 TEST 0123 4567 89" }

There isn't a property that references sepa.ownerName or sepa.ibanNumber.

**Comment by AlexandrosMor** [comment]
Hello @bsulliva,

The fields action and authentication are missing and we will add them as soon as possible.
For your second question the DefaultPaymentMethodDetails contains all the fields for the payment methods. 
In the [documentation](https://docs.adyen.com/payment-methods/sepa-direct-debit#description) sepa is not require bic. Would you like to explain us why do you need this field?

Kind regards,
Alexandros

**Comment by bsulliva** [comment]
Great, thanks Alexandros. Yeah bic field is for Giropay. For Sepa payments, we need "sepa.ownerName" and "sepa.ibanNumber"

**Comment by AlexandrosMor** [comment]
Can you check also this one ? https://github.com/Adyen/adyen-dotnet-api-library/pull/136 
Thank you in advance,

**Comment by AlexandrosMor** [comment]
We released those fields with 3.2.1.

**Comment by bsulliva** [comment]
Thanks Alexandros. Also, I'm a little confused about the different GitHub repositories. I see one that is Adyen, which is where the version 3.2.1 shows up, and the one I have currently installed is Adyen.EcommLibrary. I'm assuming I should use the Adyen (https://github.com/Adyen/adyen-dotnet-api-library) repository? Is the Adyen.EcommLibrary still active?

![image](https://user-images.githubusercontent.com/6124598/62547743-54f5a500-b82b-11e9-9682-6ba9421cb1dd.png)

**Comment by AlexandrosMor** [comment]
Yes the Adyen.EcommLibrary is deprecated. Please use Adyen

Kind regards,

**Comment by bsulliva** [comment]
Good to know. Thanks sir.

**Comment by JREU** [comment]
> Yes the Adyen.EcommLibrary is deprecated. Please use Adyen
> 
> Kind regards,

The Adyen documentation still states that you should use the Adyen.EcommLibrary. Could you perhaps make sure that the documentation is updated? If It were not for this issue I wouldn't have found out that the EcommLibrary is in fact deprecated.

https://docs.adyen.com/development-resources/libraries#csharp

Thank you.

**Comment by AlexandrosMor** [comment]
We are also busy updating the documentation 
kind regards,
Alexandros
