### ISSUE TITLE
Disable Recurring Card

### ISSUE THREAD

**Issue by attefTouina** [Adyen/adyen-dotnet-api-library#13]
Recurring service call the wrong object _listRecurringDetails in this [line ](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen.EcommLibrary/Service/Recurring.cs#L42) [the wrong endpoint] instead of _disable object

Please fix the bug

**Comment by AlexandrosMor** [comment]
Hello @attefTouina 

Thank for reporting it. It is fixed now in develop branch,

Kind regards
Alexandros Moraitis

**Comment by attefTouina** [comment]
Thank you for your efforts.

When this update will be published in Nuget ?

Best regards,

**Comment by AlexandrosMor** [comment]
Hello @attefTouina,
 
The fix is included in version 1.0.5 and it is published on nuget.

Kind regards,
Alexandros
