### ISSUE TITLE
Payment API and recurring processing model

### ISSUE THREAD

**Issue by dario-hd** [Adyen/adyen-dotnet-api-library#143]
Hi guys,

we would like to use this library in our projects. According to the Payment API (https://docs.adyen.com/api-explorer/#/Payment/v46/authorise), there should be a `recurringProcessingModel` member. I can only see that in the Checkout API (https://github.com/Adyen/adyen-dotnet-api-library/search?q=recurringProcessingModel&unscoped_q=recurringProcessingModel). Is there a plan to add it also in the Payment API client? Or, what's your suggested way to use your API in a .NET Core project? We are currently using a generated client using Swagger code generator, but that used the old OpenAPI spec. We tried generating for the latest version but the generated client wasn't working properly...thanks.

**Comment by AlexandrosMor** [comment]
Hello @dario-hd 
It is added in [PR](https://github.com/Adyen/adyen-dotnet-api-library/pull/152)
We are going to release it as soon as possible
kind regards,
Alexandros

**Comment by DsAekb** [comment]
Hello @AlexandrosMor 

`RecurringProcessingModel` is still not presented in `Adyen.Model.PaymentRequest` nor in `Adyen.Model.AbstractPaymentRequest` which is used by `Adyen.Service.Payment.AuthoriseAsync`.

The PR you pointed doesn't add it there.
