### ISSUE TITLE
IdealIssuer property not mapped in DefaultPaymentMethodDetails

### ISSUE THREAD

**Issue by JREU** [Adyen/adyen-dotnet-api-library#144]
Hi,

I'm trying to make a new payment using web drop-in (https://docs.adyen.com/checkout/drop-in-web#step-3-make-a-payment). Using AJAX i'm calling my WebAPI controller which in turn should create a payment using the Adyen nuget package. 

In my WebAPI controller I'm using the DefaultPaymentMethodDetails object as parameter (which I think is the right type?) to map the incoming JSON. Which works for creditcard, Klarna, etc. But for iDeal the issuer doesn't get mapped because the drop-in javascript library sends the issuer in the "issuer" property and the DefaultPaymentMethodDetails object doesn't have an "issuer" property but instead has an "idealIssuer" property. Am I missing something?

I could ofcourse create my own object which correctly maps the incoming "issuer" property to the "idealIssuer" property of the DefaultPaymentMethodDetails object. But I do not want to update my own models every time the properties in the Adyen package are changed.

**AJAX call**

```
$.ajax({
        url: "/api/adyen",
        data: JSON.stringify(state.paymentMethod),
        type: "POST",
        contentType: "application/json", 
        success: (result) => {
            ...
        },
        error: (error) => {
            ...
        }
    });
```

**JSON that's being sent to WebAPI controller**

```
{"type":"ideal","issuer":"1153"}
```

**WebAPI controller**

```
[HttpPost]
public void Post([FromBody]Adyen.Model.Checkout.DefaultPaymentMethodDetails paymentMethod)
{
  ...         
}
```

**Comment by bezirg** [comment]
I ran into the same problem. I fixed it temporarily by manually setting the value in the .NET side:

```csharp
paymentRequest.PaymentMethod.IdealIssuer =  "the ideal issuer that came from the shopper"
```

Another possible way w.o modifying the library is to set it in the JS dropin side, by copying over `issuer` to `idealIssuer` attribute:

```js
const callPayment = (data, config = {}) => {
  const paymentsConfig = { ...paymentsDefaultConfig, ...config };
  const paymentRequest = { ...paymentsConfig,
            // the following line copies issuer to idealIssuer
           paymentMethod: {...data.paymentMethod, idealIssuer:data.paymentMethod.issuer }};

  return fetch(`/payments`, { method: 'POST', headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
  }, credentials: 'include', body: JSON.stringify(paymentRequest)}).then(async response => response.json())
  }
```

Btw, I am running on test environment at the moment.

**Comment by praneethparupudi** [comment]
I was about to raise this issue and saw this. Not sure yet if there are more field miss-matches between the API library and drop in widgets.

**Comment by AlexandrosMor** [comment]
Hello, 

We are going to fix the issue on the library side as soon as possible.

kind regards,
Alexandros
