### ISSUE TITLE
PaymentRequest missing in PosPaymentLocalApi

### ISSUE THREAD

**Issue by mithesh109** [Adyen/adyen-dotnet-api-library#145]
Hi,

I'm using Terminal API through LAN communication to communicate with the terminal.

My code fails on this particular line in PosPaymentLocalApi.cs
 var response = _terminalApiLocal.Request(serializeSaleToPoiRequestMessageSecured, remoteCertificateValidationCallback);

The error message (HTTP Exception) I receive is:

{ "errors": [ "At SaleToPOIRequest, field PaymentRequest: Missing", "At SaleToPOIRequest: Missing" ], "warnings": [ "At SaleToPOIRequest.MessageHeader, field SecurityTrailer: Unexpected", "At SaleToPOIRequest.MessageHeader, field NexoBlob: Unexpected" ] }

I see that when the message is being serialized MessagePayload does change to PaymentRequest and then the encryption happens.

Please let me know why does it still consider MessagePayload instead of PaymentRequest.

**Comment by AlexandrosMor** [comment]
Hello @mithesh109,

The payment request that you provide via local communication should be encrypted. The encryption credentials are unique per terminal and should be set in the adyen's back office. Could please confirm that the encryption credential are correct?

Kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @mithesh109,

I believe that your question was answered. Please let us know if you have more questions,

Kind regards,
Alexandros
