### ISSUE TITLE
Readme with how to perform proper Exception Handling

### ISSUE THREAD

**Issue by Recio** [Adyen/adyen-dotnet-api-library#156]
Hi, 

I like what you guys have done regarding the response codes from the Adyen API, however I think the exception name has room for improvement as it may be confused with a native .net exception.

A readme document regarding exception handling along with a possible renaming of the exception thrown to be more "Proprietary" would be great, as the main methods (Payments, PaymentDetails, etc) for the Adyen checkout also don't mention exceptions thrown.

What do you think? :)

**Comment by AlexandrosMor** [comment]
Hello @Recio,

Thank you for the suggestion. We will talk internal about it and I will late you know as soon as possible.

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @Recio,

Renaming the exception is difficult as it might brake implementations. Adding more details in the readme file about the exception handling is something that we can work on. 

Kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hi,
I will have to close this issue as there are no actions from our side for now 
regards, 
Alexandros
