### ISSUE TITLE
Serialization Exception

### ISSUE THREAD

**Issue by bsulliva** [Adyen/adyen-dotnet-api-library#160]
Hello, I have added a property on my existing class which is marked as [Serializable] since it's stored session. The new property is, public PaymentRequest AdyenPaymentRequest { get; set; }

Since the PaymentRequest class is not marked as [Serializable], I get the following exception:

SerializationException: Type 'Adyen.Model.Checkout.PaymentRequest' in Assembly 'Adyen, Version=3.2.1.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.

The only way I know to fix this is to add the [Serializable] attribute to the PaymentRequest class, is that something you guys can do? Or do you have any suggestions to get around this issue?

Thanks

**Comment by AlexandrosMor** [comment]
Hello, @bsulliva,

Are you using System.Runtime.Serialization? If you annotate the property PaymentRequest AdyenPaymentRequest with DataMember is it throwing an exception again ?

kind regards

**Comment by AlexandrosMor** [comment]
Hello @bsulliva,

Thank you for the feedback, you can use your solution and if we see the need in the future to annotate the classes to [Serializable] we are going to do it for all of them. I will close this issue.

kind regards,
Alexandros
