### ISSUE TITLE
resultcode : PresentToShopper is missing

### ISSUE THREAD

**Issue by lslimelife** [Adyen/adyen-dotnet-api-library#161]
for voucher payments, this code is missing
resultCode = PresentToShopper
Use case : voucher (boleto / Brazil)

**Comment by AlexandrosMor** [comment]
Hello @lslimelife,

We will add it as soon as possible. 

Kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Can you test this [pr](https://github.com/Adyen/adyen-dotnet-api-library/pull/164)? 
Thank you
