### ISSUE TITLE
Nexo service: crypto error

### ISSUE THREAD

**Issue by lifecoder-phoenix** [Adyen/adyen-dotnet-api-library#162]
Hi,
For the company I work for I have to design a payment driver using your implementation, this implementation was working fine last week but now however I get the error in the title.
So did something change lately that is not yet reflected in this repo?
Thanks

**Comment by AlexandrosMor** [comment]
Hello @lifecoder-phoenix,

Would you like to provide us more information about the error? As we did not make any updates to the library for nexo it is difficult to know why the implementation was working and now not. 

Kind regards,

**Comment by lifecoder-phoenix** [comment]
Sure, so I setup a test key(because I get an error without encryption even in test whilst the documentation says otherwise) so this is my code to initialize the client:
`this.AdyenConfig = new Config() { Endpoint = "https://" + _terminalIP + ":8443/nexo/", HttpRequestTimeout = 300000, Environment = Adyen.Model.Enum.Environment.Test};
                this.AdyenClient = new Client(this.AdyenConfig);
                this.AdyenEncryption = new EncryptionCredentialDetails()
                {
                    KeyVersion = 0,
                    KeyIdentifier = "MyKey",
                    Password = "MyTestPassphraseBecauseItsRequired"
                };`
And then I make a request: `var api = new PosPaymentLocalApi(this.AdyenClient);
//here is the creation of the saleToPoiRequest, not included because it's pretty long
var response = api.TerminalApiLocal(saleToPoiRequest, AdyenEncryption);
`
Then I get an error in HttpUrlConnectionClient.cs, error code 401 unauthorized and the response body is "{\"errors\": [\"Nexo Service: crypto error\"]}"
Stacktrace: "   at Adyen.HttpClient.HttpUrlConnectionClient.Request(String endpoint, String json, Config config, Boolean isApiKeyRequired, RequestOptions requestOptions) in D:\\Sample (Version 4.0.0)\\PAY_ADYEN\\Adyen\\HttpClient\\HttpURLConnectionClient.cs:line 80\r\n   at Adyen.Service.ServiceResource.Request(String json, RequestOptions requestOptions) in D:\\Sample (Version 4.0.0)\\PAY_ADYEN\\Adyen\\Service\\ServiceResource.cs:line 47\r\n   at Adyen.Service.PosPaymentLocalApi.TerminalApiLocal(SaleToPOIMessage saleToPoiRequest, EncryptionCredentialDetails encryptionCredentialDetails) in D:\\Sample (Version 4.0.0)\\PAY_ADYEN\\Adyen\\Service\\PosPaymentLocalApi.cs:line 65\r\n   at PAY_ADYEN.PayAdyen.Pay(Object parameters) in D:\\Sample (Version 4.0.0)\\PAY_ADYEN\\PayAdyen.cs:line 278"

**Comment by AlexandrosMor** [comment]
Thank you for your feedback, we improved the certificate validation for local communication. I would like to ask if the certificate is properly installed in the CA store. For reference check the [docs](https://docs.adyen.com/point-of-sale/choose-your-architecture/local/secure-local-communications)

**Comment by lifecoder-phoenix** [comment]
Well to be perfectly honest I did not want to install the certificate on my own machine and patched out the certificate check. Is the certificate used in the encryption of the request? (except ssl)

**Comment by AlexandrosMor** [comment]
The certificate is used for the https communication. The encryption of the request is done internal in the library using the encryption credentials that you can set in the adyen's back office

**Comment by lifecoder-phoenix** [comment]
I see, well the https connection succeeds since it always returns true on all certificates(I'd have to change that in production probably) So I have no clue where this error is suddenly coming from. The only thing I can think of is the wrong key/identifier/version but I triple checked that

**Comment by AlexandrosMor** [comment]
Did you also check the xapi key ?

**Comment by lifecoder-phoenix** [comment]
I thought that was not needed in local communications?

**Comment by AlexandrosMor** [comment]
Indeed, are you maybe using a different terminal with other encryption credentials? Furthermore Is the terminal id correct?

**Comment by lifecoder-phoenix** [comment]
The terminal id is correct, I've changed the SaleID now since it was hardcoded. Let's see

**Comment by lifecoder-phoenix** [comment]
Sadly that didn't do the trick

**Comment by AlexandrosMor** [comment]
The only thing that changed if I understand correct is that you update the adyen library. With the old version used to worked properly? I will try to reproduce it and I will let you know.

**Comment by lifecoder-phoenix** [comment]
Yeah, the previous version worked. I'll try to downgrade and test too, sorry that I haven't thought of that sooner

**Comment by AlexandrosMor** [comment]
I manage to reproduce the same error by setting the AdyenCryptoVersion to 4. It should be 1. Can you please retry with this change?

**Comment by lifecoder-phoenix** [comment]
I have, for some reason it still throws the error. I'll downgrade now and see if that changes anything

**Comment by lifecoder-phoenix** [comment]
Still the same... Then it must be me setting something incorrectly. How often does it synchronize with the panel? Do I need to restart it for that?

**Comment by AlexandrosMor** [comment]
if you change any settings in the back office the terminal should also sync with the changes. From the admin menu of the terminal you need to update the configuration

**Comment by AlexandrosMor** [comment]
I will close the issue as it relates to configuration and not a technical issue

**Comment by lifecoder-phoenix** [comment]
Sure! Thank you for your time and help :)
