### ISSUE TITLE
Adding async/await to IClient interface

### ISSUE THREAD

**Issue by mwitlok** [Adyen/adyen-dotnet-api-library#17]
Hi,
Have you thought to add asynchronous versions of the Request() and Post() methods of the various operations?

Currently it's possible to provide a seperate implementation of the IClient interface, but since it currently doesn't have methods that return Tasks it's difficult to use this library with an async flow from end-to-end.

**Comment by AlexandrosMor** [comment]
Hi @mwitlok ,

It looks that it make sense to add asynchronous versions for Request and Post. We will add them to  the following release.

**Comment by AlexandrosMor** [comment]
Hello @mwitlok,

It is added in 1.1.2 version. You can downloaded from nuget. If you have more questions please let us know

kind regards,
@AlexandrosMor
