### ISSUE TITLE
Retrieving transactions of a payout

### ISSUE THREAD

**Issue by BoutemineOualid** [Adyen/adyen-dotnet-api-library#170]
Hello everyone,

Is there an API endpoint or a method within the SDK that allows me to obtain the list of transactions tied to a particular payout.

Thanks

**Comment by AlexandrosMor** [comment]
Hello @BoutemineOualid,

I would like to ask if the specific endpoint that are you referring is in adyen [docs ](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v50/overview)
kind regards,
Alexandros

**Comment by BoutemineOualid** [comment]
Hi @AlexandrosMor, 

I have already checked,
The endpoint that returns the transactions log is described here : https://docs.adyen.com/api-explorer/#/Fund/v5/accountHolderTransactionList

The documentation does not specify whether or not the transaction objects for a particular payout can be requested directly using a query param. I have noticed that there is a field in the transaction object that refers to the payout (payoutPspReference) but I am not sure if it could be used group the transactions by a particular payout.

Thanks for your help, much appreciated,

**Comment by AlexandrosMor** [comment]
I added in our list and we will pick the issue as soon as possible. 
For more information about the payout usage you can contact our [support team ](https://support.adyen.com/hc/en-us)
