### ISSUE TITLE
Please support the NuGet.org symbol server or sourcelink

### ISSUE THREAD

**Issue by ArntWork** [Adyen/adyen-dotnet-api-library#176]
Hi, trying to debug an issue, I found myself wanting to step into the Adyen library. I found no support for the NuGet.org symbol server or Sourcelink ( https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server/ and https://github.com/dotnet/sourcelink/#using-sourcelink ), so I ended up building it myself, then replacing a dll in the package NuGet downloaded. 

I think either of these 2 would make the debugging experience a bit nicer.

(My bug ended up being in my own code, but it was not obvious to find it from the error returned by the library.)

**Comment by AlexandrosMor** [comment]
Hello @ArntWork,

Thank you for posting the issue. It is a good suggestion. We will investigate how it is possible to improve package debugging experience with the NuGet.org symbol server

kind regards,
Alexandros
