### ISSUE TITLE
3D secure version 2.0

### ISSUE THREAD

**Issue by markybry** [Adyen/adyen-dotnet-api-library#19]
Are there any plans to support the new 3d secure 2.0 API. It will be required in Europe by sept 2019 I believe.

**Comment by rikterbeek** [comment]
Hi @markybry,

Yes definitely something we will add. We are first adding checkout into the library after that we can include the 3D secure 2.0 endpoints as well.

Regards,
Rik
Adyen

**Comment by markybry** [comment]
Would you open to accepting pull requests in the future to help with this?

**Comment by rikterbeek** [comment]
HI @markybry,

Yes of course, that would be awesome!

Regards,
Rik
Adyen
