### ISSUE TITLE
No RecurringProcessingModel in Adyen.Model.PaymentRequest

### ISSUE THREAD

**Issue by DsAekb** [Adyen/adyen-dotnet-api-library#190]
Hello @AlexandrosMor 

`RecurringProcessingModel` is still not presented in `Adyen.Model.PaymentRequest` nor in `Adyen.Model.AbstractPaymentRequest` which is used by `Adyen.Service.Payment.AuthoriseAsync`.

The PR you pointed doesn't add it there.

_Originally posted by @DsAekb in https://github.com/Adyen/adyen-dotnet-api-library/issues/143#issuecomment-552466924_

**Comment by rikterbeek** [comment]
Hi @DsAekb,

Thanks for making this clear to us. We will investigate and add it into the model. Feel free to always make a PR to add missing fields.

Regards,
Rik
Adyen

**Comment by AlexandrosMor** [comment]
fixed #203

**Comment by DsAekb** [comment]
> fixed #203

No, it is not. There is still no `RecurringProcessingModel` in `Adyen.Model.PaymentRequest` nor in `Adyen.Model.AbstractPaymentRequest`.

**Comment by AlexandrosMor** [comment]
@DsAekb Can you check if this [PR](https://github.com/Adyen/adyen-dotnet-api-library/pull/218) fixes the issue

**Comment by DsAekb** [comment]
Thanks for a quick reply, this should fix the issue.
