### ISSUE TITLE
PosPaymentCloudApi - Add async methods

### ISSUE THREAD

**Issue by jsheetzati** [Adyen/adyen-dotnet-api-library#191]
Can you please add an additional method signature to the PosPaymentCloudApi class that allows us to call an async version of `TerminalApiCloudAsync`.

Hoping to implement something like `await payment.TerminalApiCloudAsync(request)` in our code.

**Comment by AlexandrosMor** [comment]
Hello @jsheetzati,

The TerminalApiCloudAsync returns async the result. It is always going to return initially but not the full payment response. Would you like to explain us where is the benefit for you to make the TerminalApiCloudAsync an async method? 

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @jsheetzati,

Did you had some time to check my response on your recommendation ? 

regards,
Alexandros

**Comment by jsheetzati** [comment]
TerminalApiCloudAsync may be an async method on your end with a quick response time. However, without providing a Task that we can await, our code is now operating synchronously waiting for a response from TerminalApiCloudAsync. I understand that this should be quick, but we are effectively losing a thread by making synchronous HTTP calls and waiting for a result.

We are going to create our own REST client so you can close this if you would like. Thank you

**Comment by martinmolin** [comment]
Hello @AlexandrosMor 

I think what @jsheetzati is saying is that the TerminalApiCloudAsync method is not marked as **async** so it is not awaitable.
```
/// <summary>
/// CloudApi asynchronous call
/// </summary>
/// <param name="saleToPoiRequest"></param>
/// <returns></returns>
public SaleToPOIResponse TerminalApiCloudAsync(SaleToPOIMessage saleToPoiRequest)
{
    var serializedMessage = _saleToPoiMessageSerializer.Serialize(saleToPoiRequest);
    var response = _terminalApiAsync.Request(serializedMessage);
    this.Client.LogLine("Response: \n" + response);
    if (string.IsNullOrEmpty(response) || string.Equals("ok", response))
    {
        return null;
    }
    return _saleToPoiMessageSerializer.Deserialize(response);
}
```

Regards,
Martin

**Comment by AlexandrosMor** [comment]
Hello @martinmolin,

The TerminalApiCloudAsync uses the endpoint https://terminal-api-test.adyen.com/async. Using this method you receive the response asynchronously. This will return a 200 HTTP OK response, confirming that we received your request and the transaction will continue. 
In case of /sync you receive the result of your transactions synchronously and this request must use an extended time-out of more than 120 seconds. During this time the connection is kept alive and a synchronous response.
You can find more in [adyen's docs](https://docs.adyen.com/point-of-sale/choose-your-architecture/cloud)

Kind regards,
Alexandros

**Comment by jsheetzati** [comment]
@martinmolin is getting what I was trying to say. It doesn't matter if we are hitting /async or /sync, the Adyen library itself is making a  synchronous request to your endpoint. All of our other API calls use async Tasks that we can await. I understand /async will return nearly immediately, however, it doesn't change the fact that the Adyen library is doing that synchronously

Seems like all of the IO in this method happens synchronously:
  1) writing to the request stream
  2) sending/receiving the request
  3) reading the response stream.

https://github.com/Adyen/adyen-dotnet-api-library/blob/8f89f10062ebbd47cb684fb6c90a24cd9127450d/Adyen/HttpClient/HttpURLConnectionClient.cs#L44

We are creating our own REST client so we can keep using async as we do for everything else in our application.

**Comment by AlexandrosMor** [comment]
Hello @jsheetzati,

I understand your point and we are going to add a Task method. Let us know if you want to open a PR about this issue or we can do it . 

kind regards,
Alexandros,
