### ISSUE TITLE
Cancel and CancelOrRefund : Missing ModificationAmount in request

### ISSUE THREAD

**Issue by KouryouChairudo** [Adyen/adyen-dotnet-api-library#193]
The request for Cancel and CancelOrRefund are missing the implementation of ModificationAmount based on the documentation. Is it possible to implement?

[https://docs.adyen.com/api-explorer/#/Payment/v51/cancelOrRefund]()
[https://docs.adyen.com/api-explorer/#/Payment/v51/cancel]()

**Comment by AlexandrosMor** [comment]
Hello @KouryouChairudo,

This two endpoints are already implemented. You can check [here](https://github.com/Adyen/adyen-dotnet-api-library/tree/develop/Adyen/Service/Resource/Modification) 

kind regards,
Alexandros

**Comment by KouryouChairudo** [comment]
I understand that the endpoints are implemented, but I'm not able to supply the amount for the refund or cancel in both methods as the model does not support it. After reading the documentation I assumed I can pass this information.

However after rereading I see it is not allowed for Cancel, but why is it documented on that request then.

**modificationAmount** 
The amount that needs to be captured/refunded. Required for /capture and /refund, **_not allowed for /cancel_**. The currency must match the currency used in authorisation, the value must be smaller than or equal to the authorised amount.

The implementation of the refund request
    public class RefundRequest : AbstractModificationRequest
    {
        [DataMember(Name = "modificationAmount", EmitDefaultValue = false)]
        public Amount ModificationAmount { get; set; }
        ...

is not present in 

    public class CancelOrRefundRequest : AbstractModificationRequest
    {
         ...

and 

    public class CancelRequest: AbstractModificationRequest
    {
         ...
