### ISSUE TITLE
Adyen client proxy support

### ISSUE THREAD

**Issue by polskyDev** [Adyen/adyen-dotnet-api-library#202]
Hello everyone,

Is there any way to set proxy for HttpClient in Adyen?

Thanks

**Comment by AlexandrosMor** [comment]
Hello @polskyDev,

Would you like to explain us more what would be the benefits adding the proxy for HttpClient?

Kind regards,
Alexandros

**Comment by polskyDev** [comment]
Hello @AlexandrosMor 

We have company policy and we can't get access to the outside without proxy.

Kind regards,
Daniel

**Comment by polskyDev** [comment]
I created PR https://github.com/Adyen/adyen-dotnet-api-library/pull/217 with solution.

**Comment by AlexandrosMor** [comment]
Thank you for the PR we are going to review it and we will merge it soon

**Comment by polskyDev** [comment]
Hello @AlexandrosMor 

When you will release update nuget package with proxy support which i added?
It is very important for us.

Kind regards,
Daniel

**Comment by trikk86** [comment]
Hi @AlexandrosMor 

It would really cool if we got any ETA on the release with proxy :)

Kind Regards,
Rafal

**Comment by AlexandrosMor** [comment]
Hi @trikk86 

I believe this Friday we are going to make a release,

kind regards,

**Comment by AlexandrosMor** [comment]
FIxed with release 5.1.0
