### ISSUE TITLE
Compatilbility with the checkout adyen.js and the live servers

### ISSUE THREAD

**Issue by caveman-dick** [Adyen/adyen-dotnet-api-library#227]
Hi

I have found a compatibility issue with the v3.4.0 drop-in component and this library @ v3.4.0. The issue is with the CheckoutPaymentsAction where the Type property is not being serialized if the CheckoutActionType is set to QrCode as the property has an EmitDefaultValue set to false. This issue seems to be fixed with v5.1.0 of this library as the type is now nullable but there isn't a corresponding version of the adyen.js here:

https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/5.1.0/adyen.js

Is it ok to upgrade to this library version, will it be compatible with the v3.4.0 of adyen.js and will the library also be compatible with the live servers?

Thanks

**Comment by AlexandrosMor** [comment]
Hello @caveman-dick,

Thank you for  your message, we are going to look into the issue and reply to you as soon as possible.

regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello Richard,

The version of the adyen-dotnet-api-library is not matching with the version of drop-in component. Furthermore adyen-dotnet-api-library is compatible with the latest checkout api version v51. Can you explain us more how the  EmitDefaultValue annotation causing issues? 

regards,
Alexandros

**Comment by caveman-dick** [comment]
If version 3.4.0 of this library is used which matches the latest drop-in version then the EmitDefaultValue false means it doesn't serialize the first value in the enum. As the Type field on the CheckoutPaymentsAction was not nullable, the default was set to be the first in the CheckoutActionType which was QRCode. 

In the drop-in javascript that field is required for the flow so it was throwing an exception.

Upgrading to v5.1.0 of this library seemed to fix that issue, but we just wanted confirmation that this was a supported scenario. By the sounds of what you are saying it is supported to have these at different versions? Should we always be using the latest version of this library?

**Comment by AlexandrosMor** [comment]
Hello Richard,
I believe that now the issue with the EmitDefaultValue is fixed in version 5.1.0. 
The version of the adyen-dotnet-api-library is not the same with the version of drop-in component. Furthermore adyen-dotnet-api-library is compatible with the latest checkout api version v51.  Hope it helps,

regards,
Alexandros
