### ISSUE TITLE
HTTP Error - Unauthorized

### ISSUE THREAD

**Issue by Eibx** [Adyen/adyen-dotnet-api-library#228]
If I try to call `paymentMethods` manually with a RestClient as seen below, I get the expected result.

```csharp
var restClient = new RestClient(endpoint); // https://checkout-test.adyen.com/v51/
restClient.Authenticator = new HttpBasicAuthenticator(username, password);
restClient.AddDefaultHeader("x-API-key", apiKey);

var restRequest = new RestRequest("paymentMethods", Method.POST);
restRequest.AddJsonBody(new
{
    merchantAccount = merchant,
    countryCode = countryCode
});

var response = restClient.Execute(restRequest);
```

But when I'm trying to call `PaymentMethods` through this library I get the following response body:
```json
{ 
    "status":401,
    "errorCode":"000",
    "message":"HTTP Status Response - Unauthorized",
    "errorType":"security"
}
```

I've tried using all four constructors on `Client`, and I'm using the same API key, username and password in both examples.

```csharp
var config = new Config()
{
    Username = username,
    Password = password,
    XApiKey = apiKey,
};

var client = new Client(config);
client.SetEnvironment(Environment.Test);

var checkout = new Checkout(client);

var paymentMethodsRequest = new PaymentMethodsRequest(merchantAccount: merchant)
{
    CountryCode = countryCode,
};

var response = checkout.PaymentMethods(paymentMethodsRequest);
```

Any help will be greatly appreciated.

**Comment by AlexandrosMor** [comment]
Hello @Eibx  

Could you create a client using only the xapi key like the following example ?
`var client = new Client(apikey, Model.Enum.Environment.Test);`
The client needs username and password or the xapi key. Not both. 
The error 401 means wrong credentials.

Kind regards,
Alexandros

**Comment by Eibx** [comment]
Hi Alexandros,

Thank you for your quick reply.

I've tried the different combinations of username/password and API key. But I still get the same result.

```csharp
var client = new Client(apiKey, Environment.Test);
var checkout = new Checkout(client);

var paymentMethodsRequest = new PaymentMethodsRequest(merchantAccount: merchantAccount)
{
    CountryCode = countryCode,
};

var response = checkout.PaymentMethods(paymentMethodsRequest);
```

I've also ensured during debugging that all the variables have the values I expect.

**Comment by AlexandrosMor** [comment]
I believe the xapi key is wrong. Could you try your example code without 
`restClient.Authenticator = new HttpBasicAuthenticator(username, password);` ?

**Comment by Eibx** [comment]
Hi Alexandros,

Thank you for you help.

Removing the HttpBasicAuthenticator does give the same Unauthorized error.

Then it must be the xapi key. I'll try to get a new one and see if this fixes the issue.

**Comment by AlexandrosMor** [comment]
Hi

Ok good to know, Let us know if you need any help from us in future. 

kind regards,
Alexandros
