### ISSUE TITLE
Collect user input issue (MenuButtons): a display response containing an array as a value cannot be deserialized due to a bug in Newtonsoft.Json bug

### ISSUE THREAD

**Issue by skolbin-ssi** [Adyen/adyen-dotnet-api-library#230]
A display response containing an array as a value cannot be deserialized due to a bug in Newtonsoft.Json described here [https://github.com/JamesNK/Newtonsoft.Json/issues/2273](https://github.com/JamesNK/Newtonsoft.Json/issues/2273)

**Comment by AlexandrosMor** [comment]
Hello @skolbin-ssi 
We are going to pick this one as soon as possible. We created an internal ticket to investigate it and we will let you know

regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Can you send us which field specific cannot be serialized ? 

regards,
Alexandros

**Comment by skolbin-ssi** [comment]
Hi Alexandros,

Whenever I try to collect user input from M400 via Menu Buttons the Newtownsoft.Json library fails to deserialize the payment response's message payload.

The exception and the stack trace are below:

$exception	{"Unexpected character encountered while parsing value: [. Path 'InputResult.Input.MenuEntryNumber', line 10, position 26."}	Newtonsoft.Json.JsonReaderException



		StackTrace	"   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)\r\n   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()\r\n   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at Adyen.CloudApiSerialization.Converter.JSonConvertDeserializerWrapper`1.DeserializeObject(String objectToDeserialize) in 

I have also attached a code snippet for the display request.
[DisplayRequest-MenuButtons.txt](https://github.com/Adyen/adyen-dotnet-api-library/files/4276275/DisplayRequest-MenuButtons.txt)

**Comment by AlexandrosMor** [comment]
Hello @skolbin-ssi,

We reproduced the issue and it looks like indeed a bug from  Newtonsoft. We will try to come up with a solution as soon as possible.

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @skolbin-ssi 
I open a [PR](https://github.com/Adyen/adyen-dotnet-api-library/pull/236) for this issue. Is it possible to test it and confirm that solves the issue for you ? 

kind regards,
Alexandros
