### ISSUE TITLE
Collect user input issue - decimalString Display Input command type is not supported

### ISSUE THREAD

**Issue by skolbin-ssi** [Adyen/adyen-dotnet-api-library#231]
is decimalString Display Input Command type supported by all modern/non-legacy Adyen payment terminals? This Display Input Command type is present in the integration library, but M400 does not appear to understand this type of input. The primary goal is to collect a custom tip amount which may be fractional, and passing "AskGratuity" as a Tender Option is not always a viable technique to collect tip amount in a retail transaction flow, while the secondary goal is to avoid displaying a virtual keyboard on the terminal when collecting a tip.

**Comment by AlexandrosMor** [comment]
Hello @skolbin-ssi,

We are  going to create an internal issue for this pick it up as soon as posible.

regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @skolbin-ssi,

So far decimalString is not supported from our terminals. There are two ways to "AskGratuity". first as a Tender Option and also with the virtual keyboard. We are going to close the issue and for more information please contact adyen support. 

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
We released the 5.2.1 in nuget.
