### ISSUE TITLE
Read idempotent response

### ISSUE THREAD

**Issue by ZNS** [Adyen/adyen-dotnet-api-library#232]
Your documentation states "To verify that a request was processed idempotently, check the Idempotency-Key HTTP header returned in the response." Is this possible using this library? Otherwise I'd really like to see support for this, since it seems to support passing an idempotency token in the requests.

**Comment by RiaanVR** [comment]
Adding a One Up here 👍 as I am also at this point and hoping for a response from @AlexandrosMor about how to achieve this. 

The API documentation speaks of interpreting the header or looking at the ErrorCode which should be 703, this is a bit arbitrary as the library doesn't have an enum of sorts or different subtyped ServiceErrors that allow to easily identify this state.


Right now we've generated a client from the OpenApi specs of the API but it was when version 31 was released of the Checkout APIs this is already out of date and want to move our implementation to the Adyen supported library, but need some clarity on this before proceeding.

**Comment by AlexandrosMor** [comment]
Hello @ZNS , 
Yes the library supports idempotency keys. The way to pass the Idempotency-Key HTTP in the header is from the requestoptions for example:    
`payment.Authorise(paymentRequest, new RequestOptions{ IdempotencyKey=idempotency});`
Let us know if it helps

regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @RiaanVR,

Could you explain us more what enums are missing from the library? You can always make a PR. Of course you can move your implementation to Adyen supported library. We update the endpoints and the fields based on the latest Adyen api version

regards,
Alexandros

**Comment by RiaanVR** [comment]
Hi @AlexandrosMor 

Thanks for the quick response, I am referring to this document. 
https://docs.adyen.com/development-resources/api-idempotency/#designing-for-resilience

It specifies two cases 
1. The request was already processed will return with HTTP status: 409 error 704: "request already processed or in progress".
2. The service was unavailable, with HTTP status 504 error code 703: "required resource temporarily unavailable"

How should one handle these two cases if the library only exposes the PaymentsResponse and in error cases, I am assuming [this](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/ServiceError.cs) class will be filled with the codes above.

So the question is; should I do a string comparison on the error code and error message or is there a more OOP supported manner?

**Comment by AlexandrosMor** [comment]
Hello @RiaanVR,

For the 2 cases that you described the http client will return an error message with the http status code and you can handle it depends of the code.  Here is the [line](https://github.com/Adyen/adyen-dotnet-api-library/blob/648ad398fca2b754731006409b7334495a48642d/Adyen/HttpClient/HttpURLConnectionClient.cs#L69) that handle the exception and returns the status code

**Comment by AlexandrosMor** [comment]
Hello @RiaanVR,

For now we are closing this issue. If you have further questions please open a new issue or contact Adyen's tech support. 

kind regards,
Alexandros

**Comment by SeanErvinson** [comment]
Hi @AlexandrosMor, have the same question is there a way to differentiate between the two responses (original and the retried one)? Based on my testing there's no real differentiating field that can be used to determine that it was a retried response.
