### ISSUE TITLE
Unable to deserialise into notification models due missing default constructors

### ISSUE THREAD

**Issue by RyanONeill1970** [Adyen/adyen-dotnet-api-library#237]
When setting up notification webhooks it makes sense for the integrator to use the types already built into the library for receiving the inbound data but these types often do not have default constructors. They do have JSON instructions built into the class which implies they are meant to be bound to in this way. Attempting to do so has wasted many hours.

For example, setting up an MVC (5, not core) action to handle an inbound request it makes sense to use the NotificationRequest type but this will not bind correctly. The following code binds the simple property 'Live' but not the property with type NotificationRequestItem.

`
        [Route("order-notification")]
        [HttpPost]
        public ContentResult OrderNotification([System.Web.Http.FromBody] NotificationRequest model)
        {
`

This is due in part to the Amount type (used in a sub object) not having a default constructor so the MVC Model Binder cannot create an instance and populate the properties. It then fails silently, returning a null.

Adding these constructors should not be a breaking change as it does not change existing code. The only way I have found around this is to copy the structure of the library notification objects and duplicate them in my own code to receive the posted details. This makes it likely that I'll miss something, introduce a bug and also takes longer.

**Comment by AlexandrosMor** [comment]
Hello @RyanONeill1970,

I understand the necessity of the default empty constructors. The models are generated from the open api specs. If a property is marked as required then it is added in the constructor to define those values. It is not in the plan for now to extend the library classes and add default empty constructors.

kind regards,
Alexandros
