### ISSUE TITLE
Inconsistent use of camelCasing vs PascalCasing

### ISSUE THREAD

**Issue by RyanONeill1970** [Adyen/adyen-dotnet-api-library#238]
When using notifications the data sent to the endpoint has inconsistent naming. For example, the following snippet shows properties starting with lower and uppercase characters. This may sound like a small issue but it took a while to go through tests and make sure that it was not the property names which were causing issues with MVC Model Binding.

`
{
  "live":"false",
  "notificationItems":[
  {
  "NotificationRequestItem":{
`

This also occurs in other models in the namespace, for example the much duplicated Amount class.

**Comment by AlexandrosMor** [comment]
Hello @RyanONeill1970,
 
The notifications are sending by adyen backend. The library is only deserializing the notification json to object. It is not something that it can be change by the library. 

kind regards,
Alexandros
