### ISSUE TITLE
Merge duplicate models into single model

### ISSUE THREAD

**Issue by RyanONeill1970** [Adyen/adyen-dotnet-api-library#239]
One particular class name (Amount) is used in three different classes in slightly different namespaces.  This causes compilation errors when you have the wrong namespace imported or ambiguity errors when you have both.

The classes do the exact same thing and it would simplify the code and the serialisation tools if these were made common. It would also make the library easier to develop with but would be a breaking change, so maybe one for the next major version?

**Comment by AlexandrosMor** [comment]
Hello @RyanONeill1970,

Nice suggestion, The models are auto generated based on api open specs and that is the reason having duplicate models. I will talk internally with the team and I will let you know.

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @RyanONeill1970,

We can see the value of having a common folder so there is one sahred Amount class. You can always move the Amount classes to one and make a pull request. In the meantime to avoid the ambiguity errors you can refer to the Amount class with the namespace if it is used in the same file.

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @RyanONeill1970,

I created an internal ticket about this issue and we will pick it up as soon as possible. 
For now we can close it from here

kind regards,
Alexandros
