### ISSUE TITLE
Constrained constructors cause runtime errors

### ISSUE THREAD

**Issue by RyanONeill1970** [Adyen/adyen-dotnet-api-library#240]
When getting to grips with the library the following error can (and did) cause issues. Creating an object with an initialiser is valid C# syntax and compiles but does not run.

For example, the following code;

`                var paymentMethodsRequest = new PaymentMethodsRequest
                {
                    MerchantAccount = adyenConfiguration.MerchantAccount,
                };
`

Throws the following error;

> System.IO.InvalidDataException: merchantAccount is a required property for PaymentMethodsRequest and cannot be null

Which is confusing as it leads the developer to think they have passed a null in. After a while of fiddling around I found that it needs a specific constructor call (following) which is not intuitive.

`var paymentMethodsRequest = new PaymentMethodsRequest(merchantAccount: adyenConfiguration.MerchantAccount);`

My preference is to not enforce this validation until the object is used and make the model a simple set of properties. Alternatively you could remove the empty constructor which would stop this code compiling but has a lot of drawbacks for serialisation etc.

**Comment by AlexandrosMor** [comment]
Hello @RyanONeill1970,

We are generating the models based on the open api specs. There are some required fields so those fields are expecting in the constructor.  
```
System.IO.InvalidDataException: merchantAccount is a required property for PaymentMethodsRequest and cannot be null
```
In this case the merchantAccount is required and it should be included in the request.

kind regards,
Alexandros
