### ISSUE TITLE
Request/response logging.

### ISSUE THREAD

**Issue by DsAekb** [Adyen/adyen-dotnet-api-library#241]
Hi,
Is there a plan to add a request/response logging into the library? I can see that it is added in some places e.g. [here](https://github.com/Adyen/adyen-dotnet-api-library/blob/e91bf3a19909a3b6faac8cf80e020d84bf44b72e/Adyen/Service/PosPaymentCloudApi.cs#L54) and [here](https://github.com/Adyen/adyen-dotnet-api-library/blob/499c639353926d3397a492d0a574cda5ec81d25b/Adyen/Service/PosPaymentLocalApi.cs#L61) but most of the API calls are not covered.

**Comment by AlexandrosMor** [comment]
Hello @DsAekb, 

It is not part of our road map to add logging to Adyen's libraries for now. We added at these places for testing but there is not a decision from our side to include logging in every request/response. We will inform you for changes in the future. 

kind regards,
Alexandros
