### ISSUE TITLE
Pay button name change

### ISSUE THREAD

**Issue by microsoftdeveloper999** [Adyen/adyen-dotnet-api-library#245]
How can I change Pay button name ?

**Comment by AlexandrosMor** [comment]
Hello @microsoftdeveloper999,

Could you explain us more which Pay button? The library does not have a UI and maybe you are referring to [web component](https://docs.adyen.com/checkout/components-web/)

Kind regards
Alexandros

**Comment by microsoftdeveloper999** [comment]
I have to change the skin of credit card payment method. In this I need to change Button name from "Pay" to "Checkout" for example.

![image](https://user-images.githubusercontent.com/62878484/77903554-5aed3a00-7283-11ea-9c15-889f65b8bd85.png)

**Comment by AlexandrosMor** [comment]
Hello @microsoftdeveloper999,

Your question is skin related and Adyen's technical support can help you further. The email is  support@adyen.com.

Kind regards,
Alexandros
