### ISSUE TITLE
HttpException when calling PosPaymentLocalApi.TerminalApiLocal

### ISSUE THREAD

**Issue by bojan-kukricar** [Adyen/adyen-dotnet-api-library#257]
Hi,

 I am doing POS integration by using a local communication.

I followed instructions in documentation and did installation of certificate, entered terminal API key in the Adyen's web back office and updated configuration on the terminal(I am working with two terminals e285 and V400m), but when I call PosPaymentLocalApi.TerminalApiLocalTerminalApiLocal it throws HttpException with ResponseBody  "{ "errors": [ "At toplevel, field SaleToPOIRequest: Missing", "At toplevel: Missing" ] }".
I can see from exception that server returns BadRequest response. 
In the closed issues, I found your answer https://github.com/Adyen/adyen-dotnet-api-library/issues/145#issuecomment-523386674 and I did check credentials a few times and also test with different credentials and then I get exception { "errors": [ "At SaleToPOIRequest, field PaymentRequest: Missing", "At SaleToPOIRequest: Missing" ], "warnings": [ "At SaleToPOIRequest.MessageHeader, field SecurityTrailer: Unexpected", "At SaleToPOIRequest.MessageHeader, field NexoBlob: Unexpected" ] } which is like in the issue 145.

It seems it is something related to the encryption/decryption of the message.
I was wondering what is AdyenCryptoVersion property and what is correct value? I set it to 1, because I found that value here in your test code.

**Comment by AlexandrosMor** [comment]
Hello @bojan-kukricar,

From the error message yes it is clear that the issue is with the payment request. Do you also populate the KeyVersion field as part of  encryption credentials ?

kind regards,
Alexandros

**Comment by bojan-kukricar** [comment]
Yes, I set it to 0.

**Comment by AlexandrosMor** [comment]
Hello @bojan-kukricar,

Did you tried with both 1 AdyenCryptoVersion = 1 and KeyVersion = 1 ? Furthermore, the encryption creadentials are unique per terminal and you can retrieve them from adyen customer area.
Please let us know for the result. 
kind regards,
Alexandros

**Comment by bojan-kukricar** [comment]
Hi @AlexandrosMor ,

I tried that now without success. I am getting same error message. 
I know that they are unique and I change keyVersion there to 1 and updated configuration of the terminal before I tried. What do you mean by "retrive them"? Can I retrive encrypted values of them or you just mean I can see and change them?

**Comment by AlexandrosMor** [comment]
Hello @bojan-kukricar,

The encryption/decryption is handled by the library and this functionality is tested. There are small chances that there is an error there. I mean that you can **set** your unique encryption credentials in the Adyen's  customer area: 
Key identifier 
Key passphrase
Key version

and in the library the container which sets the fields is added as follows
```
 var encryptionCredentialDetails = new EncryptionCredentialDetails
           {
               AdyenCryptoVersion = 1,
               KeyIdentifier = "KeyIdentifier",//Key identifier
               Password = "password",//Key passphrase
               KeyVersion = 1 //Key version
           };
```

**Comment by bojan-kukricar** [comment]
Hi @AlexandrosMor ,

It is solved. The issue was because I used SaleToPOIMessage class instead like in your test file SaleToPOIRequest.

Maybe, it will be good to have a documentation specific for this library or if it is possible make SaleToPOIMessage class abstract or maybe change code in SaleToPoiMessageConverter to not write property name like value.GetType().Name. 

Anyway, thank you for your quick response!

Best wishes,
Bojan

**Comment by AlexandrosMor** [comment]
Hello @bojan-kukricar ,

I am glad that you found a solution. I will investigate it to make the naming more clear. Thank you for the suggestions

kind regards,
Alexandros
