### ISSUE TITLE
Web Drop-in: Missing 'SubType' property for PayPal payments

### ISSUE THREAD

**Issue by diffumo** [Adyen/adyen-dotnet-api-library#259]
In order to make a PayPal payment requests an additional field called 'subType' with the value 'sdk' must be send:

 "merchantAccount":"YOUR_MERCHANT_ACCOUNT",
 "shopperReference": "YOUR_UNIQUE_SHOPPER_ID",
 "reference":"YOUR_ORDER_NUMBER",
 "amount":{
   "currency":"EUR",
   "value":1000
  },
 "paymentMethod
":{
   "type":"paypal",
   "subtype": "sdk"
    }

But the class `DefaultPaymentMethodDetails` inside `PaymentRequest` is lacking the property SubType so the request fails.

**Comment by rikterbeek** [comment]
Hi @diffumo,

Thanks for this. We will add this as soon as possible and we are able to make a release on Monday with this included. Fee free to make the modification yourself and provide a Pull Request to us if you want it now.

Regards,
Rik
Adyen

**Comment by AlexandrosMor** [comment]
Hello @diffumo 

We merged the new payment method details models including PayPalDetail.cs. We are going to release it soon. 

Kind regards, 
Alexandros

**Comment by diffumo** [comment]
Ok, thanks!
