### ISSUE TITLE
Make a refund to a card - missing PaymentType in PaymentData

### ISSUE THREAD

**Issue by xslim** [Adyen/adyen-dotnet-api-library#26]
https://docs.adyen.com/developers/point-of-sale-integration/terminal-api-integration/key-steps-nexo/make-a-refund-to-a-card

need to have 

```
"PaymentData" : {
            "PaymentType" : "Refund"
         }
```

**Comment by AlexandrosMor** [comment]
Hello @xslim 
It is added in develop branch,
