### ISSUE TITLE
[PW-2352] Terminal Management API

### ISSUE THREAD

**Issue by ozonni** [Adyen/adyen-dotnet-api-library#260]
Any plans supporting Terminal Management API ?

**Comment by AlexandrosMor** [comment]
Hello @ozonni 

Yes it is in our plans. We created an internal ticket to add the terminal api endpoints. 

kind regards,
Alexandros

**Comment by ozonni** [comment]
@AlexandrosMor we use Terminal Management API for terminal onboarding. For now we will manually send API requests but would be cool to be able to do it via SDK since we already use SDK for other API's

**Comment by AlexandrosMor** [comment]
@ozonni Yes we see the need to add the Terminal Management API in the library. We are going to pick this feature soon. Furthermore, you are always welcome to add the Terminal Management API to the library. You can contribute to the library by following the [Contribution guidelines](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/CONTRIBUTING.md)
regads,
Alexandros

**Comment by AlexandrosMor** [comment]
It is released in 5.4.0
