### ISSUE TITLE
Library limitations inquiry for solution

### ISSUE THREAD

**Issue by MargaritaKalcheva** [Adyen/adyen-dotnet-api-library#267]
Hi Team,

Seems like Adyen lib does not allow underscore symbol "_". C# lib, details attached.

E.g. it was not working with url 'anna_os.zigzag-qa.co.uk', but works fine with 'annaos.zigzag-qa.co.uk'

Is there any workaround on the issue is in undercase char '_' - can we make it acceptable for our integration?

Thanks in advance,
Маргарита

![Adyen_library](https://user-images.githubusercontent.com/65646282/82412151-cb425b80-9a7b-11ea-80fb-c016df64d630.png)

**Comment by AlexandrosMor** [comment]
Hello @MargaritaKalcheva,

Could you send us where in the code do you pass this url ?

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @MargaritaKalcheva,

We would like to hear more about this issue so we can reproduce it and fix it.

regards
Alexandros

**Comment by AlexandrosMor** [comment]
Hello  @MargaritaKalcheva,

We can close the issue because of inactivity, Please open a new one with the necessary information so we can investigate it further, 

kind regards,
Alexandros
