### ISSUE TITLE
CES routine

### ISSUE THREAD

**Issue by RtypeStudios** [Adyen/adyen-dotnet-api-library#282]
**Is your feature request related to a problem? Please describe.**
We are trying to use Xamarin.forms with a custom credit card form layout to capture customers card details. We where hoping to be able to do something like this: https://docs.adyen.com/payment-methods/cards/custom-card-integration?tab=%23android_3 

Where we can collect the field values and encrypt them:

    val rawCardData = Card.Builder()
                          .setNumber(cardNumber)
                          .setExpiryDate(expiryDate.expiryMonth, expiryDate.expiryYear)
                          .setSecurityCode(securityCode)
                          .build()
    val encryptedCard = Encryptor.INSTANCE.encryptFields(rawCardData, "<publicKey>")

**Describe the solution you'd like**
We would like to be able to use CSE encryption in .net natively. 

**Describe alternatives you've considered**
We have tried look at the drop in components but in Xamarin had issues and our design team want to be responsible for all the details of the card layout page.

**Additional context**

I have taken a very rough stab at trying to convert this https://github.com/Adyen/adyen-cse-android/blob/a6342149090bcb92584f5b9d0dbaa70a660a9960/adyencse/src/main/java/adyen/com/adyencse/encrypter/ClientSideEncrypter.java#L31
 (Not sure if it the right code that does the encryption)

But whenever I send values generated by it I'm getting 

{"status":422,"errorCode":"175","message":"Unable to parse JSON data","errorType":"validation"}

I think it might be to do with the base64 encoding, but cant seem to track it down.

    using Org.BouncyCastle.Crypto;
    using Org.BouncyCastle.Crypto.Encodings;
    using Org.BouncyCastle.Crypto.Engines;
    using Org.BouncyCastle.Crypto.Modes;
    using Org.BouncyCastle.Crypto.Parameters;
    using Org.BouncyCastle.Math;
    using System;
    using System.Security.Cryptography;
    using System.Text;

    namespace ConsoleApp2
    {
        public class BcClientSideEncrypter: IClientSideEncrypter
        {
            private static readonly string PREFIX = "adyenan";
            private static readonly string VERSION = "0_1_1";
            private static readonly string SEPARATOR = "$";

            private byte[] pubKey;
            private IAeadBlockCipher aesCipher;
            private IAsymmetricBlockCipher rsaCipher;
            private RNGCryptoServiceProvider srandom;

            public BcClientSideEncrypter(string publicKeyString)
            {
                //srandom = new SecureRandom();
                srandom = new RNGCryptoServiceProvider();

                // String[] keyComponents = publicKeyString.split("\\|");
                var keyComponents = publicKeyString.Split('|');
            
                //RSAPublicKeySpec pubKeySpec = new RSAPublicKeySpec(
                //    new BigInteger(keyComponents[1].toLowerCase(Locale.getDefault()), 16),
                //    new BigInteger(keyComponents[0].toLowerCase(Locale.getDefault()), 16));

                //var pubKeySpec = new RsaPublicKeyStructure(
                //    new BigInteger(keyComponents[1].ToLowerInvariant(), 16),
                //    new BigInteger(keyComponents[0].ToLowerInvariant(), 16));

                var pubKeySpec = new RsaKeyParameters(false,
                    new BigInteger(keyComponents[1].ToLowerInvariant(), 16),
                    new BigInteger(keyComponents[0].ToLowerInvariant(), 16));
            
                // pubKey = keyFactory.generatePublic(pubKeySpec);
                // ?
            
                // aesCipher  = Cipher.getInstance("AES/CCM/NoPadding", "BC");
                aesCipher = new CcmBlockCipher(new AesEngine());

                // rsaCipher = Cipher.getInstance("RSA/None/PKCS1Padding");
                // rsaCipher.init(Cipher.ENCRYPT_MODE, pubKey);

                rsaCipher = new Pkcs1Encoding(new RsaEngine());
                rsaCipher.Init(true, pubKeySpec);

            }

            public string Encrypt(string plainText)
            {
                var textBytes = Encoding.UTF8.GetBytes(plainText);

                // SecretKey aesKey = generateAESKey(256);
                var aesKey = GenerateAESKey(256);

                // byte[] iv = generateIV(12);
               var iv = GenerateIv(12);
            
                // aesCipher.init(Cipher.ENCRYPT_MODE, aesKey, new IvParameterSpec(iv));
                aesCipher.Init(true, new AeadParameters(new KeyParameter(aesKey), 128, iv));

                // byte[] encrypted;
                var encrypted = new byte[aesCipher.GetOutputSize(textBytes.Length)];
            
                var len = aesCipher.ProcessBytes(textBytes, 0, textBytes.Length, encrypted, 0);
                aesCipher.DoFinal(encrypted, len);

                // byte[] result = new byte[iv.length + encrypted.length];
                var result = new byte[iv.Length + encrypted.Length];

                // copy IV to result
                //System.arraycopy(iv, 0, result, 0, iv.length);
                Array.Copy(iv, 0, result, 0, iv.Length);

                // copy encrypted to result
                //System.arraycopy(encrypted, 0, result, iv.length, encrypted.length);
                Array.Copy(encrypted, 0, result, iv.Length, encrypted.Length);
            
                // byte[] encryptedAESKey;
                // encryptedAESKey = rsaCipher.doFinal(aesKey.getEncoded());
                var encryptedAesKey = rsaCipher.ProcessBlock(aesKey, 0, aesKey.Length);

                return $"{PREFIX}{VERSION}{SEPARATOR}{Convert.ToBase64String(encryptedAesKey, Base64FormattingOptions.None)}{SEPARATOR}{Convert.ToBase64String(result, Base64FormattingOptions.None)}";
            }

            private byte[] GenerateAESKey(int keySize)
            {
                var aesProvider = new AesCryptoServiceProvider { KeySize = keySize };
                aesProvider.GenerateKey();
                return aesProvider.Key;
            }

            private byte[] GenerateIv(int ivSize)
            {
                var iv = new byte[ivSize];//generate random IV AES is always 16bytes, but in CCM mode this represents the NONCE
                srandom.GetBytes(iv);
                return iv;
            }

        }
    }
`

If you can help me get it working, happy to submit a PR and help merge it in to the library to share with everyone.

**Comment by RtypeStudios** [comment]
Here is an updated version that better matches the original using the same API calls.

The response now is: {"status":422,"errorCode":"174","message":"Unable to decrypt data","errorType":"validation"} 

    using Org.BouncyCastle.Crypto;
    using Org.BouncyCastle.Crypto.Parameters;
    using Org.BouncyCastle.Math;
    using Org.BouncyCastle.Security;
    using System;
    using System.Security.Cryptography;
    using System.Text;

    namespace ConsoleApp2
    {
        public class BcClientSideEncrypter: IClientSideEncrypter
        {
            private static readonly string PREFIX = "adyenan_";
            private static readonly string VERSION = "0_1_18";
            private static readonly string SEPARATOR = "$";

            //private byte[] pubKey;
            private IBufferedCipher aesCipher;
            private IBufferedCipher rsaCipher;
            private RNGCryptoServiceProvider srandom;

            public BcClientSideEncrypter(string publicKeyString)
            {
                //srandom = new SecureRandom();
                srandom = new RNGCryptoServiceProvider();

                // String[] keyComponents = publicKeyString.split("\\|");
                var keyComponents = publicKeyString.Split('|');
            
                //RSAPublicKeySpec pubKeySpec = new RSAPublicKeySpec(
                //    new BigInteger(keyComponents[1].toLowerCase(Locale.getDefault()), 16),
                //    new BigInteger(keyComponents[0].toLowerCase(Locale.getDefault()), 16));
            
                var pubKeySpec = new RsaKeyParameters(false,
                    new BigInteger(keyComponents[1].ToLowerInvariant(), 16),
                    new BigInteger(keyComponents[0].ToLowerInvariant(), 16));
            
                // pubKey = keyFactory.generatePublic(pubKeySpec);
                // ?
                //RSACryptoServiceProvider keyFactory = new RSACryptoServiceProvider();
                //keyFactory.ImportParameters(pubKeySpec);
                //byte[] pKey = keyFactory.ExportCspBlob(false);
            
                // aesCipher  = Cipher.getInstance("AES/CCM/NoPadding", "BC");
                aesCipher = CipherUtilities.GetCipher("AES/CCM/NoPadding");
            
                // rsaCipher = Cipher.getInstance("RSA/None/PKCS1Padding");
                rsaCipher = CipherUtilities.GetCipher("RSA/None/PKCS1Padding");

                // rsaCipher.init(Cipher.ENCRYPT_MODE, pubKey);
                rsaCipher.Init(true, pubKeySpec);
            }

            public string Encrypt(string plainText)
            {
                // SecretKey aesKey = generateAESKey(256);
                var aesKey = GenerateAESKey(256);

                // byte[] iv = generateIV(12);
                var iv = GenerateIv(12);
            
                // byte[] encrypted;
                byte[] encrypted;

                // aesCipher.init(Cipher.ENCRYPT_MODE, aesKey, new IvParameterSpec(iv));
                aesCipher.Init(true, new ParametersWithIV(new KeyParameter(aesKey), iv));
            
                // getBytes is UTF-8 on Android by default
                // encrypted = aesCipher.doFinal(plainText.getBytes());
                encrypted = aesCipher.DoFinal(Encoding.UTF8.GetBytes(plainText));

                // byte[] result = new byte[iv.length + encrypted.length];
                var result = new byte[iv.Length + encrypted.Length];

                // copy IV to result
                // System.arraycopy(iv, 0, result, 0, iv.length);
                Array.Copy(iv, 0, result, 0, iv.Length);

                // copy encrypted to result
                // System.arraycopy(encrypted, 0, result, iv.length, encrypted.length);
                Array.Copy(encrypted, 0, result, iv.Length, encrypted.Length);
            
                // byte[] encryptedAESKey;
                byte[] encryptedAESKey;
            
                // encryptedAESKey = rsaCipher.doFinal(aesKey.getEncoded());
                encryptedAESKey = rsaCipher.DoFinal(result);
            
                // return String.format("%s%s%s%s%s%s", PREFIX, VERSION, SEPARATOR, Base64.encodeToString(encryptedAESKey, Base64.NO_WRAP), SEPARATOR, Base64.encodeToString(result, Base64.NO_WRAP));
            return $"{PREFIX}{VERSION}{SEPARATOR}{Convert.ToBase64String(encryptedAESKey, Base64FormattingOptions.None)}{SEPARATOR}{Convert.ToBase64String(encryptedAESKey, Base64FormattingOptions.None)}";
            }

            private byte[] GenerateAESKey(int keySize)
            {
                // KeyGenerator kgen = null;
                // kgen = KeyGenerator.getInstance("AES");
                // kgen.init(keySize);
                // return kgen.generateKey();
            
                var aesProvider = new AesCryptoServiceProvider { KeySize = keySize };
                aesProvider.GenerateKey();
                return aesProvider.Key;
            }

            private byte[] GenerateIv(int ivSize)
            {
                // byte[] iv = new byte[ivSize];//generate random IV AES is always 16bytes, but in CCM mode this represents the NONCE
                // srandom.nextBytes(iv);
                // return iv;

                var iv = new byte[ivSize];
                srandom.GetBytes(iv);
                return iv;
            }
        }
    }

**Comment by AlexandrosMor** [comment]
Hello @RtypeStudios, 

Thank you for your suggestion. We will raise the suggestion internally to discuss with the team about this feature. I will let you know as soon as possible. 

kind regards,

**Comment by RtypeStudios** [comment]
The below seems to work, the part that was catching me out was the JSON error. I thought the encrypted elements were just plain text. But actually they need to be JSON structures like:

{ "generationtime": "2020-06-22T09:55:56Z", "number": "4400000000000008" }

I thought the error was regarding my overall submission not the JSON inside the encrypted parts. 

I've manage to make a few card submissions with the below. But would be great to get an official thumbs up and double check of the work. As crypto can be tricky and easy to get wrong.

    using Org.BouncyCastle.Crypto;
    using Org.BouncyCastle.Crypto.Parameters;
    using Org.BouncyCastle.Math;
    using Org.BouncyCastle.Security;
    using System;
    using System.Security.Cryptography;
    using System.Text;

    namespace ConsoleApp2
    {
        /// <summary>
        /// .Net implementation of the Ayden encryption routine.
        /// </summary>
        /// <remarks>
        /// Ported from here: https://github.com/Adyen/adyen-cse-android/blob/a6342149090bcb92584f5b9d0dbaa70a660a9960/adyencse/src/main/java/adyen/com/adyencse/encrypter/ClientSideEncrypter.java
        /// </remarks>
        public class BcClientSideEncrypter4: IClientSideEncrypter
        {
            private const string Prefix = "adyenjs";
            private const string Version = "_0_1_18";
            private const string Separator = "$";

            private readonly IBufferedCipher _aesCipher;
            private readonly IBufferedCipher _rsaCipher;
            private readonly RNGCryptoServiceProvider _secureRandom = new RNGCryptoServiceProvider();

            /// <summary>
            /// Create a new instance of <see cref="BcClientSideEncrypter4"/>.
            /// </summary>
            /// <param name="publicKeyString">The client side encryption key from your Adyen user account.</param>
            public BcClientSideEncrypter4(string publicKeyString)
            {
                // Split the public key into two pieces.
                var keyComponents = publicKeyString.Split('|');
            
                // create public key.
                var pubKey = new RsaKeyParameters(false, 
                    new BigInteger(keyComponents[1].ToLowerInvariant(), 16), 
                    new BigInteger(keyComponents[0].ToLowerInvariant(), 16));
            
                // Set up AES CCM Cipher.
                _aesCipher = CipherUtilities.GetCipher("AES/CCM/NoPadding");
            
                // Set up RSA PKCS1 Encoding Cipher.
                _rsaCipher = CipherUtilities.GetCipher("RSA/None/PKCS1Padding");

                // init the cipher with the public key.
                _rsaCipher.Init(true, pubKey);
            }

            /// <summary>
            /// Encrypt the value.
            /// </summary>
            /// <param name="plainText">The text to encrypt.</param>
            /// <returns>Text encrypted using the Adyen client side public key</returns>
            public string Encrypt(string plainText)
            {
                // Generate a random key.
                var aesKey = GenerateAesKey(256);

                // Set up Initialization vector.
                var iv = GenerateIv(12);
            
                // Init Cipher with secret key and IV
                _aesCipher.Init(true, new ParametersWithIV(new KeyParameter(aesKey), iv));
            
                // First layer of encryption using AES key and IV.
                var encrypted = _aesCipher.DoFinal(Encoding.UTF8.GetBytes(plainText));
            
                // Merge IV and aes encrypted value into a byte array.
                var result = new byte[iv.Length + encrypted.Length];

                // Copy IV to result
                Array.Copy(iv, 0, result, 0, iv.Length);

                // Copy encrypted to result
                Array.Copy(encrypted, 0, result, iv.Length, encrypted.Length);
            
                // Encrypt with public key.
                var encryptedAesKey = _rsaCipher.DoFinal(aesKey);
            
                // Merge and return result.
                return $"{Prefix}{Version}{Separator}{Convert.ToBase64String(encryptedAesKey)}{Separator}{Convert.ToBase64String(result)}";
            }

            /// <summary>
            /// Generate a AES key.
            /// </summary>
            /// <param name="keySize">The key size.</param>
            /// <returns>Returns a key for use with AES.</returns>
            private static byte[] GenerateAesKey(int keySize)
            {
                var aesProvider = new AesCryptoServiceProvider { KeySize = keySize };
                aesProvider.GenerateKey();
                return aesProvider.Key;
            }

            /// <summary>
            /// Generate a random IV.
            /// </summary>
            /// <param name="ivSize">The size of the IV in bytes.</param>
            /// <returns>Returns a IV for us in AES signing.</returns>
            private byte[] GenerateIv(int ivSize)
            {
                var iv = new byte[ivSize];
               _secureRandom.GetBytes(iv);
                return iv;
            }
        }
    }

**Comment by RtypeStudios** [comment]
Will also try and get it to work with the native .net libraries so you don't need to depend on Bouncy Castle package.

**Comment by AlexandrosMor** [comment]
Hello @RtypeStudios,

As it is mentioned in the Adyen's [documentation](https://docs.adyen.com/classic-integration/cse-integration-ecommerce#page-introduction) about CSE, this type of integration has been replaced by [Card encryption solutions](https://docs.adyen.com/payment-methods/cards) used with Checkout APIs. CSE is no longer available for new integrations.
This is the reason that the library does not include the CSE encryption natively. 

kind regards,
Alexandros

**Comment by RtypeStudios** [comment]
Hi AlexandrosMor ,

I'm a bit confused, how does the card solution stuff differ? It appears to still use CSE under the bonnet?
