### ISSUE TITLE
MessagePayloadSerializer can't deserialize PrintResponse because PrintResponse does not inherit IMessagePayload

### ISSUE THREAD

**Issue by bojan-kukricar** [Adyen/adyen-dotnet-api-library#284]
**Exception message**
GenericArguments[0], 'Adyen.Model.Nexo.PrintResponse', on 'Adyen.CloudApiSerialization.MessagePayloadSerializer`1[T]' violates the constraint of type 'T'.

**Comment by AlexandrosMor** [comment]
hello @bojan-kukricar,

This error is caused because the Adyen.Model.Nexo.PrintResponse is not implement the IMessagePayload. Can you try this solution? 
```
public partial class PrintResponse : IMessagePayload
```
regards
Alexandros

**Comment by bojan-kukricar** [comment]
Hi @AlexandrosMor ,

That should work. I will try that.

Thanks,
Bojan

**Comment by AlexandrosMor** [comment]
Hello @bojan-kukricar ,

If you can confirm that fix the parsing issue I can include it to our next release. If I understand correct you add the library as dll or from nuget. 

regards,
Alexandros

**Comment by bojan-kukricar** [comment]
Hi @AlexandrosMor ,

Yes, that will fix the issue. I did the same like you in #287  and it works. The library is added from nuget in my solution(only to test this fix I used a locally compiled dll).

regards,
Bojan

**Comment by AlexandrosMor** [comment]
Ok Great we are going to merge it as soon as possible
