### ISSUE TITLE
[PW-2616] SaleToPoiMessageSecuredEncryptor.Encrypt uses ASCII encoding instead of UTF-8

### ISSUE THREAD

**Issue by bojan-kukricar** [Adyen/adyen-dotnet-api-library#288]
**Description**
During encryption a message is ASCII encoded which results in an issue for example during printing.
Characters which do not exist in ASCII table, will not be correctly interpreted.

      public SaleToPoiMessageSecured Encrypt(string saleToPoiMessage, MessageHeader messageHeader,
                                                 EncryptionCredentialDetails encryptionCredentialDetails)
        {
            var encryptionDerivedKey = _encryptionDerivedKeyGenerator.Generate(encryptionCredentialDetails);
            var saleToPoiMessageJson = saleToPoiMessage;
            var saleToPoiMessageByteArray = Encoding.ASCII.GetBytes(saleToPoiMessageJson);
            var ivMod = _ivModGenerator.GenerateRandomMod();
            var saleToPoiMessageAesEncrypted = _aesEncryptor.Encrypt(saleToPoiMessageByteArray,
                                                                     encryptionDerivedKey,
                                                                     ivMod);
            var saleToPoiMessageAesEncryptedHmac = _hmacSha256Wrapper.HMac(saleToPoiMessageByteArray,
                                                                           encryptionDerivedKey.HmacKey);

            var saleToPoiMessageSecured = new SaleToPoiRequestSecured
            {
                MessageHeader = messageHeader,
                NexoBlob = Convert.ToBase64String(saleToPoiMessageAesEncrypted),
                SecurityTrailer = new SecurityTrailer
                {
                    KeyVersion = encryptionCredentialDetails.KeyVersion,
                    KeyIdentifier = encryptionCredentialDetails.KeyIdentifier,
                    Hmac = saleToPoiMessageAesEncryptedHmac,
                    Nonce = ivMod,
                    AdyenCryptoVersion = encryptionCredentialDetails.AdyenCryptoVersion
                }
            };
            
            return saleToPoiMessageSecured;
        }

**To Reproduce**
1. Create a print request with OpenText.Text="m\u006DÄ\u00C4"
2. Execute
3. Terminal will print "mm??"

**Comment by AlexandrosMor** [comment]
hello @bojan-kukricar,

We are going to create an internal ticket and investigate this issue.

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @bojan-kukricar,

Could you send us a PrintRequest sample so we can test it on our end? 

regards,
Alexandros

**Comment by bojan-kukricar** [comment]
Hi @AlexandrosMor, 

I will see to send you later today.

Regards, 
Bojan

**Comment by bojan-kukricar** [comment]
Hi @AlexandrosMor ,

I don't have a pure code which directly use this library because I needed an additional abstraction in my code but I took some parts which can help you to construct a PrintRequest to test this issue. For OutputText.Text (I see typo " OpenText.Text" in my initial comment) value you can use the same like I provided in the initial comment or something else which contains Unicode characters. 

```
   				
	private SaleToPOIRequest BuildSaleToPOIRequest(Requests.PrintRequest printRequest)
        {
            return new SaleToPOIRequest
            {
                MessageHeader = BuildPrintMessageHeader(printRequest),
                MessagePayload = BuildPrintMessagePayload(printRequest),
            };
        }
		
        private MessageHeader BuildPrintMessageHeader(Requests.PrintRequest printRequest)
        {
            return new MessageHeader()
            {
                MessageClass = MessageClassType.Device,
                MessageCategory = MessageCategoryType.Print,
                MessageType = MessageType.Request,
                SaleID = printRequest.PosId,
                POIID = printRequest.TerminalId,
                ServiceID = printRequest.Id,
            };
        }
		
	private object BuildPrintMessagePayload(Requests.PrintRequest printRequest)
        {
            var request = new ad.Model.Nexo.PrintRequest
            {
                PrintOutput = new PrintOutput
                {
                    DocumentQualifier = DocumentQualifierType.Document,
                    ResponseMode = ResponseModeType.PrintEnd,
                   OutputContent = new OutputContent
                {
                    OutputFormat = OutputFormatType.Text,
                    OutputText = new OutputText[]{ new OutputText{ Text = string.Empty }},
                },
                },
            };

          
            return request;
        }      
```

Best regards,
Bojan

**Comment by AlexandrosMor** [comment]
Hello @bojan-kukricar,

The issue is that you are passing in the string `OpenText.Text = "m\u006DÄ\u00C4"` but you do not unescape the string. In order to unescape the string the syntax is `OpenText.Text = @"m\u006DÄ\u00C4"`. I tested it in  our environment and indeed with `OpenText.Text = "m\u006DÄ\u00C4"` the result is `"mm??"`
and with `OpenText.Text = @"m\u006DÄ\u00C4"`  the result after the decryption is the same. 

kind regards,
Alexandros 
Adyen
