### ISSUE TITLE
Regional endpoints

### ISSUE THREAD

**Issue by Xenoage** [Adyen/adyen-dotnet-api-library#289]
The [Terminal API fundamentals](https://docs.adyen.com/point-of-sale/terminal-api-fundamentals) lists regional endpoints for the live API:

> When you're ready to go live, you need to switch to a live transaction endpoint that's geographically closest to the location of your store.

Unfortunately, this library seems to always use `CloudApiEndPointLive = "https://terminal-api-live.adyen.com"` (see [ClientConfig.cs](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Constants/ClientConfig.cs)). It would be great to have something like `enum Region`, asked for when creating the [Client](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Client.cs).

**Comment by AlexandrosMor** [comment]
Hello @Xenoage,

Can you give us an example ? 

kind regards 
Alexandros

**Comment by Xenoage** [comment]
```
// see https://docs.adyen.com/point-of-sale/terminal-api-fundamentals#endpoints-and-authentication
public enum Region {
  Europe,
  Australia,
  US
}

// in ClientConfig.cs:
public IDictionary<Region, string> CloudApiEndPointLive = new Dictionary<Region, string> {
  { Region.Europe, "https://terminal-api-live.adyen.com" }, 
  { Region.Australia, "https://terminal-api-live-au.adyen.com" }, 
  { Region.US, "https://terminal-api-live-us.adyen.com" }
}; 

// in Client.cs: (+ constructor)
public void SetEnvironment(Environment environment, string liveEndpointUrlPrefix, Region region = Region.Europe)
  // ...
  case Environment.Live:
    // ...
    Config.CloudApiEndPoint = ClientConfig.CloudApiEndPointLive[region]
```

**Comment by AlexandrosMor** [comment]
Hello @Xenoage.

Thank you for the suggestion. At the moment non of these endpoints are developed and it is not in the planning. For that reason we will not making any changes in our libraries or plugins regarding the endpoints. 

regards,
Alexandros
