### ISSUE TITLE
[PW-2742] Update payment link status

### ISSUE THREAD

**Issue by ozonni** [Adyen/adyen-dotnet-api-library#296]
https://docs.adyen.com/checkout/pay-by-link#update-payment-link-status

```

  | curl  https://checkout-test.adyen.com/v52/paymentLinks/PLFA45DD35E1E75EBE \
-- | --
  | -H "x-API-key: YOUR_API_KEY" \
  | -H "content-type: application/json" \
  | -X PATCH \
  | -d '{
  | "status": "expired"
  | }'


```

It's not possible to update payment link status as well as get payment link details

**Comment by AlexandrosMor** [comment]
Hello @ozonni ,

Can you tell us more information about the flow that you tried ? 

regards 
Alexaxandros

**Comment by ozonni** [comment]
@AlexandrosMor i've created payment link using [CreatePaymentLinkRequest](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/CreatePaymentLinkRequest.cs) and now i would like to cancel it. Adyen documentation says i need to send `PATCH` request and set `status=expired`. I didn't find a request in SDK that i can use.

**Comment by ozonni** [comment]
@AlexandrosMor this is from Adyen documentation

https://docs.adyen.com/checkout/pay-by-link#update-payment-link-status

```
In some scenarios, you might want to force the expiry of a payment link. For example, if a shopper updates their order after you've sent them a payment link, you might want to create a new payment link with the updated amount.
```

That's exactly my case.

**Comment by ozonni** [comment]
@AlexandrosMor i'm not sure if this is a right channel, but when you send create payment link request, you get back such response
```json
{
    "amount": {
        "currency": "EUR",
        "value": 4200
    },
    "expiresAt": "2020-06-23T12:25:28Z",
    "reference": "YOUR_ORDER_NUMBER",
    "url": "https://checkoutshopper-test.adyen.com/checkoutshopper/payByLink.shtml?d=PLFA45PD35E1E75KBE"
}
```

As you can see there is no `id` field in there. But all API's related to payment link management require payment link id (e.g. update payment link status). The only way i can do it is to parse the `url` and get id after `/payByLink.shtml?d=` part. Which i would say is really bad way to do it. One day Adyen will change url and the whole parsing will be broken.

I think it's super easy for Adyen to add `id` in response model, so i don't need to parse anything.

**Comment by AlexandrosMor** [comment]
No you can send the status. We are going to implement it in later releases including v53.

**Comment by ozonni** [comment]
@AlexandrosMor `No you can send the status`. What do you mean i can send the status? How?

**Comment by AlexandrosMor** [comment]
The status field is not in the [request class](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/CreatePaymentLinkRequest.cs). Updating the library to support api v53 the status field will be included

**Comment by ozonni** [comment]
@AlexandrosMor thank you. But i would say it shouldn't be part of the [CreatePaymentLinkRequest](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/CreatePaymentLinkRequest.cs). Because i'm not creating new payment link, i want to modify existing one. So i suppose it should be another type of request e.g. `ModifyPaymentLinkRequest` or more explicit one `CancelPaymentLinkRequest`.

**Comment by AlexandrosMor** [comment]
The library is aligned with Adyen api so the models are build based on open api specs. We are not planning to add additional requests

**Comment by AlexandrosMor** [comment]
I believe I answered  your question therefore I will close the issued, If you have more questions please let us know.
regards, 
Alexandros

**Comment by markhoebeke** [comment]
> We are going to create an internal ticket for adding [PATCH](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v53/patch/paymentLinks/%7BlinkId%7D) and [GET](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v53/get/paymentLinks/%7BlinkId%7D) for paybylink and pick it up as soon as possible.

Is it correct that the GET request is not yet implemented or am I looking in the wrong direction?

**Comment by AlexandrosMor** [comment]
Hello @markhoebeke, 

Indeed the GET request is not yet implemented. It is in our plans to update all the libraries. 

kind regards,
Alexandros
Adyen

**Comment by dietermijle** [comment]
+1 for the PATCH

**Comment by Lacutas82** [comment]
Can I check to see if this has been implemented in v9.0.0?  I can see that there is an UpdatePaymentLinkRequest class in the Model, but can't see that this is consumed anywhere.  Digging through the service calls I also can't see that a PATCH HTTP method is implemented anywhere.
We do need a way to cancel the links in case a customer cancels their order.

**Comment by jillingk** [comment]
Hi @Lacutas82,

Thanks for reaching out to us. As of yet we have still not implemented the Patch method in this library unfortunately. However, this will change very soon as automating and refactoring this library is next on our planning.

Best, Jilling
Adyen

**Comment by Dxsoo96** [comment]
Hi , can i check that is this function implemented?

**Comment by jillingk** [comment]
Hi @Dxsoo96,

Thanks for reaching out to us. We have implemented the update/delete paymentlinks (besides many other features/fixes/improvements), however have yet to release most of it. We're trying to do this very soon though, so stay posted!

Best, Jilling
Adyen
