### ISSUE TITLE
The ShopperInteraction field is marked as optional when making a payment but appears to be mandatory

### ISSUE THREAD

**Issue by EdwardNickson** [Adyen/adyen-dotnet-api-library#297]
When making a payment using the C# SDK the documentation states that ShopperInteraction is not a mandatory field on the PaymentRequest object. In reality I always get 442 HTTP error unless I specify the ShopperInteraction.

1. Go to Step 3: Make a payment at https://docs.adyen.com/checkout/api-only?tab=codeBlocktiXdF_6#step-3-make-a-payment
2. Copy the code for the C# implementation and fill in with your account details
3. Run it and the SDK throws an HttpClientException

**Expected behavior**
It creates a payment without throwing an error

**Actual behaviour**
The SDK throws an HttpClientException exception and the ResponseBody is
 {"status":422,"errorCode":"000","message":"Invalid shopper interaction","errorType":"validation","pspReference":"................"}

**Comment by AlexandrosMor** [comment]
Hello @EdwardNickson, 

I would like to thank you for noticing this issue. We are going to investigate it and let you know.

Kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @EdwardNickson,

The default shopper interaction is set next to your merchant account in the back office. Furthermore as you can see in the [api explorer](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v53/post/payments) you can send a test request without shopper interaction. 

You can confirm your merchant account settings with the tech support.

kind regards,
Alexandros
