### ISSUE TITLE
[PW-2421] Can you strong name the Adyen Nuget Package?

### ISSUE THREAD

**Issue by EdwardNickson** [Adyen/adyen-dotnet-api-library#298]
Hi,

My company uses strong named dlls for all of our C# projects. As such we can only use 3rd party nuget packages "out of the box" if they are also strong named. The Adyen nuget package is not strong named and therefore we have to do some additional steps to work around that.

Because it is not strong named we either have to
1. Compile from source and sign it during compilation (what we are doing now) or,
2. Disassemble your dll to IL and then rebuild and sign it (see https://stackoverflow.com/questions/331520/how-to-fix-referenced-assembly-does-not-have-a-strong-name-error)

Neither of these is ideal and both make it hard to upgarde to newer versions of your SDK. Both could be solved by Adyen strong naming their assemblies

**Describe the solution you'd like**
I would like for Adyen to strong name their assemblies.

**Comment by AlexandrosMor** [comment]
Hello @EdwardNickson,
 
Thank you for the suggestion. We have an internal ticket to strong name the dot net library.

kind regards, 
Alexandros
