### ISSUE TITLE
Documentation for refund flow

### ISSUE THREAD

**Issue by EdwardNickson** [Adyen/adyen-dotnet-api-library#299]
It looks like there is no documentation about doing a refund (or more generally, a modification) request using the dotnet SDK.
You can figure it out by looking at the source but it would be great if the API docs had this in there, similar to how they have the payment examples (see https://docs.adyen.com/checkout/api-only?tab=codeBlockTtpmB_6)

**Comment by AlexandrosMor** [comment]
Hello @EdwardNickson,

Thank you for the suggestion. We are going to create an internal ticket and update the documentation if it is needed,

Kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hey @EdwardNickson,

Were you able to make the refund request with the library? This part in the [documentation](https://docs.adyen.com/api-explorer/#/Payment/v64/post/refund) might help you

regrards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hey @EdwardNickson,

Our documentation team is going to investigate the possibility to add libraries code examples for refunds too. For the moment you can read the [page about refunds ](https://docs.adyen.com/checkout/refund). 

kind regards, 
Alexandros
