### ISSUE TITLE
BrowserInfo validations do not match real scenario

### ISSUE THREAD

**Issue by rooque** [Adyen/adyen-dotnet-api-library#305]
**Describe the bug**
The validation made in this class does not match the object generated in a real scenario.

[Validations](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/BrowserInfo.cs#L284)

Object generated by the drop in component:

```json 
"browserInfo": {
    "acceptHeader": "*/*",
    "colorDepth": 30,
    "javaEnabled": false,
    "language": "pt-BR",
    "screenHeight": 900,
    "screenWidth": 1440,
    "timeZoneOffset": 180,
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36"
  }
```

**Comment by AlexandrosMor** [comment]
Hello @rooque,

Thank you for raising this issue. Indeed the validation is not correct for useragent field. If you need the fix urgently you can open a pull request with the fix and we will review it as soon as possible. 

kind regards,
Alexandros

**Comment by rooque** [comment]
> Hello @rooque,
> 
> Thank you for raising this issue. Indeed the validation is not correct for useragent field. If you need the fix urgently you can open a pull request with the fix and we will review it as soon as possible.
> 
> kind regards,
> Alexandros

Sure, I can open a PR. 

What would be the correct validation for acceptHeader and userAgent?
