### ISSUE TITLE
Solution cannot be compiled for net462, net472, ...

### ISSUE THREAD

**Issue by T-K-E** [Adyen/adyen-dotnet-api-library#307]
Hi,

currently this solution cannot be compiled for DotNet-Framework. It is prepared only for netstandard2.0
If you change in File HttpURLConnectionClient.cs Row 196 from HttpUtility.UrlEncode to Uri.EscapeUriString you can achieve this.

best regards

**Comment by AlexandrosMor** [comment]
Hello @T-K-E,

Thank you for contacting Adyen, Based on this [matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support) the netstandard2.0 supports .net framework 4.6.1. Which version is not working for you ?

kind regards,
Alexandros

**Comment by T-K-E** [comment]
Hello Alexandros,

you cannot compile the sources to net462 etc…
if you change in Adyen.csproj
<TargetFrameworks>netstandard2.0</TargetFrameworks>
To
<TargetFrameworks>netstandard2.0;net462</TargetFrameworks>
You will get compilation errors cause of the mentioned source code row

If I use the netstandard2.0 binary I have to transfer a lot of dependent DLLs. The net462-binaries does not have this dependencies cause of the installed .Net-Framework.

Kind regards
Thomas

Von: Alexandros Moraitis [mailto:notifications@github.com]
Gesendet: Donnerstag, 13. August 2020 07:54
An: Adyen/adyen-dotnet-api-library <adyen-dotnet-api-library@noreply.github.com>
Cc: Kaube, Thomas <T.Kaube@actosoft.de>; Mention <mention@noreply.github.com>
Betreff: Re: [Adyen/adyen-dotnet-api-library] Solution cannot be compiled for net462, net472, ... (#307)


Hello @T-K-E<https://github.com/T-K-E>,

Thank you for contacting Adyen, Based on this matrix<https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support> the netstandard2.0 supports .net framework 4.6.1. Which version is not working for you ?

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @T-K-E,

I created an empty console application with .net framework 4.6.2 and I added the Adyen dotnet library using nuget. It can compile without any issues. I think maybe the problem is that you are changing the project file. Could you try to add the library using nuget too? 

regards,
Alexandros

**Comment by T-K-E** [comment]
Hello Alexandros,

I was also able to compile but not able to run. A TypeLoadException occurred.

Can you send me your solution?

Kind regards,
Thomas

Von: Alexandros Moraitis [mailto:notifications@github.com]
Gesendet: Freitag, 14. August 2020 11:42
An: Adyen/adyen-dotnet-api-library <adyen-dotnet-api-library@noreply.github.com>
Cc: Kaube, Thomas <T.Kaube@actosoft.de>; Mention <mention@noreply.github.com>
Betreff: Re: [Adyen/adyen-dotnet-api-library] Solution cannot be compiled for net462, net472, ... (#307)


Hello @T-K-E<https://github.com/T-K-E>,

I created an empty console application with .net framework 4.6.2 and I added the Adyen dotnet library using nuget. It can compile without any issues. I think maybe the problem is that you are changing the project file. Could you try to add the library using nuget too?

regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @T-K-E,

Please try to create a new console app with 4.6.2, install the Adyen library from nuget and make a basic call like payments methods. It will take 3-4 lines. Check the example [in docs](https://docs.adyen.com/checkout/api-only#1795049973)
This way you can verify that the library compiles without issues.
Can you send us more details for the TypeLoadException and how to reproduce it? Are more projects included to the project that consumes the library ? 

Thank you in advance,
Alexandros

**Comment by T-K-E** [comment]
Hello Alexandros,

you have discussed this problem with my colleagues Lutz Windmann and Dominik Wischnewski from actosoft on 31st August via MS Teams and Desktop Sharing. In this session our problem with the TypeLoadException could not be solved. So my colleagues asked me to have a look at that.
I used the sources and tried to solve the problem. I found out if you change the sources as mentioned in the issue the TypeLoadException is gone.

Kind regards
Thomas



Von: Alexandros Moraitis [mailto:notifications@github.com]
Gesendet: Montag, 17. August 2020 15:11
An: Adyen/adyen-dotnet-api-library <adyen-dotnet-api-library@noreply.github.com>
Cc: Kaube, Thomas <T.Kaube@actosoft.de>; Mention <mention@noreply.github.com>
Betreff: Re: [Adyen/adyen-dotnet-api-library] Solution cannot be compiled for net462, net472, ... (#307)


Hello @T-K-E<https://github.com/T-K-E>,

Please try to create a new console app with 4.6.2, install the Adyen library from nuget and make a basic call like payments methods. It will take 3-4 lines. Check the example in docs<https://docs.adyen.com/checkout/api-only#1795049973>
This way you can verify that the library compiles without issues.
Can you send us more details for the TypeLoadException and how to reproduce it? Are more projects included to the project that consumes the library ?

Thank you in advance,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @T-K-E,

If I understand correct is the issue solved When you are referring to the sources do you mean adding the net462 in the TargetFrameworks of project file like following  ? 

`<TargetFrameworks>netstandard2.0;net462</TargetFrameworks>
` 
kind regards,
Alexandros

**Comment by T-K-E** [comment]
Hello Alexandros,

nearly …
cause of net462 one row of code is not able to compile to this framework. I’ve added a possible correction to the issue. So it will compile for both targets.

Kind regards
Thomas

Von: Alexandros Moraitis [mailto:notifications@github.com]
Gesendet: Dienstag, 18. August 2020 18:23
An: Adyen/adyen-dotnet-api-library <adyen-dotnet-api-library@noreply.github.com>
Cc: Kaube, Thomas <T.Kaube@actosoft.de>; Mention <mention@noreply.github.com>
Betreff: Re: [Adyen/adyen-dotnet-api-library] Solution cannot be compiled for net462, net472, ... (#307)


Hello @T-K-E<https://github.com/T-K-E>,

If I understand correct is the issue solved for you? When you are referring to the sources do you mean adding the net462 in the TargetFrameworks of project file like following ?

<TargetFrameworks>netstandard2.0;net462</TargetFrameworks>
kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @T-K-E 
Yes we discussed with your colleagues for an issue related to System.ComponentModel.Annotations. The project file should not changed in order to compile properly. 
Feel free to contact Adyen if you have any questions.

kind regards,
Alexandros

**Comment by T-K-E** [comment]
Hello Alexandros,

I’m irritated: You are able to provide a sample implementation but were not able to solve our problem with the current adyen.dll. I found a solution by adding options to your project file which still compiles properly and you simply reject this.

In which circumstances changes will be made?

Kind regards,
Thomas

Von: Alexandros Moraitis [mailto:notifications@github.com]
Gesendet: Dienstag, 18. August 2020 19:04
An: Adyen/adyen-dotnet-api-library <adyen-dotnet-api-library@noreply.github.com>
Cc: Kaube, Thomas <T.Kaube@actosoft.de>; Mention <mention@noreply.github.com>
Betreff: Re: [Adyen/adyen-dotnet-api-library] Solution cannot be compiled for net462, net472, ... (#307)


Hello @T-K-E<https://github.com/T-K-E>
Yes we discussed with your colleagues for an issue related to System.ComponentModel.Annotations. The project file should not changed in order to compile properly.
Feel free to contact Adyen if you have any questions.

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @T-K-E 
Changes are made if it benefits all the merchants,
The solution is generic and not specific implemented for 4.6.2 .net framework so that is the reason that we chose .net standard 2.0 which supports multiple frameworks. Furthermore, I was not able to reproduce the issue with TypeLoadException as you did not provide information about your dev environment so I cannot be certain that adding net462 in the TargetFrameworks is the correct approach or modifying the HttpURLConnectionClient class. The library is open source and every merchant can modify the library based on each needs. Finally, If you want to add a feature or fix a bug you are always more than welcome to open a pull request. :)

**Comment by nitinanand27** [comment]
Almost similar issue. Adyen library doesnt install in my .net framework project.
i get the following error
![image](https://user-images.githubusercontent.com/15047308/224511026-1204aee9-e74e-49a8-a864-934fb6bdb059.png)

**Comment by jillingk** [comment]
Hey @nitinanand27,

Thanks for reaching out to us. I'm checking the dependencies in our library, but I'm actually unable to find the dependencies that are throwing the error. Are you sure this error is coming from our library, and not the old deprecated ecom library? 

Also what .NET framework are you using?

Ps we just release a new version of the library, v10.0.0-beta, feel free to check it out :)

Best, Jilling
Adyen
