### ISSUE TITLE
Add parameter-less constructors to all models

### ISSUE THREAD

**Issue by JohannSig** [Adyen/adyen-dotnet-api-library#314]
**Describe the bug**

Could you please add parameter-less constructors to all models in the Adyen SDK?

We save Adyen notification in JSON format in one project and restore them using System.Text.Json's JsonSerializer. 
Unfortunately System.Text.Json cannot deserialize JSON into objects that only have constructors with parameters:
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#scenarios-using-jsonserializer-that-require-workarounds

Since System.Text.Json comes bundled with all contemporary .NET projects (Newtonsoft JSON doesn't), not having these parameter-less constructors breaks serialization compatibility. And adding them is easy, clean work compared to us writing custom converters or bloating projects with Newtonsoft JSON.

Frankly, if you give the go ahead, I'd be happy to do the necessary changes in a pull request.

**To Reproduce**
Deserialize an Adyen.Model.Amount using the System.Text.Json.JsonSerializer.Deserialize method.

**Expected behavior**
Ideally, a correctly populated instance of Adyen.Model.Amount, not an exception thrown.

**Screenshots**
I'll add screenshots if needed, but this seems pretty straight-forward to me.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by AlexandrosMor** [comment]
Hello @JohannSig,

The models are autogenerated using the open api specs. Some parameters are required and to force the usage of them.
We are not using System.Text.Json and if I understand you are using the models of the library and not all the library functionality. In this case I would recommend to create your own models based on [adyen open api specs](https://github.com/Adyen/adyen-openapi/tree/master/json) or you can use the library as it is currenlty. 
There is no plan for now to switch from Newtonsoft JSON to System.Text.Json. 
Please let me know if the answer helped you. 

Kind regards,
Alexandros

**Comment by JohannSig** [comment]
Thanks for your reply Alexandros. I've just found out that .NET 5 will fix
this in Systrm.Text.Json, so this is a non-issue really. Sorry for the
bother.

**Comment by JohannSig** [comment]
The System.text.json will be fixed in .NET 5
