### ISSUE TITLE
DefaultPaymentMethodDetails does not support new version of apple pay

### ISSUE THREAD

**Issue by Melchy** [Adyen/adyen-dotnet-api-library#330]
**Describe the bug**
Adyen api changed /payments enpoint in version 49 for Apple pay. Property additionalData.applepay.token was renamed to applepay.token. 

Object [DefaultPaymentMethodDetails](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/DefaultPaymentMethodDetails.cs) is incompatible with this change. It still uses old name for ApplePayToken.

**Expected behavior**
Class DefaultPaymentMethodDetails should contain property ApplePayToken with attribute `[DataMember(EmitDefaultValue = false, Name = "applepay.token")]`

Is this behavior intentional? Are there any plans to rename this property? (Adyen apple pay SDK is currently incompatible with this object.)

**Comment by AlexandrosMor** [comment]
Hello @Melchy 

We are currently working to support Adyen api version v64. This fix will be included too. We hope that we will be able to pick it up next sprint

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @Melchy,

This is fixed from this pr #338. It will be added with the next release 

 kind regards,
Alexandros
