### ISSUE TITLE
SubType property missing in DefaultPaymentMethodDetails.cs

### ISSUE THREAD

**Issue by NemanjaMilenkovic990** [Adyen/adyen-dotnet-api-library#332]
**Describe the bug**
In DefaultPaymentMethodDetails.cs class SubType property is missing and without it pay pal smart payment will not work

**Screenshots**
![image](https://user-images.githubusercontent.com/52150883/95841305-7dd5cc00-0d45-11eb-8552-9aa51b068cc3.png)

**Comment by msilvagarcia** [comment]
Hey @NemanjaMilenkovic990 ! Thanks for raising this issue with us. Would you be able to add some unit tests and open a pull request to the repository? Otherwise, we can take action later.

Kind regards,
Marcos
Adyen

**Comment by NemanjaMilenkovic990** [comment]
Hi Marcos,

Sure but first I will need permission to push a branch and make a PR
against that repo.

Message I get
remote: Permission to Adyen/adyen-dotnet-api-library.git denied to
NemanjaMilenkovic990.
fatal: unable to access 'https://github.com/Adyen/adyen-dotnet-api-library/':
The requested URL returned error: 403

Here is my Github Account: https://github.com/NemanjaMilenkovic990

Best Regards

**Comment by AlexandrosMor** [comment]
Hello @NemanjaMilenkovic990,

There is a guide that you can follow and open a pr.  You can find the guide [here](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/CONTRIBUTING.md)

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @NemanjaMilenkovic990,

I would like to ask if the guide was helpful for you,

regards,
Alexandros

**Comment by NemanjaMilenkovic990** [comment]
Hi Alexandros,

I did not had time to look into it. I'll let you know when I do so.

Thanks for the help.

Best Regards,
Nemanja

**Comment by NemanjaMilenkovic990** [comment]
HI Alexandros,

That guide was really helpful, thanks.

Here is the Pull Request:
https://github.com/Adyen/adyen-dotnet-api-library/pull/354

Best Regards,
Nemanja

**Comment by AlexandrosMor** [comment]
Hello @NemanjaMilenkovic990,

Thank for opening the pull request. We really appreciate your efforts. We investigate the issue and we extended the newtonsoft json with a custom deserializer [PR](https://github.com/Adyen/adyen-dotnet-api-library/pull/347) and I added a unit test for paypal [here](https://github.com/Adyen/adyen-dotnet-api-library/pull/355) 

Could you please check if this solve the subtype issue for you ?

Kind regards,
Alexandros

**Comment by NemanjaMilenkovic990** [comment]
Hello Alexandros,

I have implemented your fix with our current solution, and I must say that
after I have implemented it and took the value for our paymentsRequest
object based on that fix the subType issue is still not resolved.

So far with or without this fix smart payment will not work if SubType
property is not implemented in DefaultPaymentMethodDetails.cs

Best Regards,
Nemanja

**Comment by AlexandrosMor** [comment]
Hello @NemanjaMilenkovic990,

The idea here is that the DefaultPaymentMethodDetails class is not used anymore and each payment method is deserialized in a separate class. In case of pay pal is PayPalDetails with Subtype. The end result is that paymentsRequest is contains the payment method using the [Interface](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/IPaymentMethodDetails.cs) and not the DefaultPaymentMethodDetails.

```IPaymentMethodDetails paymentMethod = new PayPalDetails() { Subtype= PayPalDetails.SubtypeEnum.SDK} ```

kind regards,
Alexandros 
Adyen

**Comment by AlexandrosMor** [comment]
This is fixed with the latest release 
https://github.com/Adyen/adyen-dotnet-api-library/releases/tag/6.0.0
It is available to nuget too
