### ISSUE TITLE
RecurringProcessingModel property missing from CreatePaymentLinkRequest

### ISSUE THREAD

**Issue by gtodde** [Adyen/adyen-dotnet-api-library#336]
Hello,

I'm using the `Adyen.Model.Checkout.CreatePaymentLinkRequest` class to implement Pay by Link, and I'm noticing that it is missing `RecurringProcessingModel` as a property.

When I make a request for a payment link, thus, I cannot include `recurringProcessingModel` as a parameter, which is required along with `shopperReference` and `storePaymentMethod` to tokenize payment details for subscriptions, according to documentation: https://docs.adyen.com/checkout/pay-by-link?tab=api__2#tokenize-subscriptions. As a workaround I'm doing a direct HTTP request to the API to include the parameter.

Will the property be added soon to `CreatePaymentLinkRequest`?

Thanks.

**Comment by AlexandrosMor** [comment]
Hello @gtodde,

Thank you for pointing this issue. Correct, the ```recurringProcessingModel ``` is missing from the ```CreatePaymentLinkRequest ```. We are going to create an internal ticket. It is always faster for you to open a PR with a unit test fixing this issue. Then we can review it and merge it.

kind regards,
Alexandros

**Comment by gtodde** [comment]
Hello @AlexandrosMor,

thank you for the swift reply. In the meantime I have attempted to fix the issue and opened the PR you see above: #337. Let me know if there's anything to correct.

Thanks!
Giulia

**Comment by AlexandrosMor** [comment]
Hello @gtodde,

Thank you for the PR we merged it and we are going to include it in our next release

Kind regards,
Alexandros
Adyen
