### ISSUE TITLE
/payments/details does not support Idempotency Key

### ISSUE THREAD

**Issue by dominicce** [Adyen/adyen-dotnet-api-library#345]
Hi,

We are seeing duplicate authorisations on 3ds1 calls, where we were advised to use the idempotency keys by Adyen support.

Whilst we were able to add it onto the /payments call, it doesn't seem possible to do that with the SDK on /payments/detail - is this a bug or is there a reason this has been excluded on purpose?

Where we have tried to work round it, it seems the call then fails.

Thanks,

**Comment by AlexandrosMor** [comment]
Hello @dominicce,

Thank you for pointing this issue. There is an open PR #346 for adding the idempotency key to on /payments/detail request.

We are going to review it and merge it as soon as possible

kind regards, 
Alexandros

**Comment by dominicce** [comment]
@AlexandrosMor thanks for approving.  @RyanONeill1970 is the developer we're working on the project with.
