### ISSUE TITLE
Please provide an update so checkout v64 api calls can be made

### ISSUE THREAD

**Issue by Darksci** [Adyen/adyen-dotnet-api-library#356]
**Is your feature request related to a problem? Please describe.**
We are using .NET Server side so using https://www.nuget.org/packages/Adyen/, and the latest version 5.7.0. However looking at the client object it says it is using v51 instead of v64.

This is preventing ApplePay integration (using Adyen's own implementation of Apple Pay). Since the output of checkout.paymentMethodsResponse.paymentMethods is currently:
{key: "applepay.token", type: "applePayToken"}

Which should actually contain more key-value pairs on a newer version of the endpoint.

**Describe the solution you'd like**
A new release of the Nuget package which will allow calls to v64 for the /paymentMethods API request.

**Describe alternatives you've considered**
None since we are using .NET Server backend for Adyen.

**Additional context**

Many thanks

**Comment by gregleon** [comment]
Seconded

**Comment by AlexandrosMor** [comment]
Hello @Darksci,

We updated the models with this [PR](https://github.com/Adyen/adyen-dotnet-api-library/pull/359). We are going to release the library soon. 

 Regards,
Alexandros
Adyen
