### ISSUE TITLE
Adyen.Model.Modification.CaptureRequest does not include Splits

### ISSUE THREAD

**Issue by jpeckham** [Adyen/adyen-dotnet-api-library#366]
**Is your feature request related to a problem? Please describe.**
I'm trying to do manual /capture with splits and I do not see a way to do it. 

**Describe the solution you'd like**
Add 'Splits' to the Adyen.Model.Modification.CaptureRequest object

**Describe alternatives you've considered**
I tried inheriting from Adyen.Model.Modification.CaptureRequest and extending it but then the serializer won't get the property either.

**Additional context**
https://docs.adyen.com/api-explorer/#/Payment/v64/post/capture__reqParam_splits

**Comment by jpeckham** [comment]
i hacked it in with this:
```
    public class ExtendedCaptureRequest : Adyen.Model.Modification.CaptureRequest
    {
        [System.Runtime.Serialization.DataMember(Name = "splits", EmitDefaultValue = false)]
        public List<Adyen.Model.Split> Splits { get; set; }
    }
    public class ExtendedModification : Modification
    {
        private readonly Capture _capture;

        public ExtendedModification(Adyen.Client client)
        : base(client)
        {
            _capture = new Capture(this);
        }

        public async Task<ModificationResult> ExtendedCaptureAsync(ExtendedCaptureRequest request, Adyen.Model.RequestOptions requestOptions = null)
        {
            var jsonRequest = Adyen.Util.JsonOperation.SerializeRequest(request);
            var jsonResult = await _capture.RequestAsync(jsonRequest, requestOptions);
            return Adyen.Util.JsonOperation.Deserialize<ModificationResult>(jsonResult);
        }
    }
```

**Comment by AlexandrosMor** [comment]
Hello @jpeckham,

Thank you for raising this issue. We opened a pr for this and we will included to the next release.

kind regards,
Alexandros
