### ISSUE TITLE
Google pay payment fails because the payment models are different

### ISSUE THREAD

**Issue by akScript** [Adyen/adyen-dotnet-api-library#376]
**Bug Description:**
When using Adyen Drop-in for web, doing a payment using google pay sends the following model:
```
{
	"paymentMethod"` : {
		googlePayCardNetwork: "VISA",
		googlePayToken: "{"signature":"MEUCIQ..",
		type: "paywithgoogle"
	}
}
```
While using the class Adyen.Model.Checkout.DefaultPaymentMethodDetails as Data model to deserialize the JSON, the property `googlePayCardNetwork ` and `googlePayToken` are not deserialized

for `DefaultPaymentMethodDetails.GooglePayToken` it seems to be linked to `paywithgoogle.token` instead of `googlePayToken`
for `googlePayCardNetwork `does not exist the `DefaultPaymentMethodDetails` class.

also using the JSON `PaymentMethodDetailsConverter` is not possible because it is declared `internal`

Adyen .net Package version: 6.0.0
@adyen/adyen-web version : "3.20.0"

**Comment by AlexandrosMor** [comment]
Hello @akScript,

You should use the [google pay details](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/Details/GooglePayDetails.cs) and not the  DefaultPaymentMethodDetails class

regards,
Alexandros

**Comment by akScript** [comment]
Hello @AlexandrosMor,

I'm using Adyen Drop-in for web with multiple payment methods and It is the user who selects what payment methods to use so at the time of making [making a payment](https://docs.adyen.com/online-payments/drop-in-web#step-3-make-a-payment) the data could be for any payment method

best regards
akScript

**Comment by AlexandrosMor** [comment]
Hello @akScript,

Thank you for checking. We are currently working on a new patch release to fix these issues as we see there are some serialization issues. This issue is fixed with this [pull request](https://github.com/Adyen/adyen-dotnet-api-library/pull/369/) in develop by adding the annotation on [IPaymentMethodDetails](https://github.com/Adyen/adyen-dotnet-api-library/pull/369/files#diff-5333bcf0425efa6c2a3bc1af19f16eeb152337db3333505c42b0a66502dbe4c6R579) . If you could test that too that would be great.

regards,
Alexandros

**Comment by akScript** [comment]
Hello @AlexandrosMor
I changed the code so it uses `Adyen.Model.Checkout.PaymentRequest` as a model and it now works

**Comment by AlexandrosMor** [comment]
Great to hear! Thank you for letting us know :) We can close this issue.

**Comment by darioflorz** [comment]
Hi,

Hi, I have a slightly different problem. When using Android drop-in doing a payment using google pay sends the following model: 
```
{
   "paymentMethod":{
      "type":"googlepay",
      "googlePayToken":{
         "signature":"MEQCIC9DduYAFQ6…"
      },
      "googlePayCardNetwork":"VISA"
   }
}
```
It gets deserialized to `DefaultPaymentMethodDetails` When using `PaymentMethodDetailsConverter`  which causes the payment to fail.
