### ISSUE TITLE
Terminal API AbortRequest results in exception

### ISSUE THREAD

**Issue by RickWieman** [Adyen/adyen-dotnet-api-library#38]
The integrator of one of our merchants reported an exception when sending a Terminal API AbortRequest through the library:

> "An exception occured when trying to abort :
>   Error reading JObject from JsonReader. Path '', line 0, position 0."
>  
> In your "ecommlibrary" and file "SaleToPoiMessageSecuredSerializer.cs" and method "internal SaleToPoiMessageSecured Deserialize(string saleToPoiMessageSecuredJSon)"
> The argument saleToPoiMessageSecuredJSon = "" and throws the exception when trying to parse the "JObject".

The terminal gives an empty response body (with HTTP 200) in case of an AbortRequest, so I think the problem is caused by an attempt to parse that empty response into an object.

**Comment by AlexandrosMor** [comment]
Hello @RickWieman 

We created an internal ticket for this issue. 

regards,
Alexandros Moraitis,
Adyen
