### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by dalton5** [Adyen/adyen-dotnet-api-library#380]
Hi,

I use api from Adyen test environement.

I try to connect on it and create an account holder.

But I always have 401 error

My code is as below:

`
        static Client client = null;

        public static async System.Threading.Tasks.Task CreateAccountAdyenAsync(string locale, string currency)
        {

            client = new Client("AQ**************************", Adyen.Model.Enum.Environment.Test);
            Console.WriteLine("Create Account");
            var account = new Adyen.Service.Account(client);
            var createAccountHolderRequest = new CreateAccountHolderRequest(accountHolderCode: Guid.NewGuid().ToString(), accountHolderDetails: new AccountHolderDetails(email:"a******@gmail.com",
                individualDetails: new IndividualDetails { Name = new ViasName(firstName: "Al", lastName: "Az", gender: ViasName.GenderEnum.UNKNOWN)})
            , legalEntity: CreateAccountHolderRequest.LegalEntityEnum.Individual, primaryCurrency:currency);

            var createAccountHolderResponse = account.CreateAccountHolder(createAccountHolderRequest); // 401

          
        }`

I generated my test api and pasted it from here

![image](https://user-images.githubusercontent.com/8339768/106475590-64988d00-64a6-11eb-8060-0ec78240f618.png)

My client:

![image](https://user-images.githubusercontent.com/8339768/106475728-8eea4a80-64a6-11eb-81ca-b6ec9be8d54c.png)

Error details

![image](https://user-images.githubusercontent.com/8339768/106475821-ad504600-64a6-11eb-9859-e40eaa7ca13a.png)

   at Adyen.HttpClient.HttpUrlConnectionClient.Request(String endpoint, String json, Config config, Boolean isApiKeyRequired, RequestOptions requestOptions)
   at Adyen.HttpClient.HttpUrlConnectionClient.Request(String endpoint, String json, Config config)
   at Adyen.Service.Resource.Resource.Request(String json)
   at Adyen.Service.Account.CreateAccountHolder(CreateAccountHolderRequest createAccountHolderRequest)
   at StripeTester.Program.<CreateAccountAdyenAsync>d__2.MoveNext() in C:\Users\Alex\Documents\Visual Studio 2019\AdyenTester\Program.cs:line 28
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

So what is the issue?

**Comment by AlexandrosMor** [comment]
Hello,

The error code 401 is Unauthorized. Could you try use the same xapi key with postman? If there an access issue please contact Adyen support to help you with the account.

Regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @dalton5,

Do you have any updates on this issue ?

kind regards,
Alexandros
Adyen

**Comment by dalton5** [comment]
yes. To access to the platform API you need to be validated by aldyen.

Unfortunately we received a no because we are starting a startup and they only work with big startups or companies. Seles representative told us this.

Then Adyen doesn't want to give the chance to startups which start then we will move to stripe or lemonpay...

Thanks anyway for your help and the follow up!

**Comment by AlexandrosMor** [comment]
Hello @dalton5,

Sorry to hear that. I will close this issue. 
Good luck with the startup :)

kind regards,
Alexandros
Adyen
