### ISSUE TITLE
Payment Details request fails with redirect result

### ISSUE THREAD

**Issue by fridastenebo** [Adyen/adyen-dotnet-api-library#381]
**Describe the bug**
After updating to 6.1, we can't complete a `payment/details` request with `RedirectResult` data, likely because the `PaymentResultRequest` model is outdated.
We started to see that our redirect back from flows with a redirect, like iDeal and Sofort, didn't look like they previously did. previously, the returnUrl that we had provided with the payment request, had been appended with a `payload` object. But it seems this has been changed in the latest [Checkout API v. 66](https://docs.adyen.com/online-payments/release-notes#checkout-api-v66);

> **POST /payments**
> 
> * For redirects, except 3D Secure redirects, the response now contains `details.key`: **redirectResult** instead of `details.key`: **payload**.
>
> **POST /payments/details**
> 
> * For redirects, except 3D Secure redirects, `redirectResult` is now the only way to specify the redirect result in the request, replacing `payload`.

The first bullet, I could account for in our frontend by updating our models, but the second bullet relies on the models of this library.
Can we use another model that contains the `redirectResult` or can the existing be updated?

**To Reproduce**
Steps to reproduce the behaviour:
1. Complete a redirect payment (Sofort or iDeal)
2. Observe that the returned GET contains a `redirectResult` object instead of the previous `payload`
3. Send in a `payments/details` request with `PaymentResultRequest` as the payload
4. Get error 409 - which probably is an irrelevant error since this worked previous to upgrading this library from 5.6->6.1

**Expected behaviour**
A successful Payment Details API call

**Library Version:**
adyen-dotnet-api-library v.6.1.0

Thank you in advance 🙂

**Comment by AlexandrosMor** [comment]
Hello @fridastenebo, 

I see that the redirectResult  is in the [PaymentCompletionDetails class](https://github.com/Adyen/adyen-dotnet-api-library/blob/ada2efcd4e50651046a4a2621840ab4dc6e0fa2a/Adyen/Model/Checkout/PaymentCompletionDetails.cs#L175) which is used in the [PaymentsDetailsRequest](https://github.com/Adyen/adyen-dotnet-api-library/blob/ada2efcd4e50651046a4a2621840ab4dc6e0fa2a/Adyen/Model/Checkout/PaymentsDetailsRequest.cs). 
The PaymentsDetailsRequest is used as an argument to make the payments/details API call using the [checkout class](https://github.com/Adyen/adyen-dotnet-api-library/blob/e220d4787150dec78fe90f8c09e28085d2be4467/Adyen/Service/Checkout.cs#L109).  

Could you try instead using PaymentResultRequest to use the PaymentsDetailsRequest to complete the  payments/details API  call? Please let us know the results so we can assist you further.

 kind regards,
Alexandros

**Comment by fridastenebo** [comment]
Thank you for the response! 
By what you said, I realized we were actually using the (old?) `payments/result` endpoint for this. On option can, of course, be for us to migrate to using the `details` endpoint (as we are in other flows like 3DS already), and it seems to work. Still not sure why the paymentsResult request doesn't seem to work, but maybe that's a question for the generic Adyen-support rather than here.
Thank you for your assistance.
