### ISSUE TITLE
Error in payment link if not passing in required values into constructor

### ISSUE THREAD

**Issue by bjarnef** [Adyen/adyen-dotnet-api-library#384]
**Describe the bug**
Using Adyen v6.1.0 https://www.nuget.org/packages/Adyen/6.1.0 and creating payment link request, it seems to fail if not passing in these required values into contructor, but using literal notation syntax.

- Amount
- Merchant Account
- Reference

```
// Create a payment request
var amount = new Adyen.Model.Checkout.Amount(currencyCode, orderAmount);
var paymentRequest = new Adyen.Model.Checkout.CreatePaymentLinkRequest
{
    Amount = amount,
    MerchantAccount = settings.MerchantAccount,
    Reference = order.OrderNumber,
    ReturnUrl = settings.ContinueUrl,
    ShopperEmail = order.CustomerInfo.Email,
    ShopperReference = order.CustomerInfo.CustomerReference,
    ShopperName = new Adyen.Model.Checkout.Name
    (
        firstName: order.CustomerInfo.FirstName,
        lastName: order.CustomerInfo.LastName
    ),
    Metadata = metadata
};

if (paymentMethods?.Count > 0)
{
    paymentRequest.AllowedPaymentMethods = paymentMethods;
}

var environment = GetEnvironment(settings);

// Create the http client
var client = new Adyen.Client(settings.ApiKey, environment);
var checkout = new Adyen.Service.Checkout(client);

var result = checkout.PaymentLinks(paymentRequest);
```

However changing to this instead works:

```
// Create a payment request
var amount = new Adyen.Model.Checkout.Amount(currencyCode, orderAmount);
var paymentRequest = new Adyen.Model.Checkout.CreatePaymentLinkRequest
    (amount: amount,
    merchantAccount: settings.MerchantAccount,
    reference: order.OrderNumber)
{
    ReturnUrl = settings.ContinueUrl,
    ShopperEmail = order.CustomerInfo.Email,
    ShopperReference = order.CustomerInfo.CustomerReference,
    ShopperName = new Adyen.Model.Checkout.Name
    (
        firstName: order.CustomerInfo.FirstName,
        lastName: order.CustomerInfo.LastName
    ),
    Metadata = metadata
};

if (paymentMethods?.Count > 0)
{
    paymentRequest.AllowedPaymentMethods = paymentMethods;
}

var environment = GetEnvironment(settings);

// Create the http client
var client = new Adyen.Client(settings.ApiKey, environment);
var checkout = new Adyen.Service.Checkout(client);

var result = checkout.PaymentLinks(paymentRequest);
```

**Expected behavior**
It should be possible to specificy amount, merchant account and reference using literal notation or the `CreatePaymentLinkRequest` should only have overload which requires amount, merchant account and reference.

**Screenshots**

![image](https://user-images.githubusercontent.com/2919859/107149921-9b195080-695b-11eb-8deb-b2c8bad62f69.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 88.0.4324.146

**Comment by AlexandrosMor** [comment]
Hello @bjarnef,

The models are autogenerated from open api specs. If a property is marked as `required` in open api specs, the model would be generated with these properties passed from the constructor and if they are not present it throws an InvalidDataException.
The reason behind this is the Adyen api v66 returns an error if the required fields are missing so the model forces the developer to pass them. I understand that it should be possible to pass the properties with the getter but for now changing it is not in our roadmap.

kind regards,
Alexandros

**Comment by bjarnef** [comment]
@AlexandrosMor okay, thanks for the explanation. Just need to be aware of that the constructor in this case should be used.
Btw. when looking at the API library and the API documentation https://docs.adyen.com/api-explorer/#/CheckoutService/v66/overview I couldn't find any endpoint the `GET` payment data/details like most other payment gateways has, e.g. the check the payment status.

There are endpoints to cancel, refund and capture, but isn't there anything to get a payment from id / transaction id = psp reference?

**Comment by AlexandrosMor** [comment]
Hello @bjarnef,

There is not such an endpoint. You can always check the transaction status in the adyen back office

regards,

**Comment by bjarnef** [comment]
@AlexandrosMor yeah, but looking at integration of Adyen in the ecommerce Vendr for Umbraco CMS, there a `FetchPaymentStatus`. This is useful when the payment is pending and it might take a while before the payment has been processed.
https://github.com/vendrcontrib/vendr-payment-provider-adyen/blob/dev/src/Vendr.Contrib.PaymentProviders.Adyen/AdyenCheckoutPaymentProvider.cs#L147

I can disable this though if not supported https://github.com/vendrcontrib/vendr-payment-provider-adyen/blob/dev/src/Vendr.Contrib.PaymentProviders.Adyen/AdyenCheckoutPaymentProvider.cs#L26 but just wondering why Adyen hasn't an endpoint for this?

All these payment gateways have endpoints for this:

- Bambora
- DIBS/Nets
- QuickPay
- Reepay
- Yourpay
- Stripe
- PayPal
- Opayo (Sage Pay)

Is there a specific reason Adyen doesn't support this
