### ISSUE TITLE
Exception on 3D secure 1 redirection fallback

### ISSUE THREAD

**Issue by michelerubino** [Adyen/adyen-dotnet-api-library#388]
While testing the 3D secure payment with a CC number that requires fallback to 3D version 1 (number 4212 3456 7890 1237) I encounter a NotSupportedException, can you help me determine the cause? Below I've included the payment data and the error message. I'm currently using library version 5.3.0

PAYMENT DATA

PaymentRequest:
Time=2021-02-18T15:01:12
MerchantAccount=JuventusFCCOM
Amount:
Currency=EUR
Value=300
ReturnUrl=http://parking-test.juventus.com/pay
Reference=0000000701
Channel=Web
Origin=https://parking-test.juventus.com
AdditionalData:
allow3DS2=true
PaymentMethod:
EncryptedCardNumber=adyenjs_0_1_25$PvUiXSQKBrTVkegi0XXWVQMPx5RCt+R3RtQrL4LACcj+2fpg7SYQ7BXJ7+GS3HCnWlU4m3hEocCHpFT23AQA2Nqi99a4cM+ZKTEqBbO4f6DviNTbz5NQ0EvdVvrfqwF04vLFPouaVRFg9/wcN848Qw6h7GtoOS2VxRGMnuWIPwO/RDTsPvu0y6e3ksRGS3Ooh34S6D76zMtwnQWz5qz1/N9UyhUgukDmDxKbdIvsToVjjxlZo57lspCPgnBrJAbvEJqCF3mcaBZF3KpW3jiHIH/raXsG4yjqzuvx2lYxmUpLUx7+WUDlAbBDE+ur2BOxYQmjNujMBRk8Kf2HWzWRWA==$ZrWKskzOwp+EtEqvhz9Mkl11fBWHWF4arWvLavwHfl1i8mUtwQR793RRvv2hfrwrS+9C1jqA2B/h9aAP/UwY2pxyVIbbBGdJRzW0nFn5+nImhKDpUGL5eO2Gn15EKKH5bcScOgpjSvwFpIuxD3XZ168yXpA5c/VVDKgSZnFYW0rMcNsn2Vt2bCeQo+VCoqiJ6srUBHqgvaMfHIaALI3aMGf1NX+ia379SuRimGWiHb2FRoZ6fIPilO5zUxO3cVEJAfHX743hwcaz5rqjY38RLvd/RmrVJuy2c4hWNEC/kbm3wblzMCDqeuytCmdTqBDWOjz0ohRg+yEa9Lo0Ss2tq9Fu1Km5yr8QaHY83QLPb2OSOuabtWDfpgoEKfM78Y0rmnbybjnvgweWXncW5xCRBF71NcDUYEMJEBWeqYtvklqgf7QpgttDYXq1APYOWg9nHKtg01C0/QCnliCvPDfIh1C/LGo8IkyZw2qbPZ0eu8FmOUCnTMI1FAjhpN3XMrtgwTz9DocoQvjiFQOo0H2wojbmNgwz1RB44+bM+fLCggTzPd6HPldEcmbfy4NICd04XVfNp9Y2/sLtqiZ0mpF6PhP+NBwQ+AHzJDNJvuZHJd/y8jwGPvQLsl9yOfK6iCKwJMjJ6jhoLaGDfvDJQShqRSvTbPICAd7PrzvvZetqcAKVZaZmQSPNbgCiAlhEqv9LkF5DihYPhO2f5S6RXo8J+VDdPYyW4EGqV7xiJBQ9kocecMrVksbcbYLzN+89dE1jm/G/8F5V10DaONRsbABsUj4G6CN/gxAt3hM69JhXpc2BSOljCXKIZz1kmDWzCVGua8nCOvdiBAXWyp/jjIOcIKaJkwPM+5uXW4kPDY9cAftDMli3fl4oil4OKERApEuMOQBe6g+4
EncryptedExpiryMonth=adyenjs_0_1_25$HtGsjX7W4kPSfMWGMLEozgcnu51TlXTu207NqsKfohyCVYXCrMVS0peef5ZGUrzHWWWN05WdmHC8hAvpPr4+3HNUevorY8FBZ5MoCFLoRIXTwbrtB0/GpeCJB9JSWuiV+vU+DiddUizxLF6qCjdKTlXQurtf6pwJJxFuzkZbLst12jmuH29hrAw5ogQZFZq1EjTOmUp23piReCxt4tLg5N3skbSnpFgCUbFH4CWrbL3CSrzQSUCI/oc1PAqXRYNPJmVSjVSsiYwZlZFdRO4MOIZgYV5RWlC7WlExieStuCrjKwQAWIkNxYfU//DWop9Tw/V4onlUniylsLjuzfQCoA==$7VBO4UApR2quOsnSi8pkKtp93yozbNpP8ROiAl6BsWg5TeZeH598/aq1tIPF/1J4KEqhT7UBSR7q5CBPPVFJcGVMo32yL76wKZPqFm9xMDDbwzKxEMCduICUcYKAO3WJBlnM9sm/k6u2GiONUzSDMmX5lXmyzz1XzKybrz+hp+eIZ8xPSlCeALAkAC9qdOHGOQc6DMm+lfwykTv2qtZa9GD7VNpKijR3teB9U0oP0OzItE2/hlMpalW/+eDxgC9k9vnVWcN7uCxBwzpCTLDyHuetEOv8PxcqK3JnT/l+dJGanJlq6Zk15VoboJEwZhu3dUh0leMYS8AxrSHjPDCgu4keYnKlKPvBUMEV46+9IC0sGLZryscLGgw+O160T2VxG8Ff1LvebclA1ERahZk8wQxn06DBZ/0rRXpDtuR3ouIg+RNdoem1OkKXvNkQlnKTfmStHovCKCZugwVPGmKwzb3xFg68ET0WfHsV76ui0w==
EncryptedExpiryYear=adyenjs_0_1_25$XtmZiHcCpbJjPPSb23whQkl+GCXXExR+wXwA/vPfig7iR1V8jWxz7uwbq30EnFxa+9i/Fqk9O3c+0UqytCw5Tj4wuUSDaouL0TrNDu8L7wwlgOt/IHaHQmxHJiMWbdRCIuj/sPTBk2WLns4tuNwiMsJ3asxn2ZUJGRr9qgfdWR2EQ+vchpij+il18lqbdJYBXto358xfWjhTDEx8GY9z52GNVWksLMLP2ikkZZx3PJHBSranjZfB46rXSFhfj8J2Yfm8bCgViiOk3Zrc3j6+bbnn5FFTKs32tOb1QdWcC4J09GjxXRtP32ENki0KZXOGNRBiNGQavOZI6A1l2L6tmA==$4FUSHd3Rzk5i5bjj3+kQwjOo2ycBFs/jt7++K1f2WVdY8QRrV4TyT+RuIIFI6xhJg9bzYmI1yo8Ysbn8xOyNnI+8W4hxhPcBzu3KHhzfHbX+pg9qrVGiKVPhMGq97XVyoVld1syI3hdeKBU20EVMoXs/vnsAQX1ZWRILy7ACLrwxaDXJyLqRV6wenSd9JMPjweQot1VOP2NJil0/E8qQng4lbvjFrv2zNFEObLgwUt2qcl835a2nR7CGzQGPn4ESMhfsGVWg33YxJ86ZPmZh10iShPyMPeuLR3LrLGiaalgp803gMlVY4aAghBoav0STDFgmsRkUCZqtqIdEl/yMyMRtIc6SmuqarfQobph9COlmVKKkEGqfx3yF4SvO2lhroiIQzxlXuNsU5EADcg8C6kMSScfoGCId28cvWvEnVbVRpBOYYHAREoi7xeWZqBpkTZLC5MXQoN7Bky9eu5UX5zBbCy7OYzeKgF19lLM7zqU=
EncryptedSecurityCode=adyenjs_0_1_25$N957KkwgL/kQ6UNp/Lw4Ckf5CXAt9cc7EArUhUv5VK7PZHo+8CkwE9e30hcRilWiC2YK6f7R2iP18CeXinuUE7zaQtPp++LcmF/33pJH4CXgis15xinghd24BMZRuwpCEWxYQXrCxjUhOep3P83u3u2z/hTyfTEXKNoIDhpBdZmHy9nNWJJX6/1pTmh4yXWmnHZY6ApaCO4JtB3G21m3ogrERMRYxW+diE9bRPSNPQueWXOuGqgcaLmeCEpYGi1jAsJiEVqPQINHqp22JZ95jXIUSw2O6l5s6WbeNSmZ+t4o2Paxww/bVj/0wbXO4uKM8ZGHEdJdRX31kAr+yW3Iqw==$BZEMB9oexglgCXdGUawomhlsa4RnLnqIVt184P70Nrp+8Jx5YpkO4cG1ivS0Q9DXsmrltMxjJdYfaNc0kZKqlrn3W1YQ5YZ2aeJPn3PIrLDEJTtS6FK/F+IBOTBg3CbE6OGYEldd7PYD673pnohnw7wMqLhZWPJJNZ3+8apr+lqjMH5EiZIwWxMq0zGUhZvgOxPIc744G353rqDp8W22Q5gJ6Ks6LTPBOxWAAw7mOPAYVGXnGzQ2/DVT8tI++i+HouMzFcnuSN7+DzUkxG3ma8Rk1JnQNzFhBZ7q5GXwV7MuWUAKcGkEtM0ZUx6A0pIoa8S6JRaKYIW3ut7cakA4/YM5Mc1W9HUL44KKh6DS7Mbr9JySEEXyNs7kkjhMs/ojzUrsMx2BrUdC6g7lAOPmcwC6ndAYNkQgFxvqHahHwJK426oZ8yLZisanLRgMc9dVIhwJDfEd2wWafxtV9BW8mJOT8QTOZvUB
SepaOwnerName=
SepaIbanNumber=
Type=scheme
BrowserInfo:
AcceptHeader=*/*
JavaEnabled=False
ColorDepth=24
ScreenHeight=864
ScreenWidth=1536
TimeZoneOffset=-60
UserAgent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
Language=it-IT

ERROR MESSAGE

{"@timestamp":"2021-02-18T15:01:13.1818704+00:00","level":"Error","messageTemplate":"Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\": An unhandled exception was thrown by the application.","message":"Connection id \"\"0HM61RG8A7O6K\"\", Request id \"\"0HM61RG8A7O6K:00000001\"\": An unhandled exception was thrown by the application.","exceptions":[{"Depth":0,"ClassName":"System.NotSupportedException","Message":"The collection type 'System.Object' on 'Adyen.Model.Checkout.CheckoutPaymentsAction.Data' is not supported.","Source":"System.Text.Json","StackTraceString":"   at System.Text.Json.JsonPropertyInfoNotNullable`4.GetDictionaryKeyAndValueFromGenericDictionary(WriteStackFrame& writeStackFrame, String& key, Object& value)\n   at System.Text.Json.JsonPropertyInfo.GetDictionaryKeyAndValue(WriteStackFrame& writeStackFrame, String& key, Object& value)\n   at System.Text.Json.JsonSerializer.HandleDictionary(JsonClassInfo elementClassInfo, JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)\n   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)\n   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)\n   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)\n   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\n   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146233067,"HelpURL":null}],"fields":{"ConnectionId":"0HM61RG8A7O6K","TraceIdentifier":"0HM61RG8A7O6K:00000001","EventId":{"Id":13,"Name":"ApplicationError"},"SourceContext":"Microsoft.AspNetCore.Server.Kestrel","RequestId":"0HM61RG8A7O6K:00000001","RequestPath":"/api/v1/pay","SpanId":"|d1f7b975-4924009e15bc0e94.3.c1c99e45_","TraceId":"d1f7b975-4924009e15bc0e94","ParentId":"|d1f7b975-4924009e15bc0e94.3."}}

**Comment by AlexandrosMor** [comment]
Hello @michelerubino,

Thank you for raising the issue. Could you maybe try with the latest version of the library ? Furthermore, you could check our examples [here](https://github.com/adyen-examples/adyen-dotnet-online-payments) Let us know if updating the library solved the issue for you 

Kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @michelerubino,

Are you still facing this issue ? Was the example helpful for you ?

Kind regards,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment]
Hello @michelerubino,

I believe the issue is resolved for you. If you have further questions please feel free to open a new issue

Kind regards,
Alexandros
Adyen
