### ISSUE TITLE
[PW-4290]FraudResults.Results.FraudCheckResult deserialization issue

### ISSUE THREAD

**Issue by whitej031788** [Adyen/adyen-dotnet-api-library#392]
**Describe the bug**
After turning in Fraud Results in the API response and seeing the data come back in the raw HTTP response from Adyen. The .NET library is not properly deserializing that data into the PaymentResponse. **FraudResult** is fine, with **AccountScore** and **Results** populated. However, the Results is a list of FraudCheckResult objects, all of which have null properties (AccountScore, CheckId, Name).

Looking at the way FraudResult object is defined, the JSON response will not map “results” correctly to List<FraudCheckResult>, as the raw API response is not simple one dimensional objects; instead, each list item has a top level **FraudCheckResult** from the API response.

**To Reproduce**
1. Install the .NET Adyen NuGet package
2. Turn on Fraud Result in the Additional Data for the synchronous Adyen response
3. Use the .NET package to make a simple /payments request, set a breakpoint after getting response
4. Interrogate PaymentResponse to see that the Results array in the FraudResult all has empty properties

**Expected behavior**
The fraud results to be properly deserialized into the FraudResult in the PaymentResponse

**Screenshots**
![FraudCheckResults](https://user-images.githubusercontent.com/5017685/109475593-d0522380-7a6d-11eb-82f1-7d4b087ce79a.png)

**Comment by AlexandrosMor** [comment]
Hello @whitej031788,

Thank you for raising this issue, We are going create an internal ticket and investigate this issue. 

Regards
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @whitej031788,

I opened a pull request with a fix. Would you have some time to test it ?

Thank you in advance,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment]
Hello

It is planned to released with version 7.0.0
Alexandros
Adyen

**Comment by AlexandrosMor** [comment]
We released the library 7.0.0 including the fix for the FraudResults
