### ISSUE TITLE
Can't deserialize PaymentResponse from json

### ISSUE THREAD

**Issue by smafre** [Adyen/adyen-dotnet-api-library#397]
When trying to deserialize PaymentResponse from JSON I get an exception. `Newtonsoft.Json.JsonSerializationException : Could not create an instance of type Adyen.Model.Checkout.Action.IPaymentResponseAction. Type is an interface or abstract class and cannot be instantiated. Path 'action.paymentData.....`

1. Install version 6.1.0 of this package.
2. Create unit test trying to deserialize a dummy json to a PaymentResponse. I'm using the following code to create the dummy json:
`const string paymentResponseJson = "{\"resultCode\":\"RedirectShopper\",\"action\":{\"paymentData\":\"some data\",\"paymentMethodType\":\"scheme\",\"url\":\"https://test.adyen.com/hpp/3d/validate.shtml\",\"data\":{\"MD\":\"some data\",\"PaReq\":\"some data\",\"TermUrl\":\"http://localhost:4200\"},\"method\":\"POST\",\"type\":\"redirect\"},\"details\":[{\"key\":\"MD\",\"type\":\"text\"},{\"key\":\"PaRes\",\"type\":\"text\"}],\"paymentData\":\"some data\",\"redirect\":{\"data\":{\"PaReq\":\"some data\",\"TermUrl\":\"http://localhost:4200\",\"MD\":\"some data\"},\"method\":\"POST\",\"url\":\"https://test.adyen.com/hpp/3d/validate.shtml\"}}";`
I'm using Newtonsoft to deserialize the json to PaymentResponse:
`var paymentResponse = JsonConvert.DeserializeObject<PaymentResponse>(paymentResponseJson);`

I'm running dotnet core 3.1 on a Mac.

**Comment by AlexandrosMor** [comment]
Hello @smafre,

Thank you for contacting us. The library supports numerous of models for POS, checkout payout etc. It looks like the `PaymentResponse` that you are using for this case is part of POS and not of checkout. Could you please try with `Adyen.Model.Checkout.PaymentResponse` ?  
So you test would look like: 
`var paymentResponse = JsonConvert.DeserializeObject<Adyen.Model.Checkout.PaymentResponse>(paymentResponseJson);`

kind regards,
Alexandros 
Adyen

**Comment by smafre** [comment]
I'm sorry, I forgot to mention that I imported this in the top of the test file:
`using Adyen.Model.Checkout;`
So it's the same as doing `var paymentResponse = JsonConvert.DeserializeObject<Adyen.Model.Checkout.PaymentResponse>(paymentResponseJson);`

I am indeed using the `PaymentResponse` from checkout, not POS.

**Comment by AlexandrosMor** [comment]
Ok, could you maybe try to use the 
```
using Adyen.Util;

var paymentResponse = JsonOperation.Deserialize<Adyen.Model.Checkout.PaymentResponse>(paymentResponseJson);
```

**Comment by smafre** [comment]
That seemed to work great, my test is now green :)

So this is the way to serialize/deserialize all Adyen types? Using Adyen.Util and JsonOperation?

**Comment by AlexandrosMor** [comment]
Indeed use the deserializer from the util class :)

I am glad that it work for you

regards,
Alexandros
Adyen
