### ISSUE TITLE
[PW-4384] Can't find support for Technical Cancel

### ISSUE THREAD

**Issue by debski** [Adyen/adyen-dotnet-api-library#406]
**Is your feature request related to a problem? Please describe.**
We have a scenario where we would need to cancel an authorization without knowing the PSP reference. For this [technical cancel](https://docs.adyen.com/api-explorer/#/Payment/v64/post/technicalCancel) would be perfect. Unfortunately I can't find support for this call in the .NET library. 

**Describe the solution you'd like**
Add technical cancel support to Adyen.Service.Modification

**Describe alternatives you've considered**
I could work outside of the .NET library and build my own HTTP request, but defeats the purpose of having a SDK.

**Additional context**
This is for an error edge case, but still a scenario we need to handle

**Comment by AlexandrosMor** [comment]
Hello @debski,

Thank you for raising this issue. Indeed the technical cancel is not implemented so we will create an internal ticket to create it. It would be always faster for you to implement it and open a pull request.  You can check the [contributing guidelines](https://github.com/Adyen/adyen-dotnet-api-library/blob/8778daf1f49cdb855e586b65e0e3e68d2d60db2e/CONTRIBUTING.md)
