### ISSUE TITLE
Creating Adyen.Client throws InvalidOperationException

### ISSUE THREAD

**Issue by andreymir** [Adyen/adyen-dotnet-api-library#411]
I'm creating a client for Terminal API using the following code:

```csharp
var client = new Client(userName, password, environment)
{
  Config =
  {
    Endpoint = deviceUrl.AbsoluteUri,
  },
};

var api = new Adyen.Service.PosPaymentLocalApi(client);
```

This code works fine on Test environment, however, when I change the environment to Live the Client constructor fails with `System.InvalidOperationException` _Missing liveEndpointUrlPrefix for endpoint generation_.

**To Reproduce**
To reproduce the issues try the following code snippet
```csharp
var testClient = new Client("ws_123456", "******", Adyen.Model.Enum.Environment.Test)
{
  Config =
  {
    Endpoint = "https://192.168.1.10:8443/nexo",
  },
};

var testApi = new Adyen.Service.PosPaymentLocalApi(testClient);

var liveClient = new Client("ws_123456", "******", Adyen.Model.Enum.Environment.Live)
{
  Config =
  {
    Endpoint = "https://192.168.1.10:8443/nexo",
  },
};

var liveApi = new Adyen.Service.PosPaymentLocalApi(liveClient);

```

**Expected behavior**
The client should be created without errors for both Live end Test environments.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Adyen Library Version: 6.1.0

**Comment by AlexandrosMor** [comment]
Hello @andreymir, 

Thank you for contacting us. There are no two clients one for test and one for live in local terminal communication. The terminal is either test or live. Furthermore, as it is local communication you do not need to pass the credentials. The client should look like this. 

```
var conf = new Conf();
conf.Endpoint ="https://192.168.1.10:8443/nexo";
var testClient = new Client(conf);
``` 
In addition make sure that the test certificate is [installed](https://docs.adyen.com/point-of-sale/choose-your-architecture/local/secure-local-communications#validate-terminal-certificate) on the root trusted cert of you development environment and that you pass the encryption credentials.

kind regards,
Alexandros
Adyen

**Comment by andreymir** [comment]
Thanks @AlexandrosMor,

I tried that and it almost worked. Looks like the environment is required. When the environment is not set the certificate validation fails. https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Security/TerminalCommonNameValidator.cs#L35

I changed the code to
```csharp
var client = new Client(new Config
{
  Endpoint = deviceUrl.AbsoluteUri,
  Environment = environment,
});

_api = new Adyen.Service.PosPaymentLocalApi(client);
```
and it worked. 

Closing the issue.
