### ISSUE TITLE
Add more constants for additional data

### ISSUE THREAD

**Issue by bjarnef** [Adyen/adyen-dotnet-api-library#420]
Currently we have these constants available, which is useful when retrieving data from webhook notification, e.g. to verify `HmacSignature`: https://github.com/Adyen/adyen-dotnet-api-library/blob/master/Adyen/Constants/AdditionalData.cs

However I noticed a few addtional data returned from webhook notifications, which are not included: "paymentLinkId" and "merchantOrderReference".

For now I have added these in my own constant class plus some custom meta data prefixed with `metadata.`.

```
public class Constants
{
    // Adyen constants in .NET library: https://github.com/Adyen/adyen-dotnet-api-library/blob/master/Adyen/Constants/AdditionalData.cs
    
    public class AdditionalData
    {
        // Additional constants not included in library
        public const string PaymentLinkId = "paymentLinkId";
        public const string MerchantOrderReference = "merchantOrderReference";

        // Custom constants for metadata
        public const string OrderReference = "metadata.orderReference";
        public const string OrderId = "metadata.orderId";
        public const string OrderNumber = "metadata.orderNumber";
    }
}
```

Unfortunately the CANCELLATION notification currently only return `hmacSignature`, even though the "meta data" setting in enabled under addtional settings for the Standard Notification in Adyen. I have reached out to the support, but unfortunately this doesn't seem to have a high prioritization.

**Comment by AlexandrosMor** [comment]
Hello @bjarnef,

Thank you for your suggestion. You could also open a pull request and we are going to review it. 

kind regards,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment]
Hello @bjarnef,

The contribution guide can be found [here](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/CONTRIBUTING.md)

kind regards,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment]
Hello @bjarnef,

Could you check the pr if it is what you are missing from the lib ?

regards,
Alexandros

**Comment by bjarnef** [comment]
Currently I ended up with not using the SDK package as I didn't needed all the functionality and the API requests for the hosted payment page wasn't supported anyway.

But have these additional constants: https://github.com/vendrcontrib/vendr-payment-provider-adyen/blob/dev/src/Vendr.Contrib.PaymentProviders.Adyen/Constants.cs#L9-L11
