### ISSUE TITLE
[PW-4521]Will there be a package to align with the changes to the 2021 KYC updates?

### ISSUE THREAD

**Issue by scottpantall** [Adyen/adyen-dotnet-api-library#421]
Will this library be updated with the KYC updates needed (https://docs.adyen.com/platforms/onboarding-and-verification/kyc-requirements-update) before May 1?

**Comment by raelyard** [comment]
Any thoughts on this question? It's only a few weeks before the new requirements on the API go into effect and neither this library, nor the API documentation show the new required properties. Is there an expectation of a version of the API that will include these with or without a corresponding update to this library? Would a pull request for this be helpful or is something already in the works?

It would be useful to know what to expect.

@AlexandrosMor It looks like you often respond to issues here. Is there anything you can say about this?

**Comment by AlexandrosMor** [comment]
Hello @raelyard and @scottpantall,

We are going to create a ticket to prioritise this feature as looks like there are merchants working with KYC and using the library. Feel free to open a pull request with the related unit tests which could review and include to the coming library releases.

kind regard
Alexandros
Adyen

**Comment by raelyard** [comment]
Thank you for the update, @AlexandrosMor . Is there anything you can tell me about the update to the API for these requirements? I'm noticing that the test API still accepts requests that don't have these properties. Will there be an update to that sometime before they start being required in production on May 1? Will they start showing up in the API documentation?

Is there a better place I should be asking about this?

**Comment by AlexandrosMor** [comment]
Hello @raelyard 

I see that the [AccountHolderDetails](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/MarketPay/AccountHolderDetails.cs)
it is part of the api library. Could you be more specific which models are missing for the KYC implementation?

kind regards,
Alexandros 
Adyen

**Comment by raelyard** [comment]
Thank you @AlexandrosMor. Will check it out and certainly will be back in touch if there is anything else.
