### ISSUE TITLE
EditMode on HOP.GetOnboardingURL

### ISSUE THREAD

**Issue by glbotu2** [Adyen/adyen-dotnet-api-library#426]
Hi

We've been specifically instructed by one of the implementation team to set `editMode=true` as part of allowing users to "fix" their onboarding if they've made a mistake ([here in API Doc](https://docs.adyen.com/api-explorer/#/Hop/v6/post/getOnboardingUrl__reqParam_editMode)). We're using this SDK, but the option doesn't seem present. Any nearby plans to include it?

**Comment by AlexandrosMor** [comment]
Hello @glbotu2,

Please check this [pull request](https://github.com/Adyen/adyen-dotnet-api-library/pull/427) and let us know if it is fixes the issue for you

regards,
Alexandros
Adyen

**Comment by glbotu2** [comment]
HI @AlexandrosMor 

Yes, that's perfect thank you. Do you know what the turnaround time tends to be on the PR getting merged?

Thanks
