### ISSUE TITLE
PW-4567 Error sending crypto request with PosPaymentLocalApi

### ISSUE THREAD

**Issue by FFraterBizeta** [Adyen/adyen-dotnet-api-library#429]
Hello,

Using the "PosPaymentLocalApi" service and the method "TerminalApiLocal" the request message is not correctly encrypted and the server get back a bad request error. I think that the first argument type ("SaleToPOIMessage") of this method is wrong. I've tried replace the type "SaleToPOIMessage" with "SaleToPOIRequest" and it works fine.

**To Reproduce**
1. try to use "TerminalApiLocal" method with "PosPaymentLocalApi" service
2. see the error:  {
    "errors": [
        "At toplevel, field SaleToPOIRequest: Missing",
        "At toplevel: Missing"
    ]
}

**Desktop:**
 - OS: Windows 10
 - Version: 20H2 

**Additional context**
I've tried the package (via NuGet): version 6.1.0 and 7.0.0 but the behavior is the same.

**Comment by AlexandrosMor** [comment]
Hello @FFraterBizeta,

Could you send us how do you create the request ? 
It should be similar to [this example request](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen.Test/MockPosApiRequest.cs#L37)

**Comment by AlexandrosMor** [comment]
I see your point. We are going to investigate it and in the meantime you can use the method similar to [this test ](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen.Test/TerminalApiPosRequestTest.cs#L58)

**Comment by FFraterBizeta** [comment]
> I see your point. We are going to investigate it and in the meantime you can use the method similar to [this test ](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen.Test/TerminalApiPosRequestTest.cs#L58)

It works. I don't know that "SaleToPOIRequest" inherits from type "SaleToPOIMessage"
