### ISSUE TITLE
[PW-6194] Expose interfaces for services

### ISSUE THREAD

**Issue by johanssontobias** [Adyen/adyen-dotnet-api-library#430]
Hi Adyen,

Is there a reason why the services (Checkout, Recurring, etc.) are not currently exposed in an interface? 

```
public interface ICheckout
{
  Task<PaymentResponse> PaymentsAsync(PaymentRequest paymentRequest, RequestOptions requestOptions = null);
}

public class Checkout : AbstractService, ICheckout 
{
  ...
  ...
}
```

This would help with both dependency injection and testing purposes. 

Using Microsoft Dependency Injection
```
public void RegisterServices(IServiceCollection services)
{
  services.AddSingleton(new Client(...));
  services.AddScoped<ICheckout, Checkout>();
  services.AddScoped<IRecurring, Recurring>();
}
```
```
public class SomePaymentProvider
{
  private readonly ICheckout _checkout;

  public SomePaymentProvider(ICheckout checkout)
  {
    _checkout = checkout;
  }
}
```
This would make it much easier to mock the dependencies in unit tests. 
```
public class SomePaymentProviderTests
{
  [Test]
  public void SomeTest()
  {
    var checkout = new Mock<ICheckout>();
    checkout
      .Setup(c => c.PaymentsAsync(...))
      .ReturnsAsync(...);

    var somePaymentProvider = new SomePaymentProvider(checkout.Object());

    // Test stuff
  }
}
```

**Comment by AlexandrosMor** [comment]
Hello @johanssontobias,

We see the benefits to expose the services using interfaces and it would be a nice addition for the library. We are going to open an internal ticket for that but you are always welcome to open a pull request for this matter

kind regards,
Alexandros
Adyen

**Comment by jillingk** [comment]
Hi @johanssontobias,

Thanks for reaching out to us with this question. This library is currently next on our scope for the automation project. That means that we will start very soon with some big changes, where we will be sure to include an interface on the services. 

Best, Jilling
Adyen
