### ISSUE TITLE
Applepay and googlepay tokens are incorrect

### ISSUE THREAD

**Issue by Siggnja** [Adyen/adyen-dotnet-api-library#432]
**Describe the bug**
According to:
https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments
and
Release notes from web drop-in:
https://docs.adyen.com/online-payments/release-notes#nov-6th-2020

The token for apple pay and google pay should be `applePayToken` and `googlePayToken` respectively. Yet this library sets the values as `applepay.token` and `paywithgoogle.token`.

Am I missing something here? If I'm correct then I guess this is an issue that needs to be addressed straight away.

https://github.com/Adyen/adyen-dotnet-api-library/blob/7ed4360e7413677e942695e224f9e512c6b893a5/Adyen/Model/Checkout/DefaultPaymentMethodDetails.cs#L83

Here is the node type:
https://github.com/Adyen/adyen-node-api-library/blob/67cad90a222b6aaad5db1c9e09c0387d84c6d756/src/typings/checkout/applePayDetails.ts#L39

**Edit**

Another thing I noticed is the toString method needs some looking into. See the appending of values in the stringbuilder here:
https://github.com/Adyen/adyen-dotnet-api-library/blob/7ed4360e7413677e942695e224f9e512c6b893a5/Adyen/Model/Checkout/DefaultPaymentMethodDetails.cs#L115

**Comment by Siggnja** [comment]
@AlexandrosMor Have you had the chance to a take a look at this? Currently this looks like the reason for why we can't accept payments from Google pay and Apple pay via Adyen.

If this will take time to fix do you have a recommended workaround?

**Comment by AlexandrosMor** [comment]
Hello, 

Yes we are going to investigate it as soon as possible

regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello, 
Indeed we need to remove these parameters. You need to use the details classes for the payment methods. For applepay use the [ApplePayDetails.cs](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/Details/ApplePayDetails.cs) 
and for googlepay please use the [GooglePayDetails.cs](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/Details/GooglePayDetails.cs).

kind regards,
Alexandros

**Comment by JohannSig** [comment]
So, when making payments, we should do a check if the incoming "paymentMethod" object is applepay or googlepay related, convert it to ApplePayDetails or GooglePayDetails if so, and default to DefaultPaymentMethodDetails if not?

**Comment by AlexandrosMor** [comment]
The deserialization should be done by the library. Just use the [payments call ](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Service/Checkout.cs#L60)

**Comment by AlexandrosMor** [comment]
Hello @JohannSig, 

I would like to ask if the previous answer solved the issue for you so I could close the ticket. 

kind regards,
Alexandros
Adyen

**Comment by Siggnja** [comment]
@AlexandrosMor This solved the issue, closing the ticket is fine by me. Are you going to leave the parameters in this file as is?
Maybe it is worth stating this in the README or something that these files shouldn't be used...

**Comment by AlexandrosMor** [comment]
@Siggnja Do you mean in the [DefaultPaymentMethodDetails](https://github.com/Adyen/adyen-dotnet-api-library/blob/7ed4360e7413677e942695e224f9e512c6b893a5/Adyen/Model/Checkout/DefaultPaymentMethodDetails.cs#L83) ?

**Comment by Siggnja** [comment]
@AlexandrosMor Yes.
