### ISSUE TITLE
Issues with ForceEntryMode

### ISSUE THREAD

**Issue by vivekadvsol** [Adyen/adyen-dotnet-api-library#435]
Hi,

I have an issue implementing [MKE](https://docs.adyen.com/point-of-sale/enter-payment-manually?tab=codeBlockmanual_keyed_entry_1_2) (Manually enter payments). Please refer the [image](https://ibb.co/Jd6d9Lg).

```
'3c. MKE (Manual Key Entry) transaction
Dim myReq_Conditions As New Model.Nexo.TransactionConditions()
myReq_Conditions.ForceEntryMode = ForceEntryModeType.Keyed
```
The last line throws error "_Value of type ForceEntryMode cannot be converted to value of type ForceEntryMode()_". But it is an ENUM.

**Comment by AlexandrosMor** [comment]
Hello @vivekadvsol,

The ForceEntryMode is an array.  [`public ForceEntryModeType[] ForceEntryMode;` ](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Nexo/TransactionConditions.cs#L48) 
The following example is in c#, could you also try it? 
`
               var transactionConditions = new TransactionConditions
                {
                    ForceEntryMode = new ForceEntryModeType[] { ForceEntryModeType.Keyed }
                };
`

regards 
Alexandros
