### ISSUE TITLE
[PW-4684] Null reference exception with TerminalApiLocal and encryption credential details

### ISSUE THREAD

**Issue by FFraterBizeta** [Adyen/adyen-dotnet-api-library#437]
Dear Adyen,

I've noticed that TerminalApiLocal method throw a null reference exception (not handled) if terminal encryption parameters are not set up.

**To Reproduce**
1.  remove encryption parameters from terminal (via Adyen portal, on terminal,store or merchant side)
2. instance a PosPaymentLocalApi object with Config parameter
3. try to do a payment request with TerminalApiLocal method and EncryptionCredentialDetails parameter set
4. See error: ![image](https://user-images.githubusercontent.com/82388799/118103583-5ed21200-b3da-11eb-8a9b-534fd8c689a9.png)
5. Exception satck trace say:
 at Adyen.ApiSerialization.SaleToPoiMessageSecuredSerializer.ParseSaleToPoiMessageSecured(JToken 
 saleToPoiMessageSecuredJToken)
   at Adyen.ApiSerialization.SaleToPoiMessageSecuredSerializer.Deserialize(String saleToPoiMessageSecuredJSon)
   at Adyen.Service.PosPaymentLocalApi.TerminalApiLocal(SaleToPOIMessage saleToPoiRequest, EncryptionCredentialDetails 
 encryptionCredentialDetails)_

**Expected behavior**
A handled exception with code and message

**Desktop
 - OS: Windows 10 Pro 20H2
 - Visual Studio 2019
 - adyen-dot-net-api-library version 7

**Comment by AlexandrosMor** [comment]
Hello @FFraterBizeta, 

Thank for reporting this issue. For the local communication is mandatory to set the encryption credentials and indeed this could be handled with a custom exception at that level. We will open an internal ticket and  handle this as soon as possible. In addition, you could also open a pull request with the suggested code which we could merge to the main branch.

kind regards,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment]
Hello @FFraterBizeta,

The encryption credentials are required so the error makes sense. We are going to close this ticket and feel free to open a new one if you have further issues.

kind regards,
Alexandros
Adyen
