### ISSUE TITLE
Metadata object not sorted

### ISSUE THREAD

**Issue by FFraterBizeta** [Adyen/adyen-dotnet-api-library#448]
**Is your feature request related to a problem? Please describe.**
When I send metadata object in "PaymentRequest.SaleData.SaleToAcquirerData.Metadata", on Adyen payments portal metadata is not sorted. 

**Describe the solution you'd like**
I would like to see the metadata object in ascending or alphabetical order.

**Describe alternatives you've considered**
I would like to send my JSON object like value of dictionary, now Adyen terminal get back a "Failed validation" error in this mode

**Additional context**
Screenshot of payment result in Adyen portal
![image](https://user-images.githubusercontent.com/82388799/119984121-50325000-bfc1-11eb-819e-223e85430a7c.png)

My dictionary is :

[0], {Key="First key", Value="first value"}

[1], {Key="Second key", Value="second value"}

[2], {Key="Third key", Value="third value"}

[3], {Key="Fourth key", Value="fourth value"}

Thank you in advance.
Regards.

Filippo

**Comment by AlexandrosMor** [comment]
Hello @FFraterBizeta,

Indeed it is a helpful enchantment but at moment low priority. You can always open a pull request so we can review it and merge it

kind regards,
Alexandros
Adyen

**Comment by FFraterBizeta** [comment]
Hello @AlexandrosMor ,

I dont' have permissions to do it.

Best regards,
Filippo

**Comment by AlexandrosMor** [comment]
Hello @FFraterBizeta,

There is a guide here how to open a pull request on the  adyen-dotnet-api-library repository [here](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/CONTRIBUTING.md) 

kind regards,
Alexandros
Adyen
