### ISSUE TITLE
Missing MerchantReference on PaymentDetailsResponse

### ISSUE THREAD

**Issue by debski** [Adyen/adyen-dotnet-api-library#449]
Using latest version `MerchantReference` is missing on `PaymentDetailsResponse`. This makes it impossible to obtain the reference, even though it is returned in /payments/detail response (see image). This causes a lot of flows to not be working in our solution, and makes it impossible to use latest version.

![image](https://user-images.githubusercontent.com/6360624/120203090-9ee12380-c227-11eb-9c4d-f1b3d250dc5d.png)

**Comment by debski** [comment]
I have now also made a PR to include this field: #450

**Comment by AlexandrosMor** [comment]
Hello @debski 

Thank for opening the pull request. We are going to review it and merge it as soon as possible
Kind regards
Alexandros
Adyen
