### ISSUE TITLE
PayPalDetails.SubtypeEnum has invalid association with const values

### ISSUE THREAD

**Issue by sviatoslav-kuzmiak** [Adyen/adyen-dotnet-api-library#452]
**Describe the bug**
`PayPalDetails.SubtypeEnum` members are associated with the same value of 1. This makes the compiler to treat different enum values as the same. 

**Actual behavior**
`PayPalDetails.SubtypeEnum.SDK` is equal `PayPalDetails.SubtypeEnum.Redirect`

**Expected behavior**
`PayPalDetails.SubtypeEnum.SDK` should not be equal to `PayPalDetails.SubtypeEnum.Redirect`

**Screenshots**
![image](https://user-images.githubusercontent.com/54887917/120464988-d07bfb00-c39d-11eb-9d86-d6a2a7712879.png)

**Issue can be reproduced using**
 - dot-net-lib v6.1.0 and above

**Comment by AlexandrosMor** [comment]
Hello @sviatoslav-kuzmiak,

Thank you for spotting this. Indeed there is a mistake here the SDK and  Redirect are equal to 1. 
I will open a PR to fix it asap.

kind regards,
Alexandros
Adyen

**Comment by sviatoslav-kuzmiak** [comment]
Thanks for quick response.
For us it fixes the issue, since we were using `DefaultPaymentMethodDetails` before and now we want to switch to `PayPalDetails`. But I'm not sure if there any side effects for people who are using PayPalDetails at the moment.
