### ISSUE TITLE
SaleToPOIRequest - Missing PaymentRequest field 

### ISSUE THREAD

**Issue by gubowork** [Adyen/adyen-dotnet-api-library#454]
posPaymentLocalApi.TerminalApiLocal() 

Get the  error: 
 "AdditionalResponse": "errors=At%20SaleToPOIRequest%2c%20field%20PaymentRequest%3a%20Missing%0aAt%20SaleToPOIRequest%3a%20Missing&warnings=At%20SaleToPOIRequest.MessageHeader%2c%20field%20SecurityTrailer%3a%20Unexpected%0aAt%20SaleToPOIRequest.MessageHeader%2c%20field%20NexoBlob%3a%20Unexpected&note=Direct%20API%20REQUIRES%20payload%20crypto%20on%20live%2c%20cleartext%20allowed%20for%20testing%20only"

BUT the "PaymentRequest" field is clearly present in the request.

Btw. Your api can't handle this response ("Object reference error").
It would be nice to let the caller know this error message.

![adyenapi_missing_field](https://user-images.githubusercontent.com/5851673/120473382-4042b380-c3a7-11eb-9941-ad1338ae10ed.png)

Request:
{"SaleToPOIRequest":{"MessageHeader":{"MessageClass":"Service","MessageCategory":"Payment","MessageType":"Request","ServiceID":"02132512","SaleID":"deligo_device_guid","POIID":"P400Plus-804720154","ProtocolVersion":"3.0"},"PaymentRequest":{"SaleData":{"SaleTransactionID":{"TransactionID":"e0751b8b-86b6-46bd-8c2f-294ce47e8fea","TimeStamp":"2021-06-02T13:25:12"},"SaleToAcquirerData":"eyJhcHBsaWNhdGlvbkluZm8iOnsiYWR5ZW5MaWJyYXJ5Ijp7Im5hbWUiOiJhZHllbi1kb3RuZXQtYXBpLWxpYnJhcnkiLCJ2ZXJzaW9uIjoiNy4xLjAifX19","TokenRequestedType":"Transaction"},"PaymentTransaction":{"AmountsReq":{"Currency":"HUF","RequestedAmount":999.0},"TransactionConditions":{"DebitPreferredFlag":false}}}}}
Encrypted Request:
{"SaleToPOIRequest":{"MessageHeader":{"MessageClass":"Service","MessageCategory":"Payment","MessageType":"Request","ServiceID":"02132512","SaleID":"deligo_device_guid","POIID":"P400Plus-804720154","ProtocolVersion":"3.0"},"NexoBlob":"c/dNvhbhEBhkvxf3xOHqKj6hILhdJiaEMKuOlV8HJnrm6kM3PLtxT/zMlJhbqm5Ow0fyI1zZMUgV6MeGxH6s8LxME8MbhPTyJwvgi7mVlHhEivz5mgsgoAqX0MdPP8Ha9MNy5rLNKNV2gG/23SES/dIlDpKRBCzEva2rhBCfBWVtygIe65ZPOxpAaegRAjJqFBce0NoEnZLO3TafOnreHHOSikKMTGPzm15sMHy7i11V4WjWoXZoSKFvOsriK5nQ4v5u/IYVyh1BG1O7B0E/fD0C6hWjKpfm0dE5ujVhaSOfH9Gu1BGbOURTk1kDLk0A/TwcDmqSiG6uKTHS4rbMUicWLL2u8tyLeMfmKtIOoH9h8uV56eOd4A9iZzvQOMhp76hktEe5Y+KkaWxie5PsG5qgTHyG0Xe2QXZ35uSU/AhZGRe4dMy++eo+KsdN42859nsrsj1PhJjcX1VuCaN9ZM7UDTexd8mRqIpSfLLwEh1mOIdN2apX1Uj8mvvJsVGVSPII9PyTqvScLC6XPXySibLJnshk89CUMLAmZvFXGlebxAIwfRPtjrILZZrMTBDNUAwRBL7dtZ9eyVIZ9MWwNGHF/aUDxBqP8nnhrglcWCMPRcZ5O15GWu1kALXXHsXinxivkxdGI/s+62iVDJzgOPFyD/U4XJ19LjgHxun6GM+EgV8wgnyphlKmlmAU0wHC1k61rhuFL0AmZP3U6ulZxwdxz8KGIzlu/ag2HJg7QfpGDvTGjFGLhYNaADsgevP6og+MayyAnm/c5OvcX7SVsEZ4OjCA+NA0D5MnBp9ZqIrqdt42bioiKsoiTcCHDWskhuaBxySHuYef+rmq+YiKazJD5UwQzTknNVjqWlMxJSJipVokkik7nB51FOPyAbzBtFX/bZpSs4AAhYzfFzaxoQ==","SecurityTrailer":{"AdyenCryptoVersion":0,"KeyIdentifier":"DELIGO","KeyVersion":1,"Nonce":"RP5rtT+Fd9RRIakHcvuYdQ==","Hmac":"ThZKa2w8Ye4zKHn66NukA1TbSoBl01IodFeuJ3/KR2I="}}}
Response:
{ "SaleToPOIResponse": { "MessageHeader": { "MessageCategory": "Payment", "MessageClass": "Service", "MessageType": "Response", "POIID": "P400Plus-804720154", "ProtocolVersion": "3.0", "SaleID": "deligo_device_guid", "ServiceID": "02132512" }, "PaymentResponse": { "POIData": { "POITransactionID": { "TimeStamp": "2021-06-02T11:25:15.215Z", "TransactionID": "DbfJ001622633115005" } }, "Response": { "AdditionalResponse": "errors=At%20SaleToPOIRequest%2c%20field%20PaymentRequest%3a%20Missing%0aAt%20SaleToPOIRequest%3a%20Missing&warnings=At%20SaleToPOIRequest.MessageHeader%2c%20field%20SecurityTrailer%3a%20Unexpected%0aAt%20SaleToPOIRequest.MessageHeader%2c%20field%20NexoBlob%3a%20Unexpected&note=Direct%20API%20REQUIRES%20payload%20crypto%20on%20live%2c%20cleartext%20allowed%20for%20testing%20only", "ErrorCondition": "MessageFormat", "Result": "Failure" } } } }

![unhandled](https://user-images.githubusercontent.com/5851673/120474098-0de58600-c3a8-11eb-84c2-723fc595226f.png)

**Comment by AlexandrosMor** [comment]
Hello @gubowork,

Could you send us how do you create the request ? 
It should be similar to [this example request](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen.Test/MockPosApiRequest.cs#L37)

kind regards,
Alexandros
Adyen

**Comment by gubowork** [comment]
Hi!

Yes , the request generating code is copied out from Github.
I figured out that my terminal yesterday *accepted only unencrypted
messages*, (made a successful transaction),
but magically today is working normally (accept only encrypted messages) so
the api library works fine.

[image: image.png]

I would like to ask what is the exact windows store name to where I must
import the .cer file ?

[image: image.png]


Regards
Gabor

**Comment by gubowork** [comment]
Hi Alexandros!
 Sorry to Bother You, but I am facing another problem.
 After sending a sync PaymentRequest to the terminal (the display waits for
card input) , and waiting for the response, I sent an AbortRequest
transaction which returned a simple Bad request (403).
What I'm doing wrong? (Attached the real message below)

Thanks
Gabor


[image: image.png]

**Comment by AlexandrosMor** [comment]
Hello @gubowork,

For those issues about terminal functionality and payment flows you need to contact Adyen support. I can help you here with technical issues about the library 

kind regards,
Alexandros
Adyen
