### ISSUE TITLE
Adyen.HttpClient.HttpClientException: 'Web Exception' - SSL/TLS

### ISSUE THREAD

**Issue by tsantosSaphyr** [Adyen/adyen-dotnet-api-library#457]
Hi Adyen Team,

im facing this issue , every time i try to make a request a get the 
![image](https://user-images.githubusercontent.com/64142049/120823133-7ca01c00-c52d-11eb-8c34-82f3e66ddb81.png)

im following the getting start tutorial,  first i tried it using postman and it works fine, so i guess my apikey is right, but now that im trying to implement it on .net its not working.

my code:
![image](https://user-images.githubusercontent.com/64142049/120823528-e7515780-c52d-11eb-8712-5e357ac68f48.png)

**Comment by tsantosSaphyr** [comment]
I'm trying to generate de adyen link for payment

**Comment by tsantosSaphyr** [comment]
Hi everyone,
me and my friend figured out why the SSL/TLS error. It was because when we created the project it was created in a version of .net lower than 4.6.1 and the default TLS is not compatible with the version that needs to work for the request.

the solution for this is to put this line of code before the request or to use Adyen's lib

System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;


Please Adyen, insert this in your documentation, it can help a lot!

**Comment by AlexandrosMor** [comment]
Hello @tsantosSaphyr,

Thank you for opening this issue and letting us know.  In the [Readme](https://github.com/Adyen/adyen-dotnet-api-library#prerequisites) we added some info about the supported versions and indeed we are going to add more details based on your findings :)

kind regards,
Alexandros 
Adyen
