### ISSUE TITLE
[PW-4984] Add capture endpoint /payments/{paymentPspReference}/captures 

### ISSUE THREAD

**Issue by johanssontobias** [Adyen/adyen-dotnet-api-library#458]
Hi,

It looks like the SDK is missing [/payments/{paymentPspReference}/captures](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments/%7BpaymentPspReference%7D/captures). [CaptureAsync](https://github.com/Adyen/adyen-dotnet-api-library/blob/cc2fd4a7198ca7b005f7b59f4156ac2289942e67/Adyen/Service/Modification.cs#L58) is using the classic API integration which, according to the documentation, is no longer recommended. 

Do you have any plans to implement the Modification endpoints in Checkout in the SDK?

**Comment by johanssontobias** [comment]
Just saw in the [release notes](https://docs.adyen.com/online-payments/release-notes) that these endpoints were added just a few days ago. Thought they had existed longer since the documentation recommended them.

**Comment by AlexandrosMor** [comment]
Hello @johanssontobias,

Thank fo raising this issue. We are going to create an internal ticket to add these endpoints. It is always possible to open a pull request for this using our [contribution guide](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/CONTRIBUTING.md) and add the endpoints with the related unit tests

kind regards,
Alexandros
Adyen
