### ISSUE TITLE
 .Net Framework compatibility

### ISSUE THREAD

**Issue by deepu105** [Adyen/adyen-dotnet-api-library#460]
**Describe the bug**

Based on https://github.com/adyen-examples/adyen-dotnet-online-payments/issues/4

> When binding `state.data` to an `Adyen.Model.Checkout.PaymentRequest` object on .Net Framework 4.7.2 it gives the error `"Cannot create an instance of an interface. Object type 'Adyen.Model.Checkout.Details.IPaymentMethodDetails'."`. Apparently .net Core is ok binding this, but .net framework does not like binding to an interface. Is there an object that I should be using to bind `state.data` that I'm missing?

**Comment by AlexandrosMor** [comment]
Hello @camrontucker

I would like to ask if you are using this method for the payment request https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Service/Checkout.cs#L60

regards,
Alexandros 
Adyen

**Comment by AlexandrosMor** [comment]
Hello @camrontucker

Is the issue solved for you using the method above ? If yes then it would be nice to close this issue or please provide us  more information 

regards,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment]
Hello @camrontucker
I will close that issue during inactivity. If you have further question please do not hesitate to contact us

regards,
Alexandros
Adyen

**Comment by persyl** [comment]
Me having the same issue and cant find a solution.
Problem is using PaymentRequest as a parameter to action method in .Net Core / .Net5 when posting from frontend.
Like this:
```
[HttpPost]
[Route("Pay")]
public async Task<IActionResult> Pay([FromBody] PaymentRequest paymentRequest) {
.....
}

```

Even though I can see this attribute on the PaymentMethod-property in PaymentRequest-class:

```
[DataMember(Name = "paymentMethod", EmitDefaultValue = false)]
[JsonConverter(typeof(PaymentMethodDetailsConverter))]
public IPaymentMethodDetails PaymentMethod { get; set; }
```
