### ISSUE TITLE
Nexo Service: crypto error (9)

### ISSUE THREAD

**Issue by matthias-hoste** [Adyen/adyen-dotnet-api-library#464]
**Describe the bug**
Exactly as the title states, a crypto error(9)

**To Reproduce**
It happens whenever a local payment request is used

**Expected behavior**
It should allow the payment to go through

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser .Net application

**Additional context**
Whenever I try to make a payment request it fails, I've double and triple checked the encryption details and they all match up.
Is there maybe a new adyencryptoversion?

**Comment by AlexandrosMor** [comment]
Hello @matthias-hoste,

Testing the local communication works fine. The error message states that it is most likely the encryption credentials are not correct. 
Could you check the encryption credentials in the customer area and make sure that the terminal configuration is up to date? 

regards
Alexandros
Adyen

**Comment by matthias-hoste** [comment]
Hi @AlexandrosMor 
Thanks for the fast reply, sadly I had to wait a lot to receive that info.
The credentials are set correctly in both the customer panel and on the driver using it.
I assume you update the terminal configuration by rebooting it and we've tried that too with little success

**Comment by AlexandrosMor** [comment]
Hello @matthias-hoste,

Update the terminal config is an action from the terminal admin menu. Rebooting the terminal is not enough. 

 regards
Alexandros
Adyen

**Comment by AlexandrosMor** [comment]
Hello @matthias-hoste,

Is the issue fixed for you ?

 regards
Alexandros
Adyen

**Comment by matthias-hoste** [comment]
Hi @AlexandrosMor 
Yes this was fixed exactly the way you suggested. It took my collegues a while to try it out.
Thank you for your help!
