### ISSUE TITLE
Support DsTransID and ThreeDSVersion in ThreeDSecureData class

### ISSUE THREAD

**Issue by zeroClearAmerican** [Adyen/adyen-dotnet-api-library#469]
**Is your feature request related to a problem? Please describe.**
According to [this Adyen guide](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce/3d-secure/other-3ds-flows/authorize-mpidata) for 3DS authorizations with MPI data, the parameters _dsTransID_ and _threeDSVersion_ are supported for 3DS version 2 payments, however these parameters are not part of the **ThreeDSecureData** class in the .NET library.

**Describe the solution you'd like**
Add the parameters _ThreeDSVersion_ and _DsTransID_ to the **ThreeDSecureData** class.

**Comment by AlexandrosMor** [comment]
Hello @zeroClearAmerican,

Thank you for contacting us, I see that the [ThreeDSecureData](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/ThreeDSecureData.cs) includes both  [dsTransID](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/ThreeDSecureData.cs#L180)
and [threeDSVersion](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/ThreeDSecureData.cs#L194)

Do you maybe use an older version ? 

kind regards,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment]
Hello @zeroClearAmerican,

I will close this issue as there is no development to be done. If you have more questions please open a new issue and we are going to check it 

kind regards,
Alexandros
Adyen

**Comment by blueohsix** [comment]
Hello, @AlexandrosMor! 
The ThreeDSecureData model mentioned by @zeroClearAmerican is here: https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/ThreeDSecureData.cs

The above model does not include ThreeDSVersion and DsTransID and it should, according to the linked guide.
