### ISSUE TITLE
Compatibility with Android 4.0.0 beta with Adyen SDK 5.6.0 .NET and call ADYEN API V51

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-dotnet-api-library#472]
Hello,

I begin migration to 4.0.0 beta Android and the first test i get 422 status error.

Our API Team use .NET Framework with Adyen SDK version 5.6.0 and call Adyen API V51. 

My question is : Adyen SDK version 5.6.0 and call Adyen API V51 compatible with 4.0.0 03 beta Android ?

Thanks,

**Comment by AlexandrosMor** [comment]
Hello @badredaha,

The adyen-dotnet-api-library is tested and developed mostly on windows environment. As a result, we do not have information about the compatibility with Android or any known issues with Android versions.  
There is always the possibility to contribute to the code based on the guide [here](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/CONTRIBUTING.md) 

regards,
Alexandros
Adyen
