### ISSUE TITLE
[PW-5243] StoreDetails for AccountHolderDetails type is missing

### ISSUE THREAD

**Issue by HeadOnSebastian** [Adyen/adyen-dotnet-api-library#480]
We need to add stores to our existing sub-merchants to use platform for pos and work with terminal. We wanted to do this according to the following documentation to the account holders: https://docs.adyen.com/platforms/platforms-for-pos#add-store

Unfortunately the properties for the StoreDetails are currently missing in the AccountHolderDetails.

Please add support to add stores by the CreateAccountHolder and UpdateAccountHolder request.

**Comment by AlexandrosMor** [comment]
Thank you for raising this issue. We created an internal ticket and we are going to add support to add stores. You could always also contribute to the library based on the [contribution guide](https://github.com/Adyen/adyen-dotnet-api-library/blob/d359dd759b11d77731ccd8a7b4e3a0c680547e99/CONTRIBUTING.md).

kind regards
Alexandros
Adyen

**Comment by akScript** [comment]
@AlexandrosMor was this issue fixed, is the StoreDetails property present on the AccountHolderDetails model?
