### ISSUE TITLE
Error deserializing an ACCOUNT_HOLDER_CREATED Platform Notification

### ISSUE THREAD

**Issue by justinpatten** [Adyen/adyen-dotnet-api-library#486]
The JSON that we receive from the Platform (MarketPay) notification for an ACCOUNT_HOLDER_CREATED event is lacking the pspReference inside of the "contents" property, but it is present on the root [AccountHolderCreateNotification](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/MarketPay/Notification/AccountHolderCreateNotification.cs). 

The [CreateAccountHolderResponse](https://github.com/Adyen/adyen-dotnet-api-library/blob/d359dd759b11d77731ccd8a7b4e3a0c680547e99/Adyen/Model/MarketPay/CreateAccountHolderResponse.cs#L94) class is throwing an exception due to that property being null and stopping our endpoint from processing the notification. I reviewed the Java SDK and it doesn't appear that they are throwing an exception. 

Is there an alternative constructor that can be added to the class for deserialization or remove the null check? It is currently blocking us from using the models in the SDK.

**Comment by AlexandrosMor** [comment]
Hello @justinpatten,

Thank you for mentioning this issue. We are going to pick it up as soon as possible.

kind regards,
Alexandros
Adyen
