### ISSUE TITLE
Internal server error 503

### ISSUE THREAD

**Issue by matthias-hoste** [Adyen/adyen-dotnet-api-library#489]
**Describe the bug**
Upon sending a saleToPoiRequest the terminal responds with "Internal Server Error" status code 503.

**Expected behavior**
No internal error and either success or an error on my side.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser None
 - Version None

**Additional context**

**Comment by AlexandrosMor** [comment]
Hello @matthias-hoste, 

Thank you for contacting us, I have some questions for the integration. Are you using local or cloud communication ? Could you send us a code snippet how do you build the client and finally is the websocket option enabled on the terminal side ?

kind regards,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment]
Hello @matthias-hoste,

Following up for this issue did you manage to move forward with the integration ? 

kind regards,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment]
Hello @matthias-hoste,

We are going to close this issue as we do not have enough details to investigate it further. Feel free to open another ticket if you have further questions 

kind regards,
Alexandros
Adyen
