### ISSUE TITLE
[PW-6630]"PhoneNumber" property missing on "AccountHolderDetails" class in .NET SDK

### ISSUE THREAD

**Issue by adam-jeffery** [Adyen/adyen-dotnet-api-library#490]
The .NET SDK (7.2.0) is missing the "PhoneNumber" property on the "AccountHolderDetails" class. Currently while a phone number is submitted using the "FullPhoneNumber" property it is never populated in responses. However, the "PhoneNumber" property is returned in responses but cannot be mapped as it is missing in the .NET SDK but is present in the Java SDK.

**Comment by AlexandrosMor** [comment]
Hello @adam-jeffery, 

This field is removed and the `PhoneNumber` is accessible through the `FullPhoneNumber`. Is the `PhoneNumber` part of the response? Could you send us an example? 

kind regards,
Alexandros
Adyen
