### ISSUE TITLE
[PW-5598]Cannot deserialize ACCOUNT_HOLDER_STATUS_CHANGE notification into AccountHolderStatusChangeNotification object

### ISSUE THREAD

**Issue by HeadOnSebastian** [Adyen/adyen-dotnet-api-library#499]
We receive ACCOUNT_HOLDER_STATUS_CHANGE from adyen which we cannot deserialized into AccountHolderStatusChangeNotification class. This occurs because the _events_ of the _oldStatus_ are empty. So we end in a InvalidDataException "executionDate is a required property for AccountEvent and cannot be null" from the AccountEvent when we try to deserialize the json string.

It should be possible to deserialize the notification json strings received from Adyen into the corresponding object.

kind regards,
Sebastian

**Json-Notification-Content Example:**
`{
	"eventDate": "2021-09-23T15:25:55+02:00",
	"eventType": "ACCOUNT_HOLDER_STATUS_CHANGE",
	"executingUserKey": "Status Update",
	"live": "false",
	"pspReference": "123456789",
	"content": {
		"accountHolderCode": "1234",
		"oldStatus": {
			"status": "Active",
			"processingState": {},
			"payoutState": {
				"allowPayout": "false"
			},
			"events": []
		},
		"newStatus": {
			"status": "Active",
			"processingState": {
				"disabled": "false",
				"processedFrom": {
					"currency": "EUR",
					"value": 1
				},
				"tierNumber": 1
			},
			"payoutState": {
				"allowPayout": "false",
				"disabled": "false"
			},
			"events": [
				{
					"AccountEvent": {
						"event": "InactivateAccount",
						"executionDate": "2021-10-23T15:25:55+02:00",
						"reason": "Processed more than EUR 0.01 or equivalent, deadline triggered"
					}
				}
			]
		},
		"reason": "Account holder has been updated"
	}
}`

**Comment by AlexandrosMor** [comment]
Hello @HeadOnSebastian,

Thank you for raising this issue. We created an internal ticket and we are going to pick this issue as soon as possible.

kind regards,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment]
Hello @HeadOnSebastian,

Could you please test this pull request if it fixes the issue for you ?

kind regards,
Alexandros
Adyen
