### ISSUE TITLE
storeName is missing in the FieldNameEnum

### ISSUE THREAD

**Issue by HeadOnBenni** [Adyen/adyen-dotnet-api-library#504]
Hi everybody,

will implementing the adyen API I noticed that the storeName is missing in the FieldNameEnum. You can reproduce this Bug when you try to add a store and the store name contains a invalid char like the @ symbol. When you try do deserialize the response with the FieldNameEnum you will get a exception.

Thanks for your help

Error converting value "storeName" to type 'System.Nullable`1[Adyen.Model.MarketPay.FieldType+FieldNameEnum]'. Path 'invalidFields[0].fieldType.fieldName'

**Comment by AlexandrosMor** [comment]
Hello @HeadOnBenni 
I opened a pr with the missing fields. You could test it before we merge it :)

regards,
Alexandros
Adyen

**Comment by HeadOnBenni** [comment]
Hi @AlexandrosMor ,

I had a quick look at the change and it should fit like this from my point of view. Unfortunately, I do not currently have the capacity to test it in detail. Until when do you think that the changes will go live. Then I can set up an automatic test on our test system to check it. 

Thanks for the implementation and your help!
