### ISSUE TITLE
Problem with specific paymentMethod in version 8

### ISSUE THREAD

**Issue by michalwawa** [Adyen/adyen-dotnet-api-library#505]
Hello

After uprading version to 8, I have a problem with for example dotpay paymentmethod in dropin.

![image](https://user-images.githubusercontent.com/92430838/137099658-0f9407a6-53dd-44d2-916b-593d45a560e4.png)

Before upgrading i had a list of available banks etc, after there is nothing in dropdown. When i downgrade my version to 7.3 everything is working ok

**Comment by AlexandrosMor** [comment]
Thanks for mentioning that issue. We are going to investigate it and make a release some soon as possible

**Comment by michalwawa** [comment]
Hello @AlexandrosMor 
I downloaded code from your PR and checked it. Everything is working right now and dropdown is filled with options. Right now im waiting for release this :)

Thanks
