### ISSUE TITLE
[PW-5676] Fee is missing in Adyen.Model.MarketPay.Transaction.TransactionStatusEnum

### ISSUE THREAD

**Issue by michalwawa** [Adyen/adyen-dotnet-api-library#506]
Hello

After upgrading to version 8 i got an error when calling FundService and method AccountHolderTransactionList.

Error message:
`Error converting value "Fee" to type System.Nullable1[Adyen.Model.MarketPay.Transaction+TransactionStatusEnum]. Path accountTransactionLists[0].transactions[12].transactionStatus, line 1, position 5501.`

**Comment by AlexandrosMor** [comment]
Hello @michalwawa,

I opened a pull request that fix that issue. Could you please check if this solves the issue for you ? 

 kind regards,
Alexandros
Adyen
