### ISSUE TITLE
captureDelayCharge field should be Nullable<int> in CreatePaymentSessionRequest

### ISSUE THREAD

**Issue by wzpyh** [Adyen/adyen-dotnet-api-library#510]
**To Reproduce**
We are using Adyen .net sdk (8.0) to set captureDelayCharge to 0 but it seems not being serialized into the JSON request ,
this causing issues when setting the checkout account with "manual capture" and we want the payment to be captured immediately

the type of captureDelayCharge should be (int?) instead of (int) in CreatePaymentSessionRequest?

P.S: I set it to 1 and it works. The charge amount will be settled after 1 hour.

**Comment by AlexandrosMor** [comment]
Hello @wzpyh,

We cannot find the captureDelayCharge  in [CreatePaymentSessionRequest](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/CreateCheckoutSessionRequest.cs)  Could you send us more details?

**Comment by wzpyh** [comment]
Hi @AlexandrosMor  I am back on the project again :) . 
it is the field captureDelayHours on Adyen.Model.Checkout.CreateCheckoutSessionRequest  which I think the type should be int? not int

**Comment by AlexandrosMor** [comment]
Hey @wzpyh, 

Could you explain us what issues is this field causes ? Is it possible to set it in lower number ? 

kind regards
Alexandros

**Comment by wzpyh** [comment]
> Hello @wzpyh,
> 
> We cannot find the captureDelayCharge in [CreatePaymentSessionRequest](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/CreateCheckoutSessionRequest.cs) Could you send us more details?
> 
> regards, Alexandros Adyen



> Hey @wzpyh,
> 
> Could you explain us what issues is this field causes ? Is it possible to set it in lower number ?
> 
> kind regards Alexandros

when the merchant account set Capture to "Manual" on Dashboard
if not touching captureDelayCharge , then the transaction will be captured immediately as the type of field is Integer and not nuallble and it will pass 0 in the JSON Data.
assign captureDelayCharge to 0 is doing the same thing.

if it is Nullable and not assigning any value into it , then this field wont show in Raw JSON request , in this case , the transaction will not be captured as the merchant account has set to "Manual"

**Comment by AlexandrosMor** [comment]
Hello @wzpyh,

It looks like that the `captureDelayCharge`  is not part of the `CreatePaymentSessionRequest` and part Adyen's open api specs. 

kind regards,
Alexandros
Adyen
