### ISSUE TITLE
Cant find refund methods

### ISSUE THREAD

**Issue by michalwawa** [Adyen/adyen-dotnet-api-library#515]
I do not know if this is a bug, but reffering to information on .net library project, .net dll is supporting payments service which should include Refund methods. I cant find any of this methods on Payments(client) service. Am i missing something ? Is there any possibility to make refund using .net api ?

**Comment by AlexandrosMor** [comment]
Hello @michalwawa,

yes it is possible to make a refund.  You can use the [refund method](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Service/Modification.cs#L79) you could also check the 
 [docs](https://docs.adyen.com/api-explorer/#/Payment/v68/post/refund)
kind regards,
Alexandros
Adyen
