### ISSUE TITLE
TokenDetails removed in PR related to 7.2 release

### ISSUE THREAD

**Issue by johanssontobias** [Adyen/adyen-dotnet-api-library#517]
Hi,

It appears TokenDetails were removed from [RecurringDetail](https://github.com/Adyen/adyen-dotnet-api-library/pull/438/files#diff-c8f40e7b729a280dd3599b94be9562f25163ca1284940c3df4e085ffd0022502) as part of PR https://github.com/Adyen/adyen-dotnet-api-library/pull/438. This information, however, is still sent through [/listRecurringDetails](https://docs.adyen.com/api-explorer/#/Recurring/v68/post/listRecurringDetails).

If I make a request directly to that endpoint, using PayPal or Klarna, I get tokenDetails in the response. This applies to version 25, 49 and 68 of that endpoint. But in the SDK that information has been removed. Why was that change made? Can you please re-add TokenDetails to the SDK?

Example response making a request directly to https://pal-test.adyen.com/pal/servlet/Recurring/v68/listRecurringDetails

```json
{
    "creationDate": "2021-10-20T10:28:24+02:00",
    "details": [
        {
            "RecurringDetail": {
                "contractTypes": [
                    "ONECLICK",
                    "RECURRING"
                ],
                "creationDate": "2021-10-20T10:28:43+02:00",
                "firstPspReference": "862634718451663E",
                "paymentMethodVariant": "klarna_paynow",
                "recurringDetailReference": "841634718504679B",
                "tokenDetails": {
                    "tokenData": {
                        "klarnapayments.country": "SE",
                        "klarnapayments.txVariant": "klarna_paynow",
                        "klarnapayments.shopperEmail": "youremail@email.com",
                        "klarnapayments.tokenId": "604ad79c-387a-4778-8b9b-a6b40f024be0"
                    },
                    "tokenDataType": "KlarnaPayments"
                },
                "variant": "klarna_paynow"
            }
        }
    ],
    "shopperReference": "shopper_iMpVrFx3D1"
}
```

/ Tobias

**Comment by johanssontobias** [comment]
TokenDetails is still part of Java SDK which appears to use v. 49.

https://github.com/Adyen/adyen-java-api-library/blob/21ae8bf5eb16a2375333da405f3b79cdbd431fa1/src/main/java/com/adyen/model/recurring/RecurringDetail.java#L80

**Comment by AlexandrosMor** [comment]
Hello @johanssontobias, 

I see your point. We will fix it as soon as possible. In the meantime feel free to open a pr so we could review it and add it with the next release.

Regards,
Alexandros
Adyen
