### ISSUE TITLE
[PW-5816]shareholderType field is missing in MarketPay.ShareholderContact

### ISSUE THREAD

**Issue by wzpyh** [Adyen/adyen-dotnet-api-library#520]
Version: V8.0.0
API Use : createAccountHolder
Issue : shareholderType field is missing in MarketPay.ShareholderContact and shareholderType is mandatory field in this api.

shareholderType 
Specifies how the person is associated with the account holder.

Possible values:

Owner: Individuals who directly or indirectly own 25% or more of a company.

Controller: Individuals who are members of senior management staff responsible for managing a company or organization.

**Comment by AlexandrosMor** [comment]
Hello @wzpyh,

Thank you for raising this issue. We are going to update the models as soon as possible.

kind regards,
Alexandros
Adyen

**Comment by dan-drews** [comment]
In my latest testing, this field seems to be required on the /createAccountHolder endpoint (I receive errors if it's not provided). However, the documentation on Adyen's website do not indicate this is required.

Is this a mistake that it is required, or is it mistakenly just not flagged as required in the documents?
