### ISSUE TITLE
BrowserInfo has required ctor values, but shouldn't have according to docs

### ISSUE THREAD

**Issue by mhagendoorn-9292** [Adyen/adyen-dotnet-api-library#521]
**Describe the bug**
There's a check in the ctor of [Adyen.Model.Checkout.BrowserInfo](https://github.com/Adyen/adyen-dotnet-api-library/blob/7ed4360e7413677e942695e224f9e512c6b893a5/Adyen/Model/Checkout/BrowserInfo.cs) to see if values are missing. However, according to your own [examples shown here](https://docs.adyen.com/online-payments/3d-secure/redirect-3ds2-3ds1/ios-drop-in#make-a-payment) this shouldn't be the case, you should just be able to submit with a payload only. It's the exact same issue as in #77, but only a different model and 2 years later. 

**Expected behavior**
Being able to use BrowserInfo without submitting the ctor values

**Comment by AlexandrosMor** [comment]
Hello @mhagendoorn-9292,

Thank you for raising this issue. We are going to update the models as soon as possible. 

kinds regards
Alexandros

**Comment by darioflorz** [comment]
Hi @AlexandrosMor,

What is the status of this issue. I'm having the same problem but with Google Pay Drop-in integration https://docs.adyen.com/payment-methods/google-pay/android-drop-in#google-pay-android.

Which parameters are actually required?

Regards
Dario

**Comment by jillingk** [comment]
Hi @darioflorz and @mhagendoorn-9292,

Little update, the docs now tell us that _browserInfo_ is required with all the values. Just thought I'd let you guys know! If there is anything else I can help you with please do let me know.

Best, Jilling
Adyen
