### ISSUE TITLE
"JobTitle" property missing on "ShareholderContact" class in .NET SDK

### ISSUE THREAD

**Issue by aastovas** [Adyen/adyen-dotnet-api-library#530]
**Describe the bug**
To update an account holder, I am looking at documentation https://docs.adyen.com/api-explorer/#/Account/v5/post/updateAccountHolder
I see that in the request object, we can specify an array of ShareholderContact objects.
Each ShareholderContact  can define a jobTitle property.
However, this property is missing.

**To Reproduce**
Check class ShareholderContact : 
https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/MarketPay/ShareholderContact.cs

**Expected behavior**
ShareholderContact must hold the property JobTitle.

Something like:

```
/// <summary>
/// Job title of the person. Required when the shareholderType is Controller.
/// </summary>
/// <value>The job title of the person.</value>
[DataMember(Name="jobTitle", EmitDefaultValue=false)]
public string JobTitle { get; set; }
```

**Comment by aastovas** [comment]
It seems that shareholderType is also missing.

**Comment by jillingk** [comment]
Hi @aastovas,

I'm closing this ticket as this issue has been solved with newer updates of the library. If you have any other questions or remarks feel free to do so!

Best, Jilling
Adyen
