### ISSUE TITLE
Cannot deserialize Platform notification webhook models (even with APIVersion: 6) - dotnetAPI

### ISSUE THREAD

**Issue by MortenBLN** [Adyen/adyen-dotnet-api-library#531]
**Describe the bug**
Hello, I am having some trouble implementing the Platform Notifications for our dotnet project (similar to Issue 499). I setup the notifications (And yes, I am using APIVersion: 6), following the guides online (https://docs.adyen.com/platforms/configure-notifications#create-a-notification-configuration). Our route accepts a "AccountHolderCreateNotification.cs" for the same notification. But there are errors. It does not matter if I use the code provided by the AdyenAPIExplorer or an actual message I received when I accepted an Object on the route. 

Error with the dummy data from adyen (https://docs.adyen.com/api-explorer/#/NotificationService/v6/post/ACCOUNT_HOLDER_CREATED): 

Each parameter in constructor 'Void .ctor(EventEnum, System.Nullable`1[System.DateTime], System.String)' on type 'Adyen.Model.MarketPay.AccountEvent' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. The match can be case-insensitive.

Error with an actual adyen ACCOUNT_HOLDER_CREATED webhook notification:

System.IO.InvalidDataException: events is a required property for AccountHolderStatus and cannot be null at Adyen.Model.MarketPay.AccountHolderStatus..ctor(List`1 events, AccountPayoutState payoutState, AccountProcessingState processingState, StatusEnum status, String statusReason

--> Both return a 500; it seems like there is some problem with the AccountEvent class

There are also other issues with other notifications/models.

So I tried to accept an object (just for testing - we are using model binding) and to pass that object to the NotificationHandler.cs
That also is returning some errors, as (for example) the Object which is sent does not include the PSPReference in the {Content}, the NotificationHandler is looking for. 

 
**To Reproduce**
1. Create a notification for platforms
{
  "configurationDetails": {
    "active": true,
    "description": "createAccountHolder",
    "apiVersion": 6,
    "eventConfigs": [
      {
        "eventType": "ACCOUNT_HOLDER_CREATED",
        "includeMode": "INCLUDE"
      }
    ],
    "notifyURL": ".../OurRoute",
    "sslProtocol": "TLSv12"
  }
}

2. create an account holder/use the test data from https://docs.adyen.com/api-explorer/#/NotificationService/v6/post/ACCOUNT_HOLDER_CREATED by creating a post request to your route 

**Expected behavior**
return a HTTP Code 200 with the message [accepted]

Thanks

**Comment by MortenBLN** [comment]
Another example: The KYCCheckStatusData.Type (in the ACCOUNT_HOLDER_CREATED webhook) accepts among others "IDENTITYVERIFICATION", but "IDENTITY_VERIFICATION" is being sent.

**Comment by MortenBLN** [comment]
So I tested all the calls now. Seems like those are throwing errors:


ACCOUNT_HOLDER_CREATED
ACCOUNT_HOLDER_UPDATED
ACCOUNT_HOLDER_VERIFICATION
ACCOUNT_HOLDER_STATUS_CHANGE

The rest is working fine with the test data

**Comment by erlinghi** [comment]
We have the same problem.
