### ISSUE TITLE
Missing SignatoryContact element on BusinessDetail

### ISSUE THREAD

**Issue by aastovas** [Adyen/adyen-dotnet-api-library#532]
**Describe the bug**
The API https://docs.adyen.com/api-explorer/#/Account/v5/post/createAccountHolder accepts as input parameters accountHolderDetails.businessDetails.signatories

However, in the .NET SDK this field is missing.

The actual model object SignatoryContact is missing from Adyen.Model.MarketPay

**Comment by AlexandrosMor** [comment]
Hello @aastovas,

I opened a pull request with the updated models for AccountService v5. Could you please check if this pr fixes the issue for you ?

kind regards,
Alexandros
Adyen

**Comment by aastovas** [comment]
Hi Alexandros,
I went through the PR and it looks good to me, it's now aligned with the documentation (it even has the UltimateParentCompany now 👍).
Thanks so much for this!
Best regards,
Alex

**Comment by aastovas** [comment]
Hi Alexandros,
I will open another issue regarding signatories, because the property signatoryCode is missing when we want to upload a document for KYC validations (POST /uploadDocument).
Best regards,
Alex
