### ISSUE TITLE
Missing SignatoryCode field on Adyen.Model.MarketPay.DocumentDetail

### ISSUE THREAD

**Issue by aastovas** [Adyen/adyen-dotnet-api-library#535]
**Describe the bug**
When uploading a document for validation through the API **POST /uploadDocument**, the DocumentDetail object of the request has missing property **signatoryCode** although the documentation for v5 and v6 of the API defines it.
See https://docs.adyen.com/api-explorer/#/Account/v5/post/uploadDocument

**Expected behavior**
DocumentDetail must have a property called SignatoryCode of type string as stated in the documentation:
The Adyen-generated signatoryCode to which the document must be linked.

**Comment by AlexandrosMor** [comment]
Hello @aastovas 

The issue with the `SignatoryCode` is fixed on the #532 right ?

kind regards,
Alexandros
Adyen

**Comment by aastovas** [comment]
Hi Alexandros,
The issue was fixed for BusinessDetail model when we wanted to create an account holder (and thank you for that!).
This time, the issue is with DocumentDetail model when user wants to upload a document for validation (two separate data models).
Best regards,
Alex

**Comment by AlexandrosMor** [comment]
Hello @aastovas
  
We fixed it in #538 and we are going to make a release as soon as possible. 
Best regards,
Alexandros
Adyen
