### ISSUE TITLE
[PW-6739]Add properties to KYCVerificationResult: legalArrangements, legalArrangementsEntities, payoutMethods, signatories, ultimateParentCompany, verificationProfile

### ISSUE THREAD

**Issue by scottpantall** [Adyen/adyen-dotnet-api-library#539]
**Is your feature request related to a problem? Please describe.**
The v6 `getAccountHolder` API endpoint (https://docs.adyen.com/api-explorer/#/Account/v6/post/checkAccountHolder) includes more KYCVerificationResult properties than the ones that exist in this library (https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/MarketPay/KYCVerificationResult.cs).

**Describe the solution you'd like**
Add the legalArrangements, legalArrangementsEntities, payoutMethods, signatories, ultimateParentCompany, verificationProfile properties to the KYCVerificationResult and add all related classes for those properties.

**Comment by jillingk** [comment]
Hi @scottpantall,

Thanks for reaching out to us. I created an internal ticket to add the properties to the library. If you would like to speed up this process consider[ contributing](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/CONTRIBUTING.md) and create a PR. 

Best, Jilling
Adyen

**Comment by jillingk** [comment]
Hi @scottpantall,

Just a quick FYI that we updated the models! Apologies for the delay.

Best, Jilling
Adyen
