### ISSUE TITLE
Dictionary equals problem

### ISSUE THREAD

**Issue by kripliki** [Adyen/adyen-dotnet-api-library#546]
Hello, during unit test, Iam getting error ...

invocation failed with mock behavior Strict.
All invocations on the mock must have a corresponding setup.

from further investigation, it is caused because AdditionalData object

https://github.com/Adyen/adyen-dotnet-api-library/blob/e72ce78f91c4a938e071cf1b9346077f1b32d0d4/Adyen/Model/Checkout/PaymentRequest.cs#L885

it looks like two Dictionary object are not equal like "Equal"

Best

Petr Hrabec

**Comment by AlexandrosMor** [comment]
Hello @kripliki,

Could you please let us know which unit test is failing? On the repository's pipe line the tests are passing correct 

kind regards,
Alexandros
Adyen

**Comment by kripliki** [comment]
Hello, @AlexandrosMor ,

I didnt fully describe where this error is occuring. It is my unit test in my application. Basically it has nothing to do with tests in general, this is just the place, where I am facing this Equal problem.

The main point is, that you are overriding Equals method with your own implementation. Every property is compairing by basic Equals method, which should compare values of two "simple" objects, like int, bool ...

In case of dictionaries, Equals method is not compairing values of each key value pair, but probably something like reference.
In this case, two different PaymentResponse instances cannot by equal when they contains not null AdditionalData dictionary.

The equality of two dictionaries is described for example here https://stackoverflow.com/questions/37180810/compare-equality-of-two-objects-based-on-dictionaries

Best

Petr Hrabec

**Comment by AlexandrosMor** [comment]
Hello @kripliki,

The models are autogenerated and we are working on the templates to fix the helper methods including equals. In the meantime you could use your own implementation of `equals`.

kind regards,
Alexandros
Adyen
