### ISSUE TITLE
Issues with 3DS1 authentication

### ISSUE THREAD

**Issue by AndreaGhisa1** [Adyen/adyen-dotnet-api-library#547]
**Describe the bug**
For 3DS1 authentication the **recurring.recurringDetailReference** and **recurring.shopperReference** values are missing from additional data parameter response for a stored payment method. This problem does not occur with Basic cards or 3DS2 cards.

**To Reproduce**
1. Make a transaction using a stored payment method for 3DS1 card. 
2. Make a call to see the details of the transaction.

**Expected behavior**
recurring.recurringDetailReference and recurring.shopperReference should be returned in "additionalData".

**Screenshots**
![adyenResponse](https://user-images.githubusercontent.com/97953166/149929688-c01e6a2d-8cb4-4f67-96bd-7255211474cc.PNG)

**Additional context**
I'm using using:
1.	Adyen NuGet version 8.0.1
2.	Web Components/Drop-in v5.3.1
3.	Checkout API V68

**Comment by AlexandrosMor** [comment]
Hello @AndreaGhisa1 
The [addtionaldata](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/PaymentResponse.cs#L185) is key value pair so the library is not parsing any data. Please test if the response json contains those values.  If not then contact the Adyen's support team. 

Kind regards,
Alexandros
Adyen

**Comment by AndreaGhisa1** [comment]
Hi @AlexandrosMor thank you for your response. I've opened a ticket to support for this problem.
