### ISSUE TITLE
Strong name signing of assemblies

### ISSUE THREAD

**Issue by Tasteful** [Adyen/adyen-dotnet-api-library#548]
In [#405](https://github.com/Adyen/adyen-dotnet-api-library/pull/405) the strong name signing was added and marked as included in the 7.0.0 release. 
When the [#433](https://github.com/Adyen/adyen-dotnet-api-library/pull/433) was merged into the 7.1.0 release the changes [reverted](https://github.com/Adyen/adyen-dotnet-api-library/pull/433/files#diff-626f3c84232cac9a4ffd0eaeed208a81c40a301c32ebac18ae8a34f31cefd161) the strong name signing.

Was there an issue with the strong name signature or can that be turned on again?

**Comment by AlexandrosMor** [comment]
Hello @Tasteful,

It is going to be added again in the coming release 

kind regards,
Alexandros 
Adyen

**Comment by Tasteful** [comment]
Thanks for fast feedback, do you have a timeframe when it can be expected or is it possible with a service release that adding it back in short time?

**Comment by AlexandrosMor** [comment]
Hey @Tasteful,

We are going to release in the coming week so it is going to be included. The plan is to automate the release so it is always strongly singed

kind regards,
Alexandros
Adyen

**Comment by Tasteful** [comment]
@AlexandrosMor Any update on the release date?
