### ISSUE TITLE
Bugs in Equals methods of some models classes

### ISSUE THREAD

**Issue by AndreiMikhniuk** [Adyen/adyen-dotnet-api-library#554]
Models\ApiError

public override bool Equals(object obj)
replace
return this.Equals(obj as RecurringDetailsResult);
with 
return this.Equals(obj as ApiError);

---------
Models\ThreeDS2Result

public override bool Equals(object obj)
replace
return this.Equals(obj as ThreeDSecureData);
with 
return this.Equals(obj as ThreeDS2Result);

-----------------
Checkout\PersonalDetails

add implementation of 
public bool Equals(PersonalDetails other)

**Comment by AlexandrosMor** [comment]
Hello @AndreiMikhniuk,

The models are autogenerated so we are going to fix this issues in the future. For now we could not take any action on this. 
kind regards,
Alexandros
Adyen
