### ISSUE TITLE
Model.AbstractPaymentRequest.CaptureDelayHours should be int?

### ISSUE THREAD

**Issue by AndreiMikhniuk** [Adyen/adyen-dotnet-api-library#555]
To support Manual capture use case we should not send any value in the request. In current implementation even when no value provided the default value(0) is sent. This raised immediate capture.

**Comment by AlexandrosMor** [comment]
Hello @AndreiMikhniuk,

We tested on our side and the  `CaptureDelayHours ` if it is not set it will not be serialized. Could you please provide us more information how are you testing this ? 

kind regards,
Alexandros
Adyen
