### ISSUE TITLE
[PW-6312] PosPaymentLocalApi.TerminalApiLocal - Async support

### ISSUE THREAD

**Issue by jsheetzati** [Adyen/adyen-dotnet-api-library#562]
**Is your feature request related to a problem? Please describe.**
When using `PosPaymentLocalApi.TerminalApiLocal`, it would be nice to have the ability to use `await`. Otherwise, this thread is blocked waiting for the terminal's response to the request

**Describe the solution you'd like**
New method on `PosPaymentLocalApi` that returns a Task that we can await

**Comment by AlexandrosMor** [comment]
Hello @jsheetzati,

Thank you for raising this issue. Indeed it would be useful. It is always faster to open a pull request with this change and  there is a 
[contribution guide](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/CONTRIBUTING.md) which can help you.

kind regards,
Alexandros
Adyen

**Comment by jillingk** [comment]
Hi @jsheetzati,

I've finally gotten around to fix this issue with the PR #662! Apologies for the big delay. 

Best, Jilling
Adyen
