### ISSUE TITLE
Account.UploadDocument returns that image uploaded is too small

### ISSUE THREAD

**Issue by wiertara** [Adyen/adyen-dotnet-api-library#572]
**Describe the bug**
I'm trying to upload document for an account holder but I'm constantly getting exception "The image uploaded is too small. The minimum accepted image file size : 10000 bytes..." even though I'm sending the documentContent more thant 2MB.

To get documentContent bytes array I'm using following code:
`var documentContent = Convert.FromBase64String(base64EncodedContent);`

The **base64EncodedContent** is valid and can be successfully uploaded by API call using Postman. Also the UploadDocumentRequest.ToJson() returns correct json that can be uploaded using API call.

I'm using the Nuget package 8.1.0.

**Expected behavior**
The document should be uploaded successfully.

**Comment by AlexandrosMor** [comment]
Hello @wiertara, 

This error message comes from the api response. The library does not parse the data.  
Is this code var documentContent = Convert.FromBase64String(base64EncodedContent); part of the library ? 

kind regards,
Alexandros
Adyen

**Comment by wiertara** [comment]
No this particular code is not the part of this library but the library incorrectly serializes bytes array to json. It seems that your ByteArrayConverter used to serialize to json is using wrong encoding (ASCII) during WriteJson: https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Util/ByteArrayConverter.cs

**Comment by jillingk** [comment]
Hi @wiertara,

 I've finally got around to fixing this! Apologies for the huge delay.

Best, Jilling
Adyen
