### ISSUE TITLE
Typo in PaymentsDetailsRequest class name

### ISSUE THREAD

**Issue by jonekdahl** [Adyen/adyen-dotnet-api-library#574]
**Describe the problem**

Several classes deal with payment details. All of them have a `PaymentDetails` prefix but `PaymentsDetailsRequest` has an additional `s`. Perhaps this class can be renamed to `PaymentDetailsRequest` in the next major release?

**Additional context**

Adyen library version: 8.0.1

**Comment by jillingk** [comment]
Hi @jonekdahl,

Thanks for your input, it makes sense to straighten the naming of the classes! I will see if we can make the change in the next release. 

Best, Jilling
Adyen
