### ISSUE TITLE
Class Adyen.Models.Nexo.SaleToPOIMessage should be SaleToPOIRequest [PW-6738]

### ISSUE THREAD

**Issue by nola2172** [Adyen/adyen-dotnet-api-library#575]
SaleToPOIMessage is not the correct name of the class that the pinpad/terminal is looking for and it conflicts with the JSON that the documentation says should be sent (SaleToPOIRequest).  If you try to use the NuGet package or a compiled version of the GitHub code to send a request to the pinpad/terminal with Adyen.Service.PosPaymentLocalApi.TerminalApiLocal, you will get the following error:

Message = "The remote server returned an error: (400) Bad Request."
{ "errors": [ "At toplevel, field SaleToPOIRequest: Missing", "At toplevel: Missing" ] }

On my local system, I did a rename of SaleToPOIMessage to SaleToPOIRequest, and that fixed the problem.

**Comment by jillingk** [comment]
Hi @nola2172,

Thank you for you input. I'm sorry to hear that you were experiencing this issue. I created a ticket to rename the class so that this issue won't show up anymore! 

Best, Jilling
Adyen
