### ISSUE TITLE
Set security protocol to Tls12 also voor sync requests

### ISSUE THREAD

**Issue by rsegerink** [Adyen/adyen-dotnet-api-library#580]
Forn a async http request the security protocol is explicit set to Tls 1.2, see: https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/HttpClient/HttpURLConnectionClient.cs#L89
But for the sync request this is not done and therefore http requests won't work when used on older .net framework versions.

**Comment by jillingk** [comment]
Hey @rsegerink,

Thank you for bringing this to our attention. I created a PR #617 to fix this for you! 

Best, Jilling
Adyen
