### ISSUE TITLE
PaymentLinks not updated to support V68

### ISSUE THREAD

**Issue by nord-** [Adyen/adyen-dotnet-api-library#589]
**Describe the bug**
`storePaymentMethodMode` (string) is replacing `storePaymentMethod` (bool) in V68, but there is no parameter in the `CreatePaymentLinkRequest`-class to set it, and using the old parameter is generating an error:

`{"status":400,"errorCode":"702","message":"Structure of CreatePaymentLinkRequest contains the following unknown fields: [storePaymentMethod]","errorType":"validation"}`

https://docs.adyen.com/api-explorer/#/CheckoutService/v68/post/paymentLinks

https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/paymentLinks

**Comment by jillingk** [comment]
Hi @nord-,

Sorry the late response. After quickly looking into it, you should be able to set the `storePaymentMethodMode`. There is a `StorePaymentMethodModeEnum` class that lets you allows you to set the parameter to enabled/disabled. Let me know if this helps or if you keep running into the same problem!

Best, Jilling
Adyen

**Comment by nord-** [comment]
No, there is no property. It's missing in the `CreatePaymentLinkRequest`-object.
![bild](https://user-images.githubusercontent.com/3777600/172802559-9aedaf75-0ed7-4351-acb4-cb3073eb4631.png)

**Comment by nord-** [comment]
Ok. So this is solved in #595 that is released yesterday, not 6 days ago when you posted, @jillingk .
I will verify with latest (9.0.0) and get back to you.

**Comment by nord-** [comment]
The issue is resolved in the latest release ([9.0.0](https://github.com/Adyen/adyen-dotnet-api-library/releases/tag/9.0.0)).
