### ISSUE TITLE
Creating Adyen.Client throws InvalidOperationException on the live environment

### ISSUE THREAD

**Issue by akScript** [Adyen/adyen-dotnet-api-library#594]
When creating an `Adyen.Client` for the live environment using basic authentication (`username` and `password`) a `System.InvalidOperationException` is thrown with the following message: _Missing liveEndpointUrlPrefix for endpoint generation_.
```C#
var client = new Client("ws_*******", "******", Adyen.Model.Enum.Environment.Live);
var fundClient = new Fund(client);
```
Other than using the `Client(Config config)` constructor, It does not seem that there is a way to provide the `liveEndpointUrlPrefix` parameter along with the `username` and `password`.

**To Reproduce**
To reproduce run the code snippet above.

**Expected behavior**
Using `Client(string username, string password, Environment environment)` constructor, an `Adyen.Client` object is created for the live environment.

**Comment by AlexandrosMor** [comment]
Hello @akScript,

We opened a pr with the fix code. Thank you for raising this issue

kind regards,
Alexandros
Adyen

**Comment by akScript** [comment]
Hello @AlexandrosMor,

Thank you, much appreciated.
