### ISSUE TITLE
Obsolete `HostedPaymentPages` service

### ISSUE THREAD

**Issue by bjarnef** [Adyen/adyen-dotnet-api-library#605]
**Is your feature request related to a problem? Please describe.**
I noticed HPP has been deprecated for some time https://docs.adyen.com/online-payments/classic-integrations/hosted-payment-pages/deprecation which `HostedPaymentPages` seems to use.
https://github.com/Adyen/adyen-dotnet-api-library/blob/7ed4360e7413677e942695e224f9e512c6b893a5/Adyen/Service/HostedPaymentPages.cs#L44

But I was surprised this hasn't been marked as obsolete or at lease a a note about it?

I guess from **1 October 2022** this will stop working?

Furthermore the `HostedPaymentPages` service + the HPP configs should probably be removed in the major or minor version of the package?

**Comment by jillingk** [comment]
Hey @bjarnef,

Thanks for reaching out to us. You're right in that HPP has been depreciated for a while now. It's unfortunate to hear that you haven't received any news of this though. There has been a [blog](https://www.adyen.com/blog/HPP-end-of-life) about the matter, so if you missed that consider checking out the [Adyen blogs](https://www.adyen.com/blog) or subscribe to the newsletter at the bottom of the page.

I will create an internal ticket to remove the HPP functionalities from the library. If you have any other questions/remarks about this or your migration from HPP, please let us know!

Best, Jilling
Adyen
