### ISSUE TITLE
paymentMethod not parsed in PaymentResponse

### ISSUE THREAD

**Issue by sparkinson** [Adyen/adyen-dotnet-api-library#609]
**Is your feature request related to a problem? Please describe.**
When calling the "Payments" method, which internally calls the Adyen /payments api endpoint, the 'paymentMethods' item in the response is not included in the PaymentResponse object returned by this library. And so we do not have the card brand in the PaymentResponse object for card payments.

I would have to also listen to webhook events to obtain validated forms of this information.

**Describe the solution you'd like**
Add a PaymentMethods property to the PaymentResponse object detailed here: https://docs.adyen.com/api-explorer/#/CheckoutService/v69/post/payments__resParam_additionalData-ResponseAdditionalDataCommon-paymentMethod

**Describe alternatives you've considered**
Listening to webhook notifications (awkward)
Using the brand in the request - but this depends upon clients of my API behaving and is not validated by Adyen

**Comment by jillingk** [comment]
Hi @sparkinson,

Thank you for bringing this to our attention. This response you are mentioning is actually a specific new feature of the new v69 payments API. We have an PR #606 open as we speak introducing the updated models and endpoints. We will try to merge it asap!

Let me know in the meantime if you have any additional questions or remarks.

Best, Jilling
Adyen
