### ISSUE TITLE
Cost Estimation Api

### ISSUE THREAD

**Issue by junalmeida** [Adyen/adyen-dotnet-api-library#61]
Any plans to support this api?

https://docs.adyen.com/developers/api-reference/cost-estimation-api/getcostestimaterequest

**Comment by AlexandrosMor** [comment]
Hey @junalmeida,

We created an internal ticket and we will investigate the possibility to support the cost estimation api.

Regards,
Alexandros Moraitis
Adyen

**Comment by AlexandrosMor** [comment]
PR [118](https://github.com/Adyen/adyen-dotnet-api-library/pull/118)
