### ISSUE TITLE
Missing fields in IPaymentResponseAction

### ISSUE THREAD

**Issue by seallard** [Adyen/adyen-dotnet-api-library#612]
**Describe the bug**
Missing fields in the IPaymentResponseAction:
- paymentMethodType
- url
- method

These should be present when a post request is sent against /payments in the [first step](https://docs.adyen.com/payment-methods/trustly/payouts#page-introduction) when initiating a trustly payout.

**To Reproduce**
Send the following request:
```

curl https://checkout-test.adyen.com/v68/payments \
-H "x-API-key: YOUR_X-API-KEY" \
-H "content-type: application/json" \
-d '{
     "amount":{
        "value":0,
        "currency":"SEK"
     },
     "paymentMethod":{
        "type":"trustly"
     },
     "enablePayOut":true,
     "shopperReference":"Supplier_JaneSmith", 
     "reference":"YOUR_ORDER_NUMBER",
     "returnUrl": "https://your-company.com/checkout?shopperOrder=12xy..",
     "merchantAccount":"YOUR_MERCHANT_ACCOUNT",
}'
```
The response contains the fields above which are not mapped in IPaymentResponseAction

**Expected behavior**
The fields should be included in IPaymentResponseAction.

**Comment by AlexandrosMor** [comment]
Hello @seallard,

IPaymentResponseAction is an interface which is used to help with the deserialization of the response if it contains `action`. The helper class that is  responsible for this is [PaymentResponseActionConverter](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Util/PaymentResponseActionConverter.cs) which is instatiates the correct class that implements the Interface and these fields should not be part of it. Could you maybe sent us which action is returned for this response ? 

kind regards,
Alexandros
Adyen
