### ISSUE TITLE
Management API support

### ISSUE THREAD

**Issue by PiotrKoszarny** [Adyen/adyen-dotnet-api-library#627]
Any plans supporting Management API?
 I would like to manage webhooks by API
 
 https://docs.adyen.com/api-explorer/#/ManagementService/v1/post/merchants/{id}/webhooks

**Comment by jillingk** [comment]
Hi @PiotrKoszarny,

Thanks for reaching out to us! I have created an internal ticket to start working on adding the Management API to this library. When we will actually get around to implementing it, I'm not too sure about though. Either way I will keep you posted on this.

Best, Jilling
Adyen
