### ISSUE TITLE
Add BankAccountUuid to CreateAccountRequest class (calling CreateAccount method)

### ISSUE THREAD

**Issue by ASisroEndava** [Adyen/adyen-dotnet-api-library#641]
**Issue description**
When calling CreateAccount method using the Adyen nuget package in dotnet, i cannot specify BankAccountUuid into **CreateAccountRequest**.  It is present in **UpdateAccountRequest** though

**To Reproduce**
Make a call to CreateAccount method, the parameter of type **CreateAccountRequest** does not have BankAccountUuid attribute

**Expected behavior**
On calling CreateAccount, i should be able to specify a BankAccountUuid which will be assigned to the Account

**Additional context**
BankAccountUuid attribute is missing here:
https://github.com/Adyen/adyen-dotnet-api-library/blob/88e299261e8e0302f8ed6744b9c5d6fedbe31da4/Adyen/Model/MarketPay/CreateAccountRequest.cs#L124-L147

**Comment by jillingk** [comment]
Hi @ASisroEndava,

Thanks for reaching out to us with this. There are indeed some things missing in our models, this should change soon though as we're in the middle of automation the model generation for our API libraries. For now to fix this for you I opened a quick PR to add this field to the CreateAccountRequest model.

Best, Jilling
Adyen

**Comment by ASisroEndava** [comment]
Hi Jilling/Adyen team

Thanks for considering this quick PR to address that fix.
Do you have any ETA for this you can provide?

Thanks in advance

ARIEL SISRO
SENIOR ENGINEER

***@***.***




T / M +598 99 44 88 22

**Comment by ASisroEndava** [comment]
Hi Jaeha/Joe

We saw Adyen team already created a PR to address the CreateAccount missing BankAccountUUID field, but it is still open.
Do you have an ETA for that to be implemented and released?

Thanks!

ARIEL SISRO
SENIOR ENGINEER

***@***.***




T / M +598 99 44 88 22


From: Ariel Sisro
Sent: Tuesday, August 23, 2022 10:09 AM
To: Adyen/adyen-dotnet-api-library ***@***.***>; Adyen/adyen-dotnet-api-library ***@***.***>
Cc: Mention ***@***.***>; Greg Bronzert ***@***.***>; ***@***.***; Todd Story ***@***.***>; Robert Salicco ***@***.***>; Walter Garcia ***@***.***>; Beerbal Abdulkhader ***@***.***>
Subject: RE: [Adyen/adyen-dotnet-api-library] Add BankAccountUuid to CreateAccountRequest class (calling CreateAccount method) (Issue #641)

Hi Jilling/Adyen team

Thanks for considering this quick PR to address that fix.
Do you have any ETA for this you can provide?

Thanks in advance

ARIEL SISRO
SENIOR ENGINEER

***@***.***




T / M +598 99 44 88 22

**Comment by jillingk** [comment]
Hi @ASisroEndava,

Apologies for the delay, I was OOO for quite a while. I just merged the PR and we will try to release this fix asap. Have a nice day!

Best, Jilling
Adyen

**Comment by ASisroEndava** [comment]
Joe,

Any update on the release of this PR? Or is there a way for us to pull the
pre-release version to continue our design?

Thanks,
Greg

**Comment by jillingk** [comment]
Hi @ASisroEndava,

The new release has now been uploaded to Nuget and you should be able to import it!

Best, Jilling
Adyen

**Comment by ASisroEndava** [comment]
Hi Ariel,

The PR in question does not have conflicts but still needs a second reviewer to approve. We will follow up to see who can issue the second review and approval.

Best,
Joe
---
Joe Plonsker
Implementation Engineer

mobile: 415-559-8988
contact: adyen.com/contact

Adyen San Francisco
274 Brannan Street Suite 600
San Francisco, CA 94107, United States
