### ISSUE TITLE
RemoteCertificateValidationCallback - Certificate Validation

### ISSUE THREAD

**Issue by jacquespieterse** [Adyen/adyen-dotnet-api-library#652]
When using library in a small windows test application.  

The certificate validation fails during RemoteCertificateValidationCallback in HttpURLConnectionClient.cs.  
When RemoteCertificateValidationCallback is triggered, there are 2 policy errors, RemoteCertificateNameMismatch | RemoteCertificateChainErrors and therefore it ignores the "TerminalCommonNameValidator.ValidateCertificate".

Even if it made it to the "Validate Certificate" the certificate being returned does not contain "adyen" in the subject.
Certificate:
[Subject]
  CN=127.0.0.1.xip.io
[Issuer]
  CN=H2O Test CA

Question:
1. Having a look at Microsoft documentation, am I correct in assuming that the certificate in this function is being returned by the terminal?
2. From the extract above, does our terminal have an incorrect certificate?

A side note on this, I am getting the same certificate error in a customer integration using Delphi.

Regards,
Jacques

**Comment by jacquespieterse** [comment]
After some further investigation, it seems that the test terminals still has legacy certificates and this the reason for the funny 127.0.0.1.xip.io certificate.  

When using the Adyen .NET library as a NuGet package, it would not have been possible to pinpoint this error.

The certificate validation is obviously very important, but is there a possibility to introduce a config to disable validation, but only in the TEST environment.  This is just to allow development and testing to continue for situations where the terminal might have an incorrect certificate.

Regards,
Jacques

**Comment by jillingk** [comment]
Hi @jacquespieterse,

Thanks for reaching out to us with this issue and apologies for the super delayed response. What .NET version were you using during this testing? It seems that this might be because of some issues with 2.0. Let me know!

Best, Jilling
Adyen
