### ISSUE TITLE
Hosted Onboarding API v1 vs v2 - compatible?

### ISSUE THREAD

**Issue by Tommixoft** [Adyen/adyen-dotnet-api-library#654]
Sorry for maybe misleading issue, but so far this library supports Hosted Onboarding API v1, but current version is v2. 
Do you RECOMMEND to avoid using this library for Hosted Onboarding API or is it still covers most the things and is ok to be used in production?

**Comment by jillingk** [comment]
Hi @Tommixoft,

Thanks for reaching out to us and apologies for the delayed response. You're right that we are still on v1 with this API, however I do not think this will majorly impact you. We are however very busy trying to our libraries fully up to date with the API and this library is next (after the java library which we're working on right now). So if anything ends up missing or bothering you should see it fully up to date fairly soon as well. 

Hope this clears it up a little bit!

Best, Jilling
Adyen
