### ISSUE TITLE
[PW-7504] System.ArguementException for Poi Message Display Notification

### ISSUE THREAD

**Issue by Martijn-W** [Adyen/adyen-dotnet-api-library#661]
**Describe the bug**
When deserializing a display notification ([display-notifications](https://docs.adyen.com/point-of-sale/notifications/display-notifications?tab=codeBlockdisplay_notifications_0_hSl0R_Json_1)) using the `SaleToPoiMessageSerializer` we get an System.ArgumentException.

**To Reproduce**
1. Copy an example JSON value from the link above (or start a real pin terminal transaction with event notifications enabled)
2. Run the following code:
`var result = new SaleToPoiMessageSerializer().Deserialize("json here");`
3. See error:
```
{System.ArgumentException: GenericArguments[0], 'Adyen.Model.Nexo.DisplayRequest', on 'Adyen.ApiSerialization.MessagePayloadSerializer`1[T]' violates the constraint of type 'T'.
 ---> System.TypeLoadException: GenericArguments[0], 'Adyen.Model.Nexo.DisplayRequest', on 'Adyen.ApiSerialization.IMessagePayloadSerializer`1[T]' violates the constraint of type parameter 'T'.
   at System.RuntimeTypeHandle.Instantiate(RuntimeType inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Adyen.ApiSerialization.MessagePayloadSerializerFactory.CreateSerializer(String messageCategory, String messageType)
   at Adyen.ApiSerialization.SaleToPoiMessageSerializer.DeserializeMessagePayload(MessageHeader messageHeader, JToken saleToPoiMessageWithoutRootJToken)
   at Adyen.ApiSerialization.SaleToPoiMessageSerializer.Deserialize(String saleToPoiMessageDto)
```

**Expected behavior**
A deserialized object with no exception.

**Desktop (please complete the following information):**
 - OS: Linux / macOS / Windows
 - Version: Adyen SDK 9.1.0
 - .NET version: 6

**Additional context**
Request JSON example:
```json
{
  "SaleToPOIRequest":{
    "DisplayRequest":{
      "DisplayOutput":[
        {
          "Device":"CashierDisplay",
          "InfoQualify":"Status",
          "OutputContent":{
            "OutputFormat":"MessageRef",
            "PredefinedContent":{
              "ReferenceID":"event=CARD_INSERTED"
            }
          },
          "ResponseRequiredFlag":false
        }
      ]
    },
    "MessageHeader":{
      "SaleID":"POSSystemID12345",
      "ProtocolVersion":"3.0",
      "MessageType":"Request",
      "POIID":"V400m-324688179",
      "ServiceID":"0207111617",
      "MessageClass":"Device",
      "MessageCategory":"Display",
      "DeviceID":"1517998563"
    }
  }
}
```

Example code:
```csharp
const string requestJson = "above json example";

try
{
    var result = new SaleToPoiMessageSerializer().Deserialize(requestJson);
}
catch (Exception ex)
{
}
```

**Comment by jillingk** [comment]
Hi @Martijn-W,

Thanks a lot for reaching out to us with this issue and apologies for the not so timely response. After looking at the library we found that we indeed do not have a proper deserializer for the display notifications. This is because the display notifications are not deserialized to the SaleToPoiResponse object but rather the SaleToPoiMessage. I created a ticket to add a custom deserializer for this. Additionally feel free to contribute and open a PR for this. 

Best, Jilling
Adyen
