### ISSUE TITLE
[PW-7313] PaymentMethodDetailsConverter has no support for "googlepay"

### ISSUE THREAD

**Issue by VDBBjorn** [Adyen/adyen-dotnet-api-library#678]
**Describe the bug**

Using the PaymentMethodDetailsConverter to convert the google pay payment details results in a loss of data, as the Type that is sent over is not "paywithgoogle" as stated in the SDK, but rather "googlepay".

**To Reproduce**

1) pay using google pay in the dropin
2) look at the paymentdetails being sent through
example: `"{\"type\":\"googlepay\",\"googlePayToken\":\"{\\\"signature\\\":\\\"***\\\",\\\"protocolVersion\\\":\\\"ECv1\\\",\\\"signedMessage\\\":\\\"{\\\\\\\"encryptedMessage\\\\\\\":\\\\\\\"***\",\\\\\\\"ephemeralPublicKey\\\\\\\":\\\\\\\"***",\\\\\\\"tag\\\\\\\":\\\\\\\***"}\",\"googlePayCardNetwork\":\"VISA\"}"`
3) Use  JsonOperation.Deserialize<IPaymentMethodDetails>( `<string holding the JSON above>` )
4) As the type (googlepay) is "unknown" for the deserializer, only the Type get deserialized and all other info gets dropped when sending this over to adyen.

**Expected behavior**

"googlepay" should be an actual type in the deserializer, so the extra information is automatically deserialized.

**Comment by jillingk** [comment]
Hi @VDBBjorn,

Thanks a lot for reaching out to us with this issue. I created an internal ticket to fix this!

Best, Jilling
Adyen

**Comment by jillingk** [comment]
Hi @VDBBjorn,

It took some time, but we have finally released a new version v10.0.0-beta which fixes this issue and adds all of our latest API endpoints. Let us know if you need any help with your integration or if you run into anything!

Best, Jilling
Adyen
