### ISSUE TITLE
[PW-7587] Checkout API, Basic Authentication (username + password) does not work using synchronous methods

### ISSUE THREAD

**Issue by LinusCenterstrom** [Adyen/adyen-dotnet-api-library#679]
**Describe the bug**
Using synchronous endpoints in the Checkout API (and possible others, have not checked) will result in 401 if the client is created using basic auth.

I checked the code and the reason they work differently is that ServiceResource.cs handles the IsApiKeyRequired flag differently.
The asyncversion always sends false to the GetHttpWebRequest method.

https://github.com/Adyen/adyen-dotnet-api-library/blob/ab8f628d461295f44ae96f4486ea617a1a9eb1ac/Adyen/Service/ServiceResource.cs#L43-L55

The GetHttpWebRequest has a possible bug (not sure what the flag is supposed to do exactly so this might be WAD) that never uses basic auth if isApiKeyRequired is true.
https://github.com/Adyen/adyen-dotnet-api-library/blob/ab8f628d461295f44ae96f4486ea617a1a9eb1ac/Adyen/HttpClient/HttpURLConnectionClient.cs#L187-L192

**To Reproduce**
Initialize the client and request any endpoint using the non-async version of the call

**Expected behavior**
It should work just the same as the async version

**Workaround**
If anyone else runs into this issue before it's fixed, a workaround is to explicitly set IsApiKeyRequired to false when initializing the Checkout Service.
```cs
var checkout = new Checkout(client)
{
    IsApiKeyRequired = false
};
```

**Comment by jillingk** [comment]
Hi @LinusCenterstrom,

Thanks a lot for reaching out to us with this issue. We created a ticket for this issue and will try to look into what is causing this! 

In the meantime perhaps consider using the API key instead of the basic authentication, as that is actually our preferred authentication method. I'll keep you posted on if/when we can fix this.

Best, Jilling
Adyen
