### ISSUE TITLE
Multiple ChannelEnum types are confusing and tedious

### ISSUE THREAD

**Issue by jonekdahl** [Adyen/adyen-dotnet-api-library#684]
**Describe the problem**

In our Adyen implementation, we select the merchant account based on the incoming `channel` value. Since there are multiple ChannelEnum types (one for each request type), we're forced to implement the same logic for each of the following types:

 * CreateCheckoutSessionRequest.ChannelEnum
 * PaymentMethodsRequest.ChannelEnum
 * PaymentRequest.ChannelEnum

Since they all seem to represent the same set of values (`Web`, `iOS` and `Android`), wouldn't it make sense to use the same enum type everywhere?

**Comment by jillingk** [comment]
Hi @jonekdahl,

Thanks a lot for reaching out to us with this issue. Indeed we have quite a couple of duplicate enums, which stem from the fact that we auto-generate the models in this library. Ideally we would find some option to not use these duplicate classes, however that might get complicated real fast with changing models etc. We are definitely considering this though, as we also see the benefit of more simple shared classes (where it's possible).

Best, Jilling
Adyen
