### ISSUE TITLE
UpdateAccountAsync call throws exception when PayoutSchedule is null

### ISSUE THREAD

**Issue by ASisroEndava** [Adyen/adyen-dotnet-api-library#689]
When we call **UpdateAccountAsync** method on Adyen.Service.Account without specifying PayoutSchedule in request, an exception is thrown saying:
 **"payoutSchedule is a required property for UpdateAccountResponse and cannot be null"** 

**To Reproduce**
Make a call to UpdateAccountAsync with a valid account without passing the optional field PayoutSchedule 

**Expected behavior**
Account should be updated with the data we send

**Library version**
Adyen .net API Library 9.1.0 (Latest)

**Comment by jillingk** [comment]
@ASisroEndava,

Thanks for reaching out to us with this issue. I see that indeed the library requires you to populate the PayoutSchedule field, even though the API strictly does not require this. We will remove this required property!

Best, Jilling
Adyen
