### ISSUE TITLE
Missing requestType NFCReadUID in Adyen.Model.Nexo.MessageCategoryType enumeration

### ISSUE THREAD

**Issue by cgill1607** [Adyen/adyen-dotnet-api-library#718]
Hello,

I want to read the UUID from an Mifare NFC Card on a castles S1F2 terminal.
Since Firmware 1.82.1 this feature should be implemented. (See request #3195828)

When i understand the documentation correctly I have to set the requesttype in the messageHeader to the string NFCReadUID. But with the Adyen.Dll from the nuget Package i can't set the header directly to a string. There is only an enumeration MessageCategoryType in the namespace Adyen.Model.Nexo and here the new requestType NFCReadUID is missing.

Therefore I can't set the RequestType to the needed value.

There are only two ways to solve this.

1. Your development must also add the new requesttype NFCReadUID to the enumeration. or

2. Your development must add a command to send a JSON string directly.
(Add an additional Command to the PosPaymentLocalApi and PosPaymentCloudApi class that you can send a Json Message directly to the terminal. eg         
public SaleToPOIResponse TerminalApiLocal(string saleToPoiRequest, EncryptionCredentialDetails encryptionCredentialDetails);

additional to 

public SaleToPOIResponse TerminalApiLocal(SaleToPOIMessage saleToPoiRequest, EncryptionCredentialDetails encryptionCredentialDetails);

Without one of this changes I simply can't use the new command which is integrated in the firmware.

Or you show me a way to call the new  NFCReadUID function with the Adyen Nuget Package from c#. But I think it's not possible without changes in the Nuget Package.

With kind regards

Dr. Christian Gill

**Comment by jillingk** [comment]
Hi @cgill1607,

Thanks a lot for reaching out to us with this issue. I quickly read through the [documentation](https://docs.adyen.com/point-of-sale/nfc-tags#identify-nfc-tag-request) of the functionality you're trying to use and it seems like you might have misinterpreted it. The type NFCReadUID is not set in the header but in the payload body instead. The **MessageCategory** in the **MessageHeader** is actually set to ```"CardAcquisition"```, which is an enum in this library. Then in the payload you create a **CardAcquisitionRequest** object, where you can set the **SaleData**->**SaleToPOIData** equal to the **Operation** base64 encoded json that contains the ```Type: NFCReadUID```.

I just checked the library and all the above mentioned objects seem to be available. Only the Operation json object you have to create yourselves and encoded base64. Hope that this helps, let me know if you run into anything else.

Kind regards,
Jilling
Adyen
