### ISSUE TITLE
More robust exception-handling by HttpUrlConnectionClient

### ISSUE THREAD

**Issue by jaw64** [Adyen/adyen-dotnet-api-library#72]
**Note: this may be a duplicate of issue #28?**

Currently, `HttpUrlConnectionClient` is vulnerable to `Exception`s being thrown both [when sending the request](https://github.com/Adyen/adyen-dotnet-api-library/blob/c0c1245a7c88b6e2cde8c75b58f163923c5ec443/Adyen.EcommLibrary/HttpClient/HttpURLConnectionClient.cs#L25) and also [when handling `WebException`s thrown](https://github.com/Adyen/adyen-dotnet-api-library/blob/c0c1245a7c88b6e2cde8c75b58f163923c5ec443/Adyen.EcommLibrary/HttpClient/HttpURLConnectionClient.cs#L45) when retrieving the response (particularly if `WebException.Response` happens to be null, which [.NET documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.webexception.response?view=netframework-4.7.2) says is possible).

I have seen a few `NullReferenceException`s thrown for different endpoints (very infrequently, once a day or less) and it seems to always be happening in this `HttpUrlConnectionClient.Request(...)` method, but I can't pinpoint exactly where it's occurring at because I'm currently using the NuGet package. From .NET documentation, the only place I can see this type of exception potentially occurring is at the handling of the `WebException`. Here is the stack trace, though I don't know that it'll be very helpful:

```
Stack trace:
   at Adyen.EcommLibrary.HttpClient.HttpUrlConnectionClient.Request(String endpoint, String json, Config config, Boolean isApiKeyRequired, RequestOptions requestOptions)
   at Adyen.EcommLibrary.Service.ServiceResource.Request(String json, RequestOptions requestOptions)
   at Adyen.EcommLibrary.Service.Payment.Authorise(PaymentRequest paymentRequest, RequestOptions requestOptions)
   at FooBar.MyApp.AuthoriseRequest.Execute(PaymentRequest paymentRequest)
   at FooBar.MyApp.Authorise.Execute(PaymentProcessRequest paymentProcessRequest, PaymentInfo paymentInfo)
 ```

Is this intended behavior? Is the merchant responsible for handling these exceptions, and if so, how should they be handled?

**Comment by AlexandrosMor** [comment]
Hello @jaw64 

Yes the merchant is responsible to handle the exception at this point. The exception should be handled in a higher level in case of error or unexpected behavior. In this way the merchant's application is informed what went wrong. The HttpClientException is a custom exception which contains the status code, headers and the last message from the api the responseText. 

Kind regards,
Alexandros Moraitis
Adyen

**Comment by jaw64** [comment]
So in the case I'm describing, no status code is returned at all because a `NullReferenceException` was thrown before the `HttpClientException` could be instantiated. Is there any guess as to why that might be happening [inside this method](https://github.com/Adyen/adyen-dotnet-api-library/blob/c0c1245a7c88b6e2cde8c75b58f163923c5ec443/Adyen.EcommLibrary/HttpClient/HttpURLConnectionClient.cs#L19) specifically?

How should merchants handle these exceptions in general? By just ignoring the error and retrying the request?

**Comment by AlexandrosMor** [comment]
Hello @jaw64, 

Exception handling can be done from application side. The httpclient can catch and rethrow the generic exception but in that case the handling is done by the library. Every implementation can handle these exceptions in a very different way so this is the reason that the library is not handling them.

I hope it helps,
Kind regards
Alexandros Moraitis
Adyen

**Comment by GauravS07** [comment]
Hii,
Can Someone help me how to integrate adyen payment gateway in asp.net mvc?
