### ISSUE TITLE
Afterpay authorisation problem using /payments checkout endpoint

### ISSUE THREAD

**Issue by irina-epam** [Adyen/adyen-dotnet-api-library#720]
**Describe the bug**
We are trying to send Aftepay authorisation request to /payments checkout endpoint using Adyen .NET nuget library v 9.0.0.

We get error while trying to convert Json to Adyen.Model.Checkout.PaymentRequest model.

Problem is with this part of  request object:
 "PaymentMethod": {
 "type": "afterpaytouch"
  },
The Error message is:
type is a required property for AfterpayDetails and cannot be null

**To Reproduce**
```
1. Try to call /payments endpoint (_checkout.PaymentsAsync() methos from Nuget Library)
2. Use provided json  for request:
     {
2  "MerchantAccount": "BodenUSweb",
3  "Channel": "web",
4  "Origin": https://www.test.com,
5  "ReturnUrl": https://www.test.com,
6  "Reference": "TA0701211225",
7  "AdditionalData": null,
8  "AuthenticationData": {
9    "AttemptAuthentication": "preferno"
10  },
11  "ShopperLocale": "en-US",
12  "EnableRecurring": true,
13  "ShopperReference": "d2132aa2bce24907a083c4ef613c4172",
14  "BrowserInfo": {
15    "AcceptHeader": "*/*",
16    "ColorDepth": 24,
17    "Language": "en-GB",
18    "JavaEnabled": false,
19    "ScreenHeight": 864,
20    "ScreenWidth": 1536,
21    "UserAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
22    "TimeZoneOffset": -240
23  },
24  "Amount": {
25    "currency": "USD",
26    "value": 10000.0
27  },
28  "CountryCode": "US",
29  "PaymentMethod": {
30    "type": "afterpaytouch"
31  },
32  "BillingAddress": {
33    "City": "New York",
34    "Country": "US",
35    "HouseNumberOrName": "509",
36    "PostalCode": "10024",
37    "Street": "Amsterdam Ave",
38    "StateOrProvince": "NY"
39  },
40  "DeliveryAddress": {
41    "City": "New York",
42    "Country": "US",
43    "HouseNumberOrName": "509",
44    "PostalCode": "10024",
45    "Street": "Amsterdam Ave",
46    "StateOrProvince": "NY"
47  },
48  "TelephoneNumber": "3106683312",
49  "ShopperEmail": customer@email.us,
50  "DateOfBirth": "1990-11-29T00:00:00Z",
51  "ShopperName": {
52    "FirstName": "TestPerson",
53    "Gender": "UNKNOWN",
54    "LastName": "Approved"
55  },
56  "LineItems": [
57    {
58      "Quantity": "1",
59      "AmountExcludingTax": "3306",
60      "TaxPercentage": "2100",
61      "Description": "Shoes",
62      "Id": "Item 1",
63      "TaxAmount": "694",
64      "AmountIncludingTax": "4000",
65      "ProductUrl": https://www.mystoredemo.io/#/product/02,
66      "ImageUrl": https://www.mystoredemo.io/static/02.png
67    },
68    {
69      "Quantity": "2",
70      "AmountExcludingTax": "4959",
71      "TaxPercentage": "2100",
72      "Description": "Socks",
73      "Id": "Item 2",
74      "TaxAmount": "1041",
75      "AmountIncludingTax": "6000",
76      "ProductUrl": https://www.mystoredemo.io/#/product/09,
77      "ImageUrl": https://www.mystoredemo.io/static/09.png
78    }
79  ]
80}
```

4. Try co convert this Json to Adyen.Model.Checkout.PaymentRequest model
5. See error

**Expected behavior**
Json is successfully converted to the model and authorisation happens.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Latest version

**Additional context**
![image](https://user-images.githubusercontent.com/105265958/212739577-a12a8b5d-48e0-4128-8b00-270458b17511.png)
AfterpayDetails class has no default constructor and has only constructor with default nullable parameters:
![image](https://user-images.githubusercontent.com/105265958/212739672-756f4674-4ad5-4a4f-b059-b0228229d976.png)

**Comment by jillingk** [comment]
Hi @irina-epam,

Thanks a lot for reaching out to us regarding your issue. Indeed it seems that the Afterpay details model is not really working correctly. This is a result of us patching all these payment methods manually (and in this case incorrectly). Luckily we are working right now on automating the generation of such classes, and I verified that Afterpay is working as intended in our new develop branch. We're trying to release all these changes very soon, but in the meantime we could try to come up with a temporary solution (or maybe import the develop branch of this library locally in your environment).

Let me know what solution you would prefer, so we can assist you with that.

Best regards,
Jilling
Adyen

**Comment by NikolayN01** [comment]
Hi @jillingk,
I hope you are well.

Could you please share an update regarding the tentative date of release of the new version of the library?

Thank you.

Best regards,
Nikolay N.
Business Analyst
Boden

**Comment by jillingk** [comment]
Hi @NikolayN01,

Apologies for the delayed response, we have been quite busy trying to refactor this library and the subsequent release. However as you might have noticed we have release a new version v10.0.0-beta of this library, fixing many issues, adding endpoints and keeping the models up to date.

Testing the changes I would recommend waiting for some documentation that's coming in form of a blogpost/article describing the major changes and how to migrate. In theory not much should change though except for some minor things, which I can elaborate depending on which endpoints you're using (I presume checkout?). 

Starting from this release we will try to release much more often and thus also decrease the amount of major changes. Let us know if you run into anything, and be sure to let us know your experience migrating to our newest library version. 

Best, Jilling
Adyen

**Comment by NikolayN01** [comment]
Hi Jilling,

Thank you very much for your update.
After looking at the changes we realised that the model of the request messages has changed, and it will take us a lot of effort to migrate to the new version of the library.
We are considering options, but I just wanted to double check with you in case you know an easier way. We are using Drop-in, so yes, those should be checkout APIs.

Best regards,
Nikolay N.
