### ISSUE TITLE
Incorrect error message when connecting to payment terminal times out

### ISSUE THREAD

**Issue by jsyrjala** [Adyen/adyen-dotnet-api-library#723]
**Describe the bug**

If I try to connect a payment terminal that is not reachable and connection times out, for example the payment terminal has been shut down, I get this exception:
```
Unhandled exception. Adyen.HttpClient.HttpClientException: Potential certificate mismatch
   at Adyen.HttpClient.HttpUrlConnectionClient.HandleWebException(WebException e)
   at Adyen.HttpClient.HttpUrlConnectionClient.Request(String endpoint, String json, Config config, Boolean isApiKeyRequired, RequestOptions requestOptions)
   at Adyen.Service.ServiceResource.Request(String json, RequestOptions requestOptions)
   at Adyen.Service.PosPaymentLocalApi.TerminalApiLocal(SaleToPOIMessage saleToPoiRequest, EncryptionCredentialDetails encryptionCredentialDetails)
```

`Potential certificate mismatch` is rather misleading here.

**To Reproduce**
1. Shut down payment terminal
2. Try to send message to it with `PosPaymentLocalApi.TerminalApiLocal`
3. Look at the exception that gets throw when timeout happens

**Expected behavior**

I'd expect to get exception that says something about host not reachable or connection timeout.

**Additional context**

curl does this when trying to access the same url
```
curl -i https://192.168.1.10:8443/nexo
curl: (28) Failed to connect to 192.168.1.10 port 8443 after 75013 ms: Operation timed out
```

Adyen dotnet library version 9.1.0.

**Comment by jsyrjala** [comment]
`HttpClientException` has a field `ResponseBody`, which contains the actual error in this case
```
Operation timed out [::ffff:192.168.1.10]:8443 (192.168.1.10:8443)
```

**Comment by wboereboom** [comment]
Hi @jsyrjala,

Thanks for raising this issue.
Unfortunately we cannot influence the actual API behaviour from this library.
Given that fact, I see you have found a way to retrieve the corresponding error from the API response. Do you require any more assistance from our end?

Kind Regards,
Wouter
Adyen

**Comment by jsyrjala** [comment]
Thanks, no more assistance is needed with this issue.
