### ISSUE TITLE
Notification item not serialized

### ISSUE THREAD

**Issue by guibranco** [Adyen/adyen-dotnet-api-library#73]
When serializing the notification (NotificationRequest) the property NotificationItemContainers (a list of NotificaticationItemContainer) comes null (no Json property assigned)

**Comment by guibranco** [comment]
https://docs.adyen.com/developers/development-resources/notifications/set-up-notifications

**Comment by AlexandrosMor** [comment]
Hello @guibranco,

We will look the issue as soon as possible and we will inform you about the status. 

Kind regards,
Alexandros Moraitis,
Adyen

**Comment by guibranco** [comment]
Can I do a PR ?
