### ISSUE TITLE
GET PaymentLinks not implemented

### ISSUE THREAD

**Issue by UTurista** [Adyen/adyen-dotnet-api-library#749]
**Describe the bug**
Checkout service does not implement GET /paymentLinks/{linkId}

**To Reproduce**
1. Create an instance of `Adyen.Service.Checkout`
2. Observe that both`PaymentLinks` and `PaymentLinksAsync` are used only to create a paymentLink and not to check the details of one.

**Expected behavior**
Expected to have a `GetPaymentLinkAsync(string linkId)` that calls the endpoint described here: https://docs.adyen.com/api-explorer/Checkout/70/get/paymentLinks/_linkId_

**Screenshots**
https://github.com/Adyen/adyen-dotnet-api-library/blob/9.2.0/Adyen/Service/Checkout.cs#L188-L210

**Comment by jillingk** [comment]
Hi @UTurista,

Thanks for reaching out to us here. We have just actually implemented the latest version of the Checkout endpoints in our library, including the paymentLinks endpoints. However, we have yet to release this, which we're trying to do very soon. I will keep you updated on when we will do the actual release!

Best, Jilling
Adyen
