### ISSUE TITLE
Error converting value "IdentifyShopper"

### ISSUE THREAD

**Issue by pdavis86** [Adyen/adyen-dotnet-api-library#75]
The class Adyen.EcommLibrary.Model.Checkout.PaymentsResponse has it's own Enum for ResultCodeEnum (instead of using Adyen.EcommLibrary.Model.Enum.ResultCodeEnum) so when making a 3DS call to Adyen.EcommLibrary.Service.Payments you get the error:
````
Error converting value "IdentifyShopper" to type 'System.Nullable`1[Adyen.EcommLibrary.Model.Checkout.PaymentsResponse+ResultCodeEnum]'. Path 'resultCode', line 1, position 31.
````

**Comment by AlexandrosMor** [comment]
Hello @pdavis86,

We will look at the issue and we will include a fix to our next release.

kind regards,
Alexandros
Adyen
