### ISSUE TITLE
9.2.0 version does not support LEM.

### ISSUE THREAD

**Issue by e8-ZimingLiu** [Adyen/adyen-dotnet-api-library#769]
**Describe the bug**
From the readme, we can see it supports LegalEntityManagement. But actually, I can't create an object of LegalEntityManagement

**To Reproduce**
Just install the NuGet package with version 9.2.0 and then try to create an object of LegalEntityManagement.

**Expected behavior**
It can create the object of LegalEntityManagement without error.

**Additional context**
Look like NuGet package Adyen 10.0.0 fixed this.

**Comment by jillingk** [comment]
Hey @e8-ZimingLiu,

Apologies for the delayed answer. We have however just released the .NET library version 10.0.0-beta, which includes LegalEntityManagement and much much more! Everything should be up to date now, and in the future if there are changes/bugs we will be able to release way faster. Be sure to let us know though if you run into anything!

Best, Jilling
Adyen
