### ISSUE TITLE
PaymentData is a required property for PaymentsDetailsRequest

### ISSUE THREAD

**Issue by pdavis86** [Adyen/adyen-dotnet-api-library#77]
There is a check in the ctor of Adyen.EcommLibrary.Model.Checkout.PaymentsDetailsRequest

if (PaymentData == null)
        throw new InvalidDataException("PaymentData is a required property for PaymentsDetailsRequest and cannot be null");

However, various bits of documentation such as https://docs.adyen.com/payment-methods/sofort/#step-4-present-payment-result show that you can submit with just a payload.

The work-around is to pass an empty string into the ctor but this guard clause should be updated/removed

**Comment by AlexandrosMor** [comment]
Hello @pdavis86,

Correct, PaymentData is not required field. We will update it as soon as possilble
