### ISSUE TITLE
SaleToPOIRequest -> PaymentRequest -> SaleToAcquirerData missing 'recurringProcessingModel'

### ISSUE THREAD

**Issue by Tommixoft** [Adyen/adyen-dotnet-api-library#771]
**Describe the bug**
SaleToPOIRequest.MessagePayload as PaymentRequest, SaleToAcquirerData missing property **recurringProcessingModel**.
I can't create token via POS terminal because of this missing property, it mst be set to create token. 
Library have all other needed properties to create token, except for this.
I really would love to avoid using my own version of this lib. 

AdyenLib version 9.2.0, 
10.0.0 beta also missing this property.

**Comment by jillingk** [comment]
Hi @Tommixoft,

Thanks for reaching out to us with this issue. Have you tried put this parameter in the additionalData dictionary in the SaleToAcquirerData class? Our Point Of Sale models are hard to keep up to date unfortunately, which means we resorted to using additionalData dictionaries in some cases. Let me know if this works for you!

Best, Jilling
Adyen

**Comment by Tommixoft** [comment]
Hi, thanks for reply. No i didn't try. I saw in documentation that this parameter goes diretly into **SaleToAcquirerData** object.
Maybe Adyen server parses additionalData like any other properties in this object, than your suggestion should work. Thanks! Will test. WIll take me day or two, not yet finished, but WILL inform and close this issue if this helps.

**Comment by Tommixoft** [comment]
It worked. Thanks. It's bad that token do not come via webhook, as it does using ecommerce account, but that's another problem and will not talk about it here  :)

**Comment by Tommixoft** [comment]
Well looks like it didn't help. I do not receive required fields in response, so looks like putting recurringProcessingModel in Additionaldata - doesnt do the trick, because field recurring.recurringDetailReference in additionalResponse is not returned.

**Comment by Kwok-he-Chu** [comment]
@Tommixoft Just checking if this might be helpful, try the following:

In your `Customer Area`, go to `Developers` → `Additional Settings` → Under `Payment` enable `Recurring Details` for subscriptions. This will pass the recurring.recurringDetailReference as part of your webhook response under the `additionalData` property.

**Comment by Tommixoft** [comment]
If i use postman and post JSON -i do receive all what i need, when i use AdyenLib -i dont receive it. S i dont think it's settings related problem, but my coworker that have access to customer area will double check. But im 99.9% sure it's not the case.

**Comment by jillingk** [comment]
@Tommixoft,

So I just added this parameter quickly as a fix to our nexo models. I realised a bit later that this value actually cannot be part of the additionaldata/metadata dicts, my bad. we'll quickly merge this and release it in our full v10 release (will be fairly soon).

Best, Jilling
Adyen
