### ISSUE TITLE
Commented out code

### ISSUE THREAD

**Issue by opinionmachine** [Adyen/adyen-dotnet-api-library#78]
So, Adyen.EcommLibrary/Notification/NotificationHandler.cs has a bunch of uncommented code. What's wrong with deleting the file in its entirety if it's only returning null?  We're supposed to put people's payment information (well - but you know what I mean) through this codebase, and commented out code, in master, isn't inspiring confidence.

**Comment by AlexandrosMor** [comment]
Hello @opinionmachine ,

We have an internal ticket for this issue and we will update it as soon as possible.

Kind regards,
Alexandros
Adyen
