### ISSUE TITLE
[ITT-514] PaymentMethodsMerchantLevelService.GetAllPaymentMethodsAsync returns list with all fields null

### ISSUE THREAD

**Issue by jnischler** [Adyen/adyen-dotnet-api-library#787]
**Describe the bug**
The method PaymentMethodsMerchantLevelService.GetAllPaymentMethodsAsync always returns a List with the correct count but with all values null (default).

The API
https://management-test.adyen.com/v1/merchants/{merchant}/paymentMethodSettings
returns the the list data wrapped in a PaymentMethod object.
But the SDK dosn't respect this wrapping and thus return a list with all values null.

API Data:

{
	"itemsTotal": 13,
	"pagesTotal": 7,
	"data": [
		{
			"PaymentMethod": {
				"businessLineId": "xxx",
				"id": "xx",
				"type": "amex",
				"storeId": "xx",
				"enabled": true,
				"countries": [],
				"currencies": [
					"CHF",
					"EUR",
					"GBP",
					"USD"
				],
				"allowed": true,
				"verificationStatus": "valid",
				"customRoutingFlags": []
			}
		},
		{
			"PaymentMethod": {
				"businessLineId": "xx",
				"id": "xx",
				"type": "bcmc",
				"storeId": "xx",
				"enabled": true,
				"countries": [],
				"currencies": [],
				"bcmc": {},
				"allowed": true,
				"verificationStatus": "valid",
				"customRoutingFlags": []
			}
		}
	]
}

PaymentMethodResponse
https://github.com/Adyen/adyen-dotnet-api-library/blob/7bf873610acd096adf5105c9aabe56aa16595a44/Adyen/Model/Management/PaymentMethodResponse.cs#L335

PaymentMethodResponse.Data =  public List<PaymentMethod> Data { get; set; }
Missing the "PaymentMethod" wrap

regards
Julian

**Comment by jillingk** [comment]
Hi @jnischler,

Thanks for reaching out to us here with this issue. We have encountered this problem before (and found a solution for it) but were not aware it was also in the management API. We will take a look at it! 

Best, Jilling
Adyen

**Comment by wboereboom** [comment]
Resolved in v10.1.0
