### ISSUE TITLE
HttpUrlConnectionClient - StatusCode 100 continue

### ISSUE THREAD

**Issue by Pret88** [Adyen/adyen-dotnet-api-library#79]
Hi, there is a problem with receiving of response when StatusCode 100 Continue is sended by your server. Example:
Call TerminalApiCloudAsync with SaleToPOIRequest
`public string Request(string endpoint, string json, Config config, bool isApiKeyRequired, RequestOptions requestOptions = null)
        {
            string responseText = null;
         
            var httpWebRequest = GetHttpWebRequest(endpoint, config, isApiKeyRequired, requestOptions);

            using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
            {
                streamWriter.Write(json);
                streamWriter.Flush();
                streamWriter.Close();
            }

            try{
                using (var response = (HttpWebResponse)httpWebRequest.GetResponse())
                {
                    using (var reader = new StreamReader(response.GetResponseStream(), _encoding))
                    {
                        responseText = reader.ReadToEnd();
                    }

                }
            }
            catch (WebException e)
            {
                
                var response = (HttpWebResponse)e.Response;
                using (var sr = new StreamReader(response.GetResponseStream()))
                {
                    responseText = sr.ReadToEnd();
                }
                throw new HttpClientException((int)response.StatusCode, e.Message, response.Headers, responseText);
            }
            return responseText;
        }`

When i run request on Linux platform with .net core, this code raise exception (over 10MB debug file, realy??), when i raised only WebException, then i get 
`{
 "ClassName": "System.Net.WebException",
 "Message": "The remote server returned an error: (100) Continue.",
 "Data": null,
 "InnerException": null,
 "HelpURL": null,
 "StackTraceString": "   at System.Net.HttpWebRequest.GetResponse()\n   at Adyen.EcommLibrary.HttpClient.HttpUrlConnectionClient.Request(String endpoint, String json, Config config, Boolean isApiKeyRequired, RequestOptions requestOptions) in /app/gapatoadyen/src/Adyen.EcommLibrary/HttpClient/HttpURLConnectionClient.cs:line 51\n   at Adyen.EcommLibrary.Service.PosPaymentCloudApi.TerminalApiCloudAsync(SaleToPOIMessage saleToPoiRequest) in /app/gapatoadyen/src/Adyen.EcommLibrary/Service/PosPaymentCloudApi.cs:line 30\n  `

No usual repairs doesnt work
`System.Net.ServicePointManager.Expect100Continue = false;`, settings of Expect header, ...
after 30 hours i found a solution 

```
public HttpWebRequest GetHttpWebRequest(string endpoint, Config config, bool isApiKeyRequired, RequestOptions requestOptions = null)
{
//Add default headers
var httpWebRequest = (HttpWebRequest)WebRequest.Create(endpoint);
 httpWebRequest.Method = "POST";
httpWebRequest.ProtocolVersion = HttpVersion.Version10;
```
HTTP 1.0 doesnt support StatusCode 100, so magicly work.

Please repair receiving of response when 100 status is sended by your server.

**Comment by AlexandrosMor** [comment]
Hello @Pret88,

Thank you for posting the issue. We will try to reproduce the issue and test this solution. We will update you as soon as possible

kind regards,
Alexandros Moraitis
Adyen

**Comment by AlexandrosMor** [comment]
Hello @Pret88,
Sorry for the late response, Is it possible to let us know more how do you run the .net library? For example what linux are you using ?

Thank you in advance,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @Pret88,

For now we are going to close the issue. If you have any questions please open a new issue. 

Thank you in advance,
Alexandros
