### ISSUE TITLE
Unable to cast object of type 'System.Net.FileWebRequest' to type 'System.Net.HttpWebRequest'

### ISSUE THREAD

**Issue by rsilvaZyris** [Adyen/adyen-dotnet-api-library#790]
**Describe the bug**
Trying to implement Adyen API Library with azure functions using C# to work together with web static app trying to follow react drop in guide. Not sure why I keep getting this exception "Unable to cast object of type 'System.Net.FileWebRequest' to type 'System.Net.HttpWebRequest'". 

**Screenshots**
![Screenshot 2023-04-11 at 12 11 06 PM](https://user-images.githubusercontent.com/122044692/231266895-2c29fab1-bbe3-46fd-930d-4bcee089daa7.png)
![Screenshot 2023-04-11 at 12 10 52 PM](https://user-images.githubusercontent.com/122044692/231266901-2dd81260-fa78-41d1-a7a3-9fd917c03490.png)
![Screenshot 2023-04-11 at 12 09 59 PM](https://user-images.githubusercontent.com/122044692/231266904-20b30798-8dc5-4092-b99b-cff65002fe6e.png)
![Screenshot 2023-04-11 at 12 09 40 PM](https://user-images.githubusercontent.com/122044692/231266905-70e35f0e-a196-419f-86ab-386546cafd8f.png)

**Desktop (please complete the following information):**
 - OS: MacBook Pro
 - Browser: safari
 - Codeeditor: Vscode

**Additional context**
I tried version 10.0.0-beta and actually getting ILogger abstraction error on compile time which not sure why that is happening. Versions 9.2.1 - 9..1.0 getting this exception error  "Unable to cast object of type 'System.Net.FileWebRequest' to type 'System.Net.HttpWebRequest'".

**Comment by AlexandrosMor** [comment]
Hello @rsilvaZyris,

Could you provide us the full stacktrace ?  It is a weird issue as the library is not using `FileWebRequest ` in v9 or v10. Is it a class that is used in Azure? 

kind regards,
Alexandros
Adyen

**Comment by rsilvaZyris** [comment]
Hey @AlexandrosMor,

Correct azure functions uses a class. I was actually able to reproduce this on standalone console app. Please see exception message, I do not see anything else come up on the call stack I even have external code enabled. Please see copy of the console program.cs, exception message and screenshots. 

Program.cs
`using Adyen;
using Adyen.Model.Checkout;
using Adyen.Service;
using Environment = Adyen.Model.Enum.Environment;


var amount = new Amount("USD", 1000);

var config = new Config
{
    XApiKey = "API-KEY",
    Environment = Environment.Test
};

var client = new Client(config);
var checkout = new Checkout(client);

var paymentRequest = new Adyen.Model.Checkout.PaymentMethodsRequest(merchantAccount: "COMPANY")
 {
    CountryCode = "US",
    ShopperLocale = "en-US",
    Amount = amount,
    Channel = Adyen.Model.Checkout.PaymentMethodsRequest.ChannelEnum.Web
 };

 var paymentResponse = checkout.PaymentMethods(paymentRequest);


// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!, {0}", client.ApiVersion.ToString());
//Console.WriteLine(paymentRequest.ToString());`

`Exception has occurred: CLR/System.InvalidCastException
* 
An unhandled exception of type 'System.InvalidCastException' occurred in System.Private.CoreLib.dll: 'Unable to cast object of type 'System.Net.FileWebRequest' to type 'System.Net.HttpWebRequest'.'
   at Adyen.HttpClient.HttpUrlConnectionClient.GetHttpWebRequest(String endpoint, Config config, Boolean isApiKeyRequired, RequestOptions requestOptions)
   at Adyen.HttpClient.HttpUrlConnectionClient.Request(String endpoint, String json, Config config, Boolean isApiKeyRequired, RequestOptions requestOptions)
   at Adyen.Service.ServiceResource.Request(String json, RequestOptions requestOptions)
   at Adyen.Service.Checkout.PaymentMethods(PaymentMethodsRequest paymentMethodsRequest)
   at Program.<Main>$(String[] args) in /Users/rafaelsilva/Documents/source/SandboxConsole/Program.cs:line 26`

![Screenshot 2023-04-12 at 10 56 45 AM](https://user-images.githubusercontent.com/122044692/231543846-89de6d19-5595-4d0a-a501-496ad3987eee.png)
![Screenshot 2023-04-12 at 11 03 19 AM](https://user-images.githubusercontent.com/122044692/231545156-6c7292f3-2b9f-42c1-b958-5e1ef0b112ca.png)

**Comment by jillingk** [comment]
Hi @rsilvaZyris,

Can you try upgrading to our library version 10.0.0-beta? Starting from that version we opted to use HttpRequestMessage instead of HttpWebRequest, to create our http request object. Let me know if that works for you.

Best, Jilling
Adyen

**Comment by jillingk** [comment]
Hi @rsilvaZyris,

Were you able to resolve this issue by updating the library version?
