### ISSUE TITLE
[ITT-515]Terminal API: Local communication without encryption (in Test)

### ISSUE THREAD

**Issue by jonekdahl** [Adyen/adyen-dotnet-api-library#791]
**Is your feature request related to a problem? Please describe.**
I am trying to use this library for a Terminal API integration in **Test**, but I can't find a way to make Terminal API calls without encryption.

According to the docs, [protecting local communications](https://docs.adyen.com/point-of-sale/design-your-integration/choose-your-architecture/local?tab=windows_2#protect-communications) is optional for test integrations:

> While you are building a test integration, we don't enforce this step. This allows you to develop the functional and security aspects in parallel.

**Describe the solution you'd like**
A documented solution that describes how to use the `PosPaymentLocalApi` without encryption. I think that would make it easier to get started with the Terminal API.

**Describe alternatives you've considered**
It looks like there is no alternative for the **Test** environment other than setting up the same type of protection as for the **Live** environment.

**Comment by jillingk** [comment]
Hi @jonekdahl,

Thanks a lot for reaching out to us here. This is actually something we have not really thought about but might be a good idea for us to implement at some point. I will create a ticket so we can add this whenever we find some time for it.

Best, Jilling
Adyen

**Comment by jonekdahl** [comment]
Hi @jillingk. Thanks for responding to this features request. Just for my understanding, when you say that you will "create a ticket", is that in an internal issue tracker or here on Github?

**Comment by jillingk** [comment]
Hi @jonekdahl,

Ah my bad I should've specified, It's an internal ticket. We will refine it this week and then hopefully we'll able to work on this soonish. I really like the idea of having this local TAPI without encryption, as the encryption part is a big pain point for a lot of integrators and I think it'd be super useful to test it without.

**Comment by jonekdahl** [comment]
@jillingk No worries, thanks for the clarification.

**Comment by jillingk** [comment]
Hi @jonekdahl,

We've finally gotten around to testing, and implementing the unencrypted Local Terminal API. You can track #869 to see when this will get approved and merged. Hope this helps your integration process (if you haven't integrated already).

Best, Jilling
Adyen

**Comment by AlexandrosMor** [comment]
Hello @jonekdahl,

We added this feature in the [latest release ](https://github.com/Adyen/adyen-dotnet-api-library/releases/tag/v11.1.1)

kind regards,
Alexandros
Adyen
