### ISSUE TITLE
The webhook doesn't Deserialise into a NotificationRequest object

### ISSUE THREAD

**Issue by BrettButcher** [Adyen/adyen-dotnet-api-library#793]
I am successfuly getting a webhook response, but the signature I am using, ( that I lifted from the adyen-dotnet-checkout-example.csproj a sample from Adyen on Github), produces null NotifcationItemContainers. (The Live field is correct.).

This is the signature that doesn't work:

`
        [AllowAnonymous]

        [HttpPost]

        [Route(Routes.AdyenWebHookRoute)]// should be api/finance/AdyenReponse
        public async Task<ActionResult<string>> Webhooks([FromBody] NotificationRequest notificationRequest)
        {
`
When I debug this,  the Notification containers are null...
![image](https://user-images.githubusercontent.com/39193658/232033940-5cbc8e67-562e-4923-bfa1-ed58997348c9.png)

I have tried decoding it manually as follows:

`
        [AllowAnonymous]
        [HttpPost]
        [Route(Routes.AdyenWebHookRoute)]  // should be api/finance/AdyenReponse
        public async Task<ActionResult> PaymentResult()
        {

            var json = await new StreamReader(HttpContext.Request.Body).ReadToEndAsync();

            var obj = JsonConvert.DeserializeObject<NotificationRequest>(json);
            try
`
This works ok, but obviously I would prefer to use the Adyen objects rather than laboriously create my own.

My Using statements are:

`using Adyen.Model.Checkout;

using AutoMapper;

using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Identity;

using Microsoft.AspNetCore.Mvc;

using Newtonsoft.Json;

... (my stuff)

using System.Data;

using System.Runtime.Serialization;`

I assume this works in the sample code... it doesnt do much so I didnt debug it at the time and since I moved on, it would take some unwinding to go back.

I am implementing the Adyen-drop in into a Blazor based client, but this is obviously a the server which is a .NET 6 based application under Windows.

I was advised to post this here by Adyen tech support.

Many thanks.
PS. I could also do with a link to some details of the Drop-in, a list of the supported methods with examples. I need to unmount and reset the drop in in the client and think Iv'e done it, but I'd like to be certain.
Cheers

**Comment by BrettButcher** [comment]
Sorry, I forgot to mention, I am using Adyen 9.2.1 library. Thanks

**Comment by Kwok-he-Chu** [comment]
When receiving the webhooks in the adyen-examples, we're using the [ApiController]-annotation and the [HttpPost("...")] for the route itself, see: https://github.com/adyen-examples/adyen-dotnet-online-payments/blob/main/checkout-example/Controllers/WebhookController.cs#L27-L28 

In order for the deserialization to happen correctly, we're registering the correct serializer (https://github.com/adyen-examples/adyen-dotnet-online-payments/blob/main/checkout-example/Startup.cs#L50)`.AddNewtonsoftJson()` in our DI-container. 

This is likely why your notificationItemContainers empty, please let me know if this solved your issue.

**Comment by jillingk** [comment]
Hi @BrettButcher,

Were you able to fix this issue with @Kwok-he-Chu's proposed solution?

Best, Jilling
Adyen

**Comment by BrettButcher** [comment]
> Hi @BrettButcher,
> 
> Were you able to fix this issue with @Kwok-he-Chu's proposed solution?
> 
> Best, Jilling Adyen

Hi @jillingk ... sorry for not getting back sooner. I didn't see the notification till I came back to post a new issue...

I am afraid I didn't because by the time I I saw @Kwok-he-Chu 's solution, I had already soved it by generating my own object and reading into that.

I do think that the dependency on NewtonSoft Json could be part of the problem here. Most .NET devs are now using system.text.json as its pretty much built in and 'just works' if objects are set up correctly.

I posted another comment on here for a different issue, where now, in V10 i am having problems in the other direction.

I am going to try ther NewtonSoft Libs, and if that doesn't work, Im going back to V9.X which I did make work...
Cheers

**Comment by AlexandrosMor** [comment]
Hello @BrettButcher, 

Do you have any updates ? Is the v10 with `NewtonSoft` worked for you ?

kind regards,
Alexandros
Adyen

**Comment by BrettButcher** [comment]
> Hello @BrettButcher,
> 
> Do you have any updates ? Is the v10 with `NewtonSoft` worked for you ?
> 
> kind regards, Alexandros Adyen

Hi Alexandros,
I'm afraid it didn't so I went back to the V9.XX libs where it worked. We are going through the hoops to see if we can get an Adyen account atm so I won't be re-visiting this till the business side is sorted. 
Cheers
Brett
