### ISSUE TITLE
IPaymentMethodDetails Issue - Version 5.4

### ISSUE THREAD

**Issue by bsulliva** [Adyen/adyen-dotnet-api-library#796]
**Describe the bug**
Hello, I'm using an older version of this library, version 5.4. I have two issues, one is I'm not able to deserialize into a PaymentRequest object from the Adyen web components state.data object.

The state.data object is:
{"riskData":{"clientData":"eyJ2ZXJzaW9uIjoiMS4wLjAiLCJkZXZpY2VGaW5nZXJwcmludCI6IkRwcXdVNHpFZE4wMDUwMDAwMDAwMDAwMDAwTGxEeVo0OW5qRDAwNTAyNzE1NzZjVkI5NGlLekJHZFpzZWVkSWVPTkJpeDdSWDNhejgwMDJ6aVRHVnhNRDdrMDAwMDBxWmtURTAwMDAwZjFWbGtxVzR2WEs0eVJEYU1zZ3U6NDAiLCJwZXJzaXN0ZW50Q29va2llIjpbXSwiY29tcG9uZW50cyI6eyJ1c2VyQWdlbnQiOiJmMTkwZTM1YzZhNTNhOGUzZTJiYmFkYzdkNzQwNjc4YiIsIndlYmRyaXZlciI6MCwibGFuZ3VhZ2UiOiJlbi1VUyIsImNvbG9yRGVwdGgiOjI0LCJkZXZpY2VNZW1vcnkiOjgsInBpeGVsUmF0aW8iOjEuMTAwMDAwMDIzODQxODU4LCJoYXJkd2FyZUNvbmN1cnJlbmN5IjoxMiwic2NyZWVuV2lkdGgiOjE5MjAsInNjcmVlbkhlaWdodCI6MTA4MCwiYXZhaWxhYmxlU2NyZWVuV2lkdGgiOjE5MjAsImF2YWlsYWJsZVNjcmVlbkhlaWdodCI6MTA0MCwidGltZXpvbmVPZmZzZXQiOjMwMCwidGltZXpvbmUiOiJBbWVyaWNhL0NoaWNhZ28iLCJzZXNzaW9uU3RvcmFnZSI6MSwibG9jYWxTdG9yYWdlIjoxLCJpbmRleGVkRGIiOjEsImFkZEJlaGF2aW9yIjowLCJvcGVuRGF0YWJhc2UiOjEsInBsYXRmb3JtIjoiV2luMzIiLCJwbHVnaW5zIjoiMjljZjcxZTNkODFkNzRkNDNhNWIwZWI3OTQwNWJhODciLCJjYW52YXMiOiJhNmM5YTM1MzNjYTFjMmEzNWI2MWEwNzM5MGNiYzQ0NSIsIndlYmdsIjoiNGMwNzUzMjdkZjM2YjJmOTdiMTQwZDJmZGVmNjRhZmQiLCJ3ZWJnbFZlbmRvckFuZFJlbmRlcmVyIjoiR29vZ2xlIEluYy4gKEludGVsKX5BTkdMRSAoSW50ZWwsIEludGVsKFIpIElyaXMoUikgWGUgR3JhcGhpY3MgRGlyZWN0M0QxMSB2c181XzAgcHNfNV8wLCBEM0QxMSkiLCJhZEJsb2NrIjowLCJoYXNMaWVkTGFuZ3VhZ2VzIjowLCJoYXNMaWVkUmVzb2x1dGlvbiI6MCwiaGFzTGllZE9zIjowLCJoYXNMaWVkQnJvd3NlciI6MCwiZm9udHMiOiI0MWMzN2VlN2EyNzE1MmVkOGZhNGIzZTZmMjM0OGIxYiIsImF1ZGlvIjoiOTAyZjBmZTk4NzE5Yjc3OWVhMzdmMjc1MjhkZmIwYWEiLCJlbnVtZXJhdGVEZXZpY2VzIjoiNWYzZmRhZjQ3NDNlYWE3MDdjYTZiN2RhNjU2MDM4OTIifX0="},"paymentMethod":{"type":"paypal","subtype":"sdk","BrowserInfo":{"AcceptHeader":"","ColorDepth":24,"JavaEnabled":false,"Language":"en-US","ScreenHeight":1080,"ScreenWidth":1920,"TimeZoneOffset":300,"UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48","JavaScriptEnabled":true},"additionalData":{"RequestedTestAcquirerResponseCode":null}}}

The code I'm using to deserialize:
var requestObj = JsonConvert.DeserializeObject<PaymentRequest>(request);

The error is:
Newtonsoft.Json.JsonSerializationException: 'Could not create an instance of type Adyen.Model.Checkout.IPaymentMethodDetails. Type is an interface or abstract class and cannot be instantiated. Path 'paymentMethod.type', line 1, position 1530.'

The second issue is when I post a PaymentRequest type to my API, PaymentMethod is always null.

My request body is:
{"channel":"Web","shopperInteraction":"Ecommerce","additionalData":{"RequestedTestAcquirerResponseCode":null},"amount":{"currency":"USD","value":969},"applicationInfo":{"adyenLibrary":{"name":"adyen-dotnet-api-library","version":"5.4.0"}},"billingAddress":{"city":"Fort Worth","country":"US","houseNumberOrName":"NA","postalCode":"76102","stateOrProvince":"TX","street":"1000 N Main"},"browserInfo":{"acceptHeader":"application/json, text/javascript, */*; q=0.01","colorDepth":24,"javaEnabled":false,"language":"en-US","screenHeight":720,"screenWidth":1280,"timeZoneOffset":300,"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.39","javaScriptEnabled":true},"countryCode":"US","deliveryAddress":{"city":"Mansfield","country":"US","houseNumberOrName":"NA","postalCode":"76063","stateOrProvince":"TX","street":"1000 N Main"},"merchantAccount":"","paymentMethod":{"subtype":"sdk","type":"paypal"},"reference":"A638172904618281869","returnUrl":https://www.mouserdev.com:44333/myaccount/verifyadyenredirectresponse,"shopperEmail":[barry.sullivan@mouser.com](mailto:barry.sullivan@mouser.com),"shopperIP":"127.0.0.1","shopperReference":"884680","telephoneNumber":"817-804-3587"}

My c# code is this, but paymentRequest.PaymentMethod is always null.
public string Payment([FromBody] PaymentRequest paymentRequest)

**Comment by jillingk** [comment]
Hi @bsulliva,

Thanks for reaching out to us here. I'm actually not sure what the problem is, seen as the library version you're using is quite old. I could look into it for you, but then if it's a bug we'd rather not fix it as we try to proactively fix things by releasing new versions and not support older versions. Also the checkout version that this version uses is quite old (v51), so I really do recommend an upgrade! 

If there is a big reason that prevents you from upgrading, let me know and we can figure out the migration process or look into a way to still use the older version.

Best, Jilling
Adyen

**Comment by bsulliva** [comment]
Hi @jillingk, the main reason I was looking into using an older version is to save time. I wanted to see what is the minimum amount of work we need to do do add PayPal. I'm trying to prevent a complete re-write of the Adyen implementation with the new /sessions flow. If you have suggestions on exactly which SDK and API SDK to upgrade to where we don't have to do a complete re-write let me know. Or we need to connect on zoom to clear things up, we can do that too. Thanks
