### ISSUE TITLE
Klarna not not adhering to api documentation in 10.1.0 

### ISSUE THREAD

**Issue by marcuslonnerstrand** [Adyen/adyen-dotnet-api-library#826]
**Describe the bug**
When omitting to set a shopper name in the payment request we get the response:
`Object 'shopperName' is not valid. Reason: The name is not provided, or the first or last name is missing.`
Looking at the [documentation](https://docs.adyen.com/payment-methods/klarna/web-component?tab=_code_payments_code__2) this field is not required and it worked without the shoppername in the previous sdk version (9.2.1).
If we hardcode shoppername we get the response:
`"117 Field 'billingAddress' is not valid.` which is also not a required field. 
So I think the SDK is doing something with these fields that causes the validation to fail when it's sent over to adyen.

**To Reproduce**

_In test environment:_
No particular steps are necessary to reproduce this from our testing, everytime shoppername is omitted or null in the payment request we get this error. Same with any other non - required field. It seems like the validation looks at them one by one and responds with an error on the first one missing. So all non-required fields might have this behaviour.

**Expected behavior**
All non-required fields should be able to be omitted without errors when using Klarna.

**Comment by marcuslonnerstrand** [comment]
I've gotten it working now by setting the fields `StorePaymentMethod` , `RecurringProcessingModel`, `ShopperInteraction`. So when omitting these fields I get errors for validation on other none required fields. 
Either way it's working so I'm happy. But I still think there's something off with the error messages considering I got errors on `shopperName` not valid when omitting  `StorePaymentMethod` , `RecurringProcessingModel`, `ShopperInteraction`.

You can decide if you want to look into it I guess.

**Comment by marcuslonnerstrand** [comment]
closed this as I thought we thought we got it working but we were mistaken, it's still an issue.

**Comment by jillingk** [comment]
Hi @marcuslonnerstrand,

I'm sorry to hear this issue persisted! I just played around with it a bit myself and I didn't really get the API error you described. Could you perhaps send me the request you're sending so I can recreate the issue on my side? 

As for the required fields, I believe technically they can be dependent on the specific payment method your implementing. That is, klarna might require some fields that are not set required in the API explorer. 

Best, Jilling
Adyen

**Comment by marcuslonnerstrand** [comment]
@jillingk thanks for reaching out. Here's an example of what is created by the SDK:

```
{
   "Channel":null,
   "EntityType":null,
   "IndustryUsage":null,
   "RecurringProcessingModel":"Subscription",
   "ShopperInteraction":"Ecommerce",
   "AccountInfo":null,
   "AdditionalAmount":null,
   "AdditionalData":[
      "(""riskdata.storePaymentDetailsAsRecurring":"True"")"
   ],
   "Amount":"Amount"{
      "Currency":"SEK",
      "Value":0
   },
   "ApplicationInfo":null,
   "AuthenticationData":null,
   "BillingAddress":null,
   "BrowserInfo":null,
   "CaptureDelayHours":null,
   "CheckoutAttemptId":null,
   "Company":null,
   "ConversionId":null,
   "CountryCode":"SE",
   "DateOfBirth":"01/01/0001 00":"00":00,
   "DccQuote":null,
   "DeliveryAddress":null,
   "DeliveryDate":"01/01/0001 00":"00":00,
   "DeviceFingerprint":null,
   "EnableOneClick":false,
   "EnablePayOut":false,
   "EnableRecurring":false,
   "FraudOffset":null,
   "Installments":null,
   "LineItems":[
      "LineItem"{
         "AmountExcludingTax":0,
         "AmountIncludingTax":0,
         "Brand":null,
         "Color":null,
         "Description":"Storytel Unlimited",
         "Id":"70c731c5-f027-40f5-9437-663ea245cfcf-1",
         "ImageUrl":"https://static.storytel.net/klarna/UNLIMITED",
         "ItemCategory":null,
         "Manufacturer":null,
         "ProductUrl":null,
         "Quantity":1,
         "ReceiverEmail":null,
         "Size":null,
         "Sku":null,
         "TaxAmount":0,
         "TaxPercentage":3500,
         "Upc":null
      }
   ],
   "LocalizedShopperStatement":null,
   "Mandate":null,
   "Mcc":null,
   "MerchantAccount":"StorytelSE",
   "MerchantOrderReference":null,
   "MerchantRiskIndicator":null,
   "Metadata":null,
   "MpiData":null,
   "Order":null,
   "OrderReference":null,
   "Origin":null,
   "PaymentMethod":"CheckoutPaymentMethod"{
      "ActualInstance":"KlarnaDetails"{
         "Type":"Klarna",
         "BillingAddress":null,
         "CheckoutAttemptId":null,
         "DeliveryAddress":null,
         "PersonalDetails":null,
         "RecurringDetailReference":null,
         "StoredPaymentMethodId":null
      },
      "IsNullable":false,
      "SchemaType":"oneOf"
   },
   "PlatformChargebackLogic":null,
   "RecurringExpiry":null,
   "RecurringFrequency":null,
   "RedirectFromIssuerMethod":null,
   "RedirectToIssuerMethod":null,
   "Reference":"70c731c5-f027-40f5-9437-663ea245cfcf",
   "ReturnUrl":"https://checkout-test.storytel.com/api/payment/adyen/v2/complete?orderNumber=1368ff8f-cdac-419e-8a6c-3e182963413f&countryIso=SE&languageIso=sv&returnHash=A9954BEBB8D0992440B28D454A9C77AF1694F4E16801B7002B2402C24AD0FF4A&origin=test05.storytel.com&transactionId=70c731c5-f027-40f5-9437-663ea245cfcf",
   "RiskData":null,
   "SessionValidity":null,
   "ShopperEmail":"marcus.lonnerstrand+klarnismo@storytel.com",
   "ShopperIP":"85.226.24.139",
   "ShopperLocale":null,
   "ShopperName":null,
   "ShopperReference":"621ed09e-fd91-4a68-b3e6-0fcafe3c0a98",
   "ShopperStatement":null,
   "SocialSecurityNumber":null,
   "Splits":null,
   "Store":null,
   "StorePaymentMethod":true,
   "TelephoneNumber":null,
   "ThreeDS2RequestData":null,
   "ThreeDSAuthenticationOnly":false,
   "TrustedShopper":false
},
"StorePaymentDetailsAsRecurring":true,
"TransactionId":"70c731c5-f027-40f5-9437-663ea245cfcf",
"StoreId":"STHP-SE",
"TotalAmount":"Money"{
   "Currency":"SEK",
   "Amount":0.0000
},
"CountryCode":"SE",
"PaymentDetailsId":"621ed09e-fd91-4a68-b3e6-0fcafe3c0a98",
"PaymentMethod":"klarna_paynow",
"PaymentMethodCategory":"klarna",
"ActivityId":"1182713",
"OrderSummary":"Storytel Unlimited",
"ReturnUri":"https"://checkout-test.storytel.com/api/payment/adyen/v2/complete?orderNumber=1368ff8f-cdac-419e-8a6c-3e182963413f&countryIso=SE&languageIso=sv&returnHash=A9954BEBB8D0992440B28D454A9C77AF1694F4E16801B7002B2402C24AD0FF4A&origin=test05.storytel.com&transactionId=70c731c5-f027-40f5-9437-663ea245cfcf,
"Email":"marcus.lonnerstrand+klarnismo@storytel.com",
"IpAddress":"85.226.24.139"
}
```

So we're using the `PaymentsService` which calls the  `/payments`  endpoint
(Also wanted to add that we've used klarna for a few years all with the SDK, so this is something that stopped working in the 10.0.0-10.1.0 version, it has worked in all versions before that, waaaay back)

**Comment by marcuslonnerstrand** [comment]
And this is what happens currently:

`Adyen.HttpClient.HttpClientException: 422: UnprocessableEntity, ResponseBody: {"status":422,"errorCode":"119","message":"Object 'shopperName' is not valid. Reason: The name is not provided, or the first or last name is missing.","errorType":"validation","pspReference":"MMS4BB7G36PFWR82"}`

**Comment by jillingk** [comment]
Hi @marcuslonnerstrand,

I'm looking at your request and I'm a bit surprised by all the null values in your serialized request. What setup are you running? Because for me the request do not look like that at all and uninitialised params in the payment request will get omitted.

**Comment by marcuslonnerstrand** [comment]
> Hi @marcuslonnerstrand,
> 
> I'm looking at your request and I'm a bit surprised by all the null values in your serialized request. What setup are you running? Because for me the request do not look like that at all and uninitialised params in the payment request will get omitted.

I see, maybe you're looking at what's actually sent out - I don't have any good logs of that so what I sent you was a serialized log of  the `PaymentRequest.cs` that's in the `Adyen.Model.Checkout` namespace. 
We pass the `PaymentRequest` to the `PaymentsService` and I haven't looked into what adyen does at that point. Maybe the fields are omitted and not sent to the api. 

I can see this code
```
    public async Task<PaymentResponse> PaymentsAsync(
      PaymentRequest paymentRequest,
      RequestOptions requestOptions = null,
      CancellationToken cancellationToken = default (CancellationToken))
    {
      PaymentsService paymentsService = this;
      string endpoint = paymentsService._baseUrl + "/payments";
      return await new ServiceResource((AbstractService) paymentsService, endpoint).RequestAsync<PaymentResponse>(paymentRequest.ToJson(), requestOptions, new HttpMethod("POST"), cancellationToken).ConfigureAwait(false);
    }

```

And maybe the `ToJson()` is supposed to remove the null fields. 
But then the question is why we get this error? 👀

**Comment by jillingk** [comment]
Hi @marcuslonnerstrand,

Okay the null values make sense now. Perhaps to double check you can debug this by going into the library and setting a break point on the ```paymentRequest.ToJson()``` line, just to verify the serialization is not messing up the actual API call. 

I'm running the code now and it seems to work on my end. Two things; could you perhaps remove the ```new()``` and replace this with ```new LineItem```? I don't think it should matter but our library runs a version that does not support this feature so just to rule it out. The second thing I'm wondering is what serialization depedency you're using, since this library uses newtonsoft sometimes that causes some errors using frameworks that use the default (system.text). Let me know :)

**Comment by marcuslonnerstrand** [comment]
So this is what ToJson generates if I run the above request locally in debug:
(I omitted the riskdata because I assume that shouldn't affect things)

```
{
  "recurringProcessingModel": "Subscription",
  "shopperInteraction": "Ecommerce",
  "amount": {
    "currency": "SEK",
    "value": 0
  },
  "countryCode": "SE",
  "lineItems": [
    {
      "amountExcludingTax": 0,
      "amountIncludingTax": 0,
      "description": "Storytel Unlimited",
      "id": "70c731c5-f027-40f5-9437-663ea245cfcf-1",
      "imageUrl": "https://static.storytel.net/klarna/UNLIMITED",
      "quantity": 1,
      "taxAmount": 0,
      "taxPercentage": 3500
    }
  ],
  "merchantAccount": "StorytelSE",
  "paymentMethod": {"type":"klarna"},
  "reference": "70c731c5-f027-40f5-9437-663ea245cfcf",
  "returnUrl": "https”://checkout-test.storytel.com/api/payment/adyen/v2/complete?orderNumber=1368ff8f-cdac-419e-8a6c-3e182963413f&countryIso=SE&languageIso=sv&returnHash=A9954BEBB8D0992440B28D454A9C77AF1694F4E16801B7002B2402C24AD0FF4A&origin=test05.storytel.com&transactionId=70c731c5-f027-40f5-9437-663ea245cfcf",
  "shopperEmail": "marcus.lonnerstrand+klarnismo@storytel.com",
  "shopperIP": "85.226.24.139",
  "shopperReference": "621ed09e-fd91-4a68-b3e6-0fcafe3c0a98",
  "storePaymentMethod": true
}
```

So the null values are indeed omitted but that leaves the question why do we get this error back. Could there be something with the test environment? 👀 

We're using Netwonsoft as well!

**Comment by marcuslonnerstrand** [comment]
Any news @jillingk? 👀

**Comment by marcuslonnerstrand** [comment]
I figured it out! 

I didn't notice that klarna had multiple types now when you introduced the new `CheckoutPaymentMethod`
We are using the type `klarna_paynow` but the KlarnaDetails defaults to the type `klarna`. A sneaky one but nothings wrong with the SDK or API then! 😄 It would be nice if you could bring back the old model where we just define the type directly though instead of these concrete classes like `KlarnaDetails`. 

But it works, so I'm closing this. 

Thank you!
