### ISSUE TITLE
Outdated code snippet in docs.

### ISSUE THREAD

**Issue by andreysarafanov** [Adyen/adyen-dotnet-api-library#830]
The C# code snippet [here](https://docs.adyen.com/development-resources/webhooks/verify-hmac-signatures?tab=codeBlockhmac_validation_IpzsD_cs_3#hmac_validation) is outdated:

```
var notificationHandler = new NotificationHandler();
var handleNotificationRequest = notificationHandler.HandleNotificationRequest(notificationRequestJson);
```

But the `HandleNotificationRequest` method is now in `WebhookHandler` and `NotificationHandler` doesn't exist.

**Comment by jillingk** [comment]
Hi @andreysarafanov,

Thanks a lot for reaching out to us here! We are aware of this and are currently in the process of updating the code snippets on our documentation. Apologies for the confusion this might have caused you! 

Best, Jilling 
Adyen
