### ISSUE TITLE
Endpoint configuration overwritten when Client is created (10.x)

### ISSUE THREAD

**Issue by jonekdahl** [Adyen/adyen-dotnet-api-library#833]
**Describe the bug**
When providing a custom value for `Config.Endpoint` the value is being overwritten when the Client instance is created. 

**To Reproduce**

```fsharp
// Put the following code in repro.fsx and run it with 'dotnet fsi repro.fsx'
#r "nuget: Adyen, 10.1.0"

open Adyen

let config = Config(
    Endpoint = "https://192.168.1.10:8443/nexo"
    )

let client = Client(config)

printfn $"Endpoint: %s{client.Config.Endpoint}"
```

Output:
```
Endpoint: https://pal-test.adyen.com
```

**Expected behavior**

```fsharp
#r "nuget: Adyen, 9.2.1"

open Adyen

let config = Config(
    Endpoint = "https://192.168.1.10:8443/nexo"
    )

let client = Client(config)

printfn $"Endpoint: %s{client.Config.Endpoint}"
```

Output:
```
Endpoint: https://192.168.1.10:8443/nexo
```

**Comment by jonekdahl** [comment]
Hi @jillingk! The use case was indeed the local terminal API and I do get the expected behavior with `LocalTerminalApiEndpoint`. I don't see this mentioned in the  [migration guide for 10.x](https://adyen.medium.com/upgrading-to-adyen-net-library-10-0-0-40df79b3f14f), perhaps it would be a good to add it there?

As a side note, I think the current behavior is slightly confusing since it allows you to specify a value for `Endpoint` in the Config that is ignored/overwritten later.

**Comment by Kwok-he-Chu** [comment]
@jonekdahl I've updated the migration guide, thank you for the suggestion! 

>  I think the current behavior is slightly confusing since it allows you to specify a value for Endpoint in the Config that is ignored/overwritten later.

I agree. Do you have a proposal on how to structure it better to improve the overall developer experience?


@jillingk We can make a nice improvement here, can you create a ticket? ^

**Comment by jonekdahl** [comment]
Hi @Kwok-he-Chu, sorry for not getting back sooner, but I've been on vacation.

I don't have any specific design to improve this, the important thing is that provided configuration is not ignored/overwritten. If `Endpoint` and other similar properties are not supposed to be configured in this way, perhaps you should introduce a new configuration type without those properties.
