### ISSUE TITLE
Missing CancelOrRefund from PaymentsService

### ISSUE THREAD

**Issue by RyanONeill1970** [Adyen/adyen-dotnet-api-library#838]
**CancelOrRefund is not present on PaymentsService concrete class**
Trying to upgrade from 9 to 10 and the modification service has been subsumed into the payments service, which is fine.
The CancelOrRefund method that exists on IPaymentsService has not been implemented by the PaymentsService and IPaymentsService does not include CancelOrRefund in the current release.

Similarly with Capture, I'm sure there are other methods missing as well but I've not got to those yet.

The notes say the method is supposed to be there, am I missing anything?

From what I can see, the current version is not usable for my needs.

**Comment by RyanONeill1970** [comment]
OK, I've realised what is going on now, there are two classes PaymentService and PaymentsService. Is one obsolete or perhaps not well named?

**Comment by wboereboom** [comment]
Hi @RyanONeill1970,

Thanks for raising this issue. The mixup is understandable. The `PaymentService` is a service representing our [Classic Payment Integration](https://docs.adyen.com/api-explorer/Payment/68/overview).
the `PaymentsService` is a subclass of the `Checkout` Package, and it is part of our [Checkout API](https://docs.adyen.com/api-explorer/Checkout/70/overview).
The modifications endpoints can be found in the `ModificationsService` class, which is also a subclass of Checkout.

We try to stick to the structure in our API explorer (see links to that above). We actually use the same openApi specifications as a source, so they should always closely match each other.
I hope this resolves any confusion the migration has caused.

Please let me know if we can be of further assistance.

Kind Regards,
Wouter
Adyen
