### ISSUE TITLE
v10 isn't supported with Azure Functions v4 in-proc model

### ISSUE THREAD

**Issue by JSCProjects** [Adyen/adyen-dotnet-api-library#839]
Version 10 has a reference to Microsoft.Extensions.Http v7 and this has deeper references to Microsoft.Extensions assemblies with v7. This prevents us to implement v10 within our Azure Functions v4 running in a in-proces model. According to this [comment](https://github.com/Azure/azure-functions-host/issues/8984#issuecomment-1571075265) v7 versions aren't supported.

Is it possible that Adyen is using a minimal version of v6. So there is a higher adoption for companies who want to use this sdk and have their Azure Functions v4 with a in-proc model.

Thanx in advance

**Comment by wboereboom** [comment]
Hi @JSCProjects ,

Sorry for the slow response.
We've looked into trying to reproduce on Azure Functions, but poor documentation and limited time forced us to abort the investigation.

Trying to understand the issue at hand here:
Are you suggesting that Microsoft.Extensions.Http v7 uses .Net 7.0 under the hood, which is not supported in Azure functions? The documentation for the dependency suggests it should be compatible with .Net 6.0.

Kind Regards,
Wouter
Adyen

**Comment by wboereboom** [comment]
Hi @JSCProjects ,

Sorry for the slow response.
We've looked into trying to reproduce on Azure Functions, but poor documentation and limited time forced us to abort the investigation.

Trying to understand the issue at hand here:
Are you suggesting that Microsoft.Extensions.Http v7 uses .Net 7.0 under the hood, which is not supported in Azure functions? The documentation for the dependency suggests it should be compatible with .Net 6.0.

Kind Regards,
Wouter
Adyen

**Comment by JSCProjects** [comment]
Hi Wouter,

Short answer is that v7 isn't supported by Azure Functions (in-proc). For deeper analysis we should ask Microsoft, why some assemblies have dependencies which doesn't work with Azure Functions (in-proc).

To support Adyen we forked your code and changed v7 to v6 versions and everything still functions as expected.

Greetz,

Joey
________________________________
Van: Wouter Boereboom ***@***.***>
Verzonden: Wednesday, August 30, 2023 11:58:29 AM
Aan: Adyen/adyen-dotnet-api-library ***@***.***>
CC: JSC Projects ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Adyen/adyen-dotnet-api-library] v10 isn't supported with Azure Functions v4 in-proc model (Issue #839)


Hi @JSCProjects<https://github.com/JSCProjects> ,

Sorry for the slow response.
We've looked into trying to reproduce on Azure Functions, but poor documentation and limited time forced us to abort the investigation.

Trying to understand the issue at hand here:
Are you suggesting that Microsoft.Extensions.Http v7 uses .Net 7.0 under the hood, which is not supported in Azure functions? The documentation for the dependency suggests it should be compatible with .Net 6.0.

Kind Regards,
Wouter
Adyen

**Comment by wboereboom** [comment]
Hi @JSCProjects ,

I'm not sure I have fully understood the answer.
Is  `Microsoft.Extensions.Http` v7 not available in Azure functions?
Or is this dependency somehow using some feature which is not available in .Net 6?

If it is the former; How is it possible that our library **is** available through Nuget on Functions, but `Microsoft.Extensions.Http` is not?

Sorry for all the questions, I'm just trying to understand the problem at hand.

Kind Regards,
Wouter
Adyen

**Comment by jillingk** [comment]
Hey @JSCProjects,

I think we can safely downgrade to v6, as it does not seem we use any of the functionalities of http v7 anyways. Let me discuss this and I'll get back to you!

Best, Jilling
Adyen
