### ISSUE TITLE
[ITT-628] LiveEndpointUrlPrefix with Local Terminal API

### ISSUE THREAD

**Issue by summitMaximilian** [Adyen/adyen-dotnet-api-library#842]
**Describe the bug**
After upgrading to Version 10.1 (from 9.1) an Exception is thrown if LiveEndpointUrlPrefix is not set in the Config. Is this value now necessary for the Local Terminal API?

**Comment by AlexandrosMor** [comment]
Hello @summitMaximilian,

The url for the local terminal api should be passed using the Config object. Are you setting it similar to the [example](https://github.com/Adyen/adyen-dotnet-api-library#using-the-local-terminal-api) ? 

kind regards,
Alexandros
Adyen

**Comment by summitMaximilian** [comment]
Hi!

I am following the example. With Model.Environment.Test everything works, but with Model.Environment.Live I get the mentioned Exception. I think the problem lies in the difference of "Client.cs":

In version 9.1 "SetEnvironment" was not called in the constructor:

`  public Client(Config config)
        {
            Config = config;
        }`

But in version 10.1:

`  public Client(Config config)
        {
            Config = config;
            SetEnvironment(Config.Environment, Config.LiveEndpointUrlPrefix);
            HttpClient = new HttpClientWrapper(Config, GetHttpClient());
        }`

This change forces me to set LiveEndpointUrlPrefix in the Config.

**Comment by AlexandrosMor** [comment]
Hey,

This looks like a bug from our side. I will open an internal ticket to fix that. Adding a dummy `LiveEndpointUrlPrefix` works and you are able to make a transaction right ? Maybe this could be a temp solution until we fix it and make a release. 

kind regards,
Alexandros
Adyen

**Comment by summitMaximilian** [comment]
Hi!

I was not able to perform a transaction, because in Version 10.1 the default HttpClient does not get its `ServerCertificateCustomValidationCallback `set, so I get a `RemoteCertificateNameMismatch` Error. 

This was fixed with #837. But I am going to inject my own HttpClient (which I should do anyway). Now the transactions works fine (on `Test`).

I could not test it on `Live ` so far. 

Kind Regards
Maximilian
