### ISSUE TITLE
Remove property validation in PaymentSessionRequest

### ISSUE THREAD

**Issue by MatijaSestak** [Adyen/adyen-dotnet-api-library#86]
Hi,
in class  PaymentSessionRequest in constructor is validation logic for some class properties. So when I want to create a new PaymentSessionRequest  then I need to specify all properties via constructor although I need to set only several properties.

Could you put validation logic somewhere else?

**Comment by AlexandrosMor** [comment]
Hey @MatijaSestak,

All the parameters that we validate are required as you can check from teh [adyen doc](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v41/paymentSession)

Kind regards,

**Comment by MatijaSestak** [comment]
Ok.
