### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by guibranco** [Adyen/adyen-dotnet-api-library#87]
Request to build the application with current commit to the nuget.org.

The package was last update 2 months ago, last PR was 5 days ago...

Also submitted request by email, that created a ticket on Adyen's support system

https://support.adyen.com/hc/en-us/requests/754478

**Comment by AlexandrosMor** [comment]
Hello @guibranco,

Version 2.0.2 is released on nuget.  https://www.nuget.org/packages/Adyen.EcommLibrary/

regards,
Alexandros
