### ISSUE TITLE
Exception when generating a new API key for existing API credentials

### ISSUE THREAD

**Issue by mpoelman** [Adyen/adyen-dotnet-api-library#881]
**Describe the bug**
I'm using SDK version v11.1.0 to generate a new API key for existing API credentials. 

However, the call to APIKeyCompanyLevelService.GenerateNewApiKey throws the following exception:

```
System.ArgumentNullException: 'Value canot be null.
Parameter name: content'
```

If I use Postman to execute the request (with exactly the same path parameters), a 200 OK is returned (and a new API key as well).

**To Reproduce**
Install SDK version 11.1.0, and use the APIKeyCompanyLevelService to generate a new API key.
SDK version 10.1.0 has this problem as well.

**Expected behavior**
No exception being thrown, and a new API key.

**Comment by jillingk** [comment]
Hi @mpoelman,

Thanks for reaching out to us with this issue you are encountering. I've pinpointed the issue and opened a quick PR to fix it! We will be sure to include this fix in the scheduled release for next Monday. 

Best, Jilling
Adyen

**Comment by AlexandrosMor** [comment]
Hello @mpoelman,

This is fixed and released in the [latest version ](https://github.com/Adyen/adyen-dotnet-api-library/releases/tag/v11.1.1)
