### ISSUE TITLE
Notification namespace missing in last release 11.1.2

### ISSUE THREAD

**Issue by edika99** [Adyen/adyen-dotnet-api-library#897]
I've just installed the 11.1.2 from nuget and the namespace Notification is missing so the NotificationHandler class is not available and the webhook example from the Adyen site does not work.

Am i missing something or is this a nuget publish error?

**Comment by Aleffio** [comment]
Hi @edika99 and thanks for reaching out,

You are correct, the webhook example is not up to date unfortunately.

The `NotificationHandler` class has been renamed to `WebhookHandler`: https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Webhooks/WebhookHandler.cs in version 10.0.0 of this library.

Can you please use `WebhookHandler` with namespace `Webhooks` instead?
We will fix our example asap, sorry for the inconvenience.

Regards,
Alessio
Adyen

**Comment by edika99** [comment]
Thanks Alessio,

in the meantime I was simply replaced the handler with JsonOperation.Deserialize<NotificationRequest>(jsonRequest);

Regards 

Edika

**Comment by peymannj** [comment]
@Aleffio The example hasn't been updated yet :)
