### ISSUE TITLE
Support for error condition "Communication timeout"

### ISSUE THREAD

**Issue by jonekdahl** [Adyen/adyen-dotnet-api-library#915]
**Is your feature request related to a problem? Please describe.**

I am reading the docs on payment terminal error handling, more specifically the chapter on [processing time-out](https://docs.adyen.com/point-of-sale/error-scenarios/pos-timeouts/#processing-time-out).

The docs state that the error condition in this case will be "Communication timeout" but that error condition doesn't seem to be represented in [ErrorConditionType](https://github.com/Adyen/adyen-dotnet-api-library/blob/554799e29ca0f1f29b90e484ca4c9474dabb8a03/Adyen/Model/Nexo/ErrorConditionType.cs#L6) in this library.

Is the documentation incorrect or has the processing time-out scenario not been implemented in this library?

**Describe the solution you'd like**
Assuming the docs are correct I would like "Communication timeout" to be represented as an error condition. 

**Describe alternatives you've considered**
I don't see any other good alternatives. Frankly I don't know what would happen if I would get a response with "Communication timeout" as the error condition, I assume the XML deserialization would fail?!

**Comment by jonekdahl** [comment]
I opened an issue with Adyen support to ask for clarification on this and they responded that a "Communication timeout" might surface as error condition `UnreachableHost` in the .NET SDK. Can this be confirmed by someone who works on the .NET SDK? 

The [documentation](https://docs.adyen.com/point-of-sale/error-scenarios/refusal-reasons-pos/#error-condition-unreachable) for UnreachableHost states that this error condition occurs when _"It's not possible to contact the shopper's bank to authorise the transaction."_. It's not clear to me whether this is the same scenario as "Communication timeout" or not.

**Comment by jillingk** [comment]
Hi @jonekdahl,

Thanks for reaching out and apologies for the not so timely response! 

The `Communication timeout` response seems wrong to me as well, based on the enum types structure we would not have this sort of casing with a space in between. I suppose the responses would adhere to the type values we have in the library and the docs in this case are wrong. I just checked a very up to date specification of our internal terminal API and it seems to be identical to the values we have for the enum, so I think we can safely assume the sdk would be up to date!

I'll reach out to our docs team to fix their documentation.

I think you can safely

**Comment by jillingk** [comment]
Hi @jonekdahl,

Yes looking at [this doc page](https://docs.adyen.com/point-of-sale/error-scenarios/refusal-reasons-pos/#error-condition-unreachable) we can be quite certain these will be the responses. Let me know if you run into anything else integrating the terminal API. 

Best, Jilling
Adyen

**Comment by jonekdahl** [comment]
Thanks for confirming @jillingk. Closing this issue now but I'll be sure to let you know if we run into any other issues.
