### ISSUE TITLE
This should be AllowedOriginResponse (CompanyLevel)

### ISSUE THREAD

**Issue by jellevdv** [Adyen/adyen-dotnet-api-library#924]
Shouldn't this be 'AllowedOriginResponse' instead of 'AllowedOrigin**s**Response' ? The serializer can't seem to deserialize the response body because it only returns 1 'AllowedOriginResponse' instead of a list of 'AllowedOriginResponse' like in the  'AllowedOrigin**s**Response' class. (Same for the async method)

https://github.com/Adyen/adyen-dotnet-api-library/blob/1d676a90573bf11e96e7ad1cfbb361a463b197c4/Adyen/Service/Management/AllowedOriginsCompanyLevelService.cs#L157

**Comment by dietermijle** [comment]
+1

I see that its already wrong in the Swagger definition on https://github.com/Adyen/adyen-openapi/blob/main/json/ManagementService-v1.json too!

The swagger definition indicates a response of type `AllowedOriginsResponse` which is an array of ´AllowedOrigin` objects:
`"AllowedOriginsResponse": {
        "properties": {
          "data": {
            "description": "List of allowed origins.",
            "items": {
              "$ref": "#/components/schemas/AllowedOrigin"
            },
            "type": "array"
          }
        },
        "type": "object"
      }`

But the documentation states a response of a single `AllowedOrigin`, see https://docs.adyen.com/api-explorer/Management/1/post/merchants/_merchantId_/apiCredentials/_apiCredentialId_/allowedOrigins.

**Comment by jillingk** [comment]
Hi @jellevdv & @dietermijle,

I'll create an internal ticket to investigate this issue.

Best, Jilling
Adyen

**Comment by AlexandrosMor** [comment]
Hello @dietermijle @jellevdv 

The question for you is if the  'AllowedOriginsResponse' should be 'AllowedOriginResponse' instead? The  'AllowedOriginsResponse' has an array of `AllowedOrigin` so that why the plural. Is something else that I missed from the question ? 

kind regards,
Alexandros
Adyen

**Comment by dietermijle** [comment]
Hi @AlexandrosMor,

As you can see, this [method](https://github.com/Adyen/adyen-dotnet-api-library/blob/main/Adyen/Service/Management/AllowedOriginsCompanyLevelService.cs#L157) returns an array of `AllowedOrigin` according to the code base and according to the [documentation](https://docs.adyen.com/api-explorer/Management/1/post/merchants/_merchantId_/apiCredentials/_apiCredentialId_/allowedOrigins).

Non the less, when executing this via API, a single `AllowedOrigin` is returned:
![image](https://github.com/Adyen/adyen-dotnet-api-library/assets/25662662/c21eaf09-06f9-4978-981f-54e6768b7a4e)

This means that either the API is wrong or the documentation and SDK are wrong.

Kind regards,
Dieter

**Comment by wboereboom** [comment]
hi @jellevdv , @dietermijle 

The docs are indeed wrong.
Our internal teams are aware of this issue and are working on a fix.
When this fix is implemented it will automatically be propagated to this library.
Apologies on the slow response, and for any inconvenience this problem might cause you.

Kind Regards,
Wouter
Adyen
