### ISSUE TITLE
This should be AllowedOriginResponse (MerchantLevel)

### ISSUE THREAD

**Issue by jellevdv** [Adyen/adyen-dotnet-api-library#925]
Shouldn't this be 'AllowedOriginResponse' instead of 'AllowedOrigin**s**Response' ? The serializer can't seem to deserialize the response body because it only returns 1 'AllowedOriginResponse' instead of a list of 'AllowedOriginResponse' like in the 'AllowedOrigin**s**Response' class. (Same for the async method)

https://github.com/Adyen/adyen-dotnet-api-library/blob/1d676a90573bf11e96e7ad1cfbb361a463b197c4/Adyen/Service/Management/AllowedOriginsMerchantLevelService.cs#L157

**Comment by wboereboom** [comment]
hi @jellevdv ,

Our internal teams are aware of this issue and are working on a fix.
When this fix is implemented it will automatically be propagated to this library.
Apologies on the slow response, and for any inconvenience this problem might cause you.

Kind Regards,
Wouter
Adyen
