### ISSUE TITLE
"DEFAULT" value not in Enum 

### ISSUE THREAD

**Issue by jellevdv** [Adyen/adyen-dotnet-api-library#926]
When attempting to retrieve the account holder using the SDK (version 11.2.1, specifically the getAccountHolder method v6), we encounter the following error:
"Newtonsoft.Json.JsonSerializationException: Error converting value \"DEFAULT\" to type 'System.Nullable`1[Adyen.Model.PlatformsAccount.PayoutScheduleResponse+ScheduleEnum]'. Path 'accounts[0].payoutSchedule.schedule', line 1, position 2013.\n ---> System.ArgumentException: Requested value 'DEFAULT' was not found.\n   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(..."
https://github.com/Adyen/adyen-dotnet-api-library/blob/1d676a90573bf11e96e7ad1cfbb361a463b197c4/Adyen/Model/PlatformsAccount/PayoutScheduleResponse.cs#L40

This problem appears to stem from the absence of the "DEFAULT" enum value within the specified enum. The Swagger definition also lacks this value, although it is documented as present here:
https://docs.adyen.com/api-explorer/Account/6/post/getAccountHolder#responses-202-accounts-payoutSchedule-schedule

**Comment by jillingk** [comment]
Hi @jellevdv,

Thanks for reaching out here. I've opened a quick PR #927 to add this value to the library. 

Let me know if you run into anything else!

Best, Jilling
Adyen
