### ISSUE TITLE
Live PayPal payment error

### ISSUE THREAD

**Issue by cjpires** [Adyen/adyen-dotnet-api-library#93]
I am trying to make live PayPal payments and it fails though it works fine with test payments.
I am getting this exception message: Invalid URI: The format of the URI could not be determined.

I debugged the dot net SDK v2.0.0 and v.2.0.2 and noticed the following.
a) in the "namespace Adyen.EcommLibrary":
The method "SetEnviroment" on the switch statement when it sets the live environment it fails testing the variable "liveEndpointUrlPrefix". 
b) In the "namespace Adyen.EcommLibrary.HttpClient"
The method "GetHttpWebRequest" receives the endpoint "/v41/payments" instead of the full API URL; for the test environment it gets the URL "https://checkout-test.adyen.com/v41/payments" instead of the "-checkout-live.adyenpayments.com/checkout" probably because of failing the prefix as mentioned above.

**Comment by AlexandrosMor** [comment]
Hello @cjpires,

Did you pass the liveEndpointUrlPrefix when you create the client ?

Kind regards,

**Comment by AlexandrosMor** [comment]
Hello @cjpires 
We assume that this topic is covered. If there are more questions we are glad to help.
Kind regards
Alexadros
