### ISSUE TITLE
API error when calling PlatformsNotificationConfigurationService.GetNotificationConfigurationListAsync

### ISSUE THREAD

**Issue by p-zender** [Adyen/adyen-dotnet-api-library#943]
**Describe the bug**
`PlatformsNotificationConfigurationService.GetNotificationConfigurationListAsync` returns an error with a message "Empty input which would have resulted in a null result.". 

Based on what I heard from Adyen support this is because the library calls the API with a null request body instead of an empty JSON (and there is no way to send any request body that I'm aware of)

**To Reproduce**
1. Call `PlatformsNotificationConfigurationService.GetNotificationConfigurationListAsync `
2. An exception is thrown with the following information:

> 2023-11-24 12:25:25Z Error 400: BadRequest, ResponseBody: {"status":400,"errorCode":"702","message":"Empty input which would have resulted in a null result.","errorType":"validation"}
Adyen.HttpClient.HttpClientException: 400: BadRequest, ResponseBody: {"status":400,"errorCode":"702","message":"Empty input which would have resulted in a null result.","errorType":"validation"}
   at Adyen.HttpClient.HttpClientWrapper.RequestAsync(String endpoint, String requestBody, RequestOptions requestOptions, HttpMethod httpMethod, CancellationToken cancellationToken)
   at Adyen.Service.ServiceResource.RequestAsync[T](String json, RequestOptions requestOptions, HttpMethod httpMethod, CancellationToken cancellationToken)
   at Adyen.Service.PlatformsNotificationConfigurationService.GetNotificationConfigurationListAsync(RequestOptions requestOptions, CancellationToken cancellationToken)

**Expected behavior**
A list of currently configured notification subscriptions is returned

**Screenshots**

**Desktop (please complete the following information):**
 - N/A
 - N/A
 - N/A

**Smartphone (please complete the following information):**
 - N/A
 - N/A
 - N/A
 - N/A

**Additional context**
Using the 13.0.0 version of the client library.

**Comment by wboereboom** [comment]
Hi @p-zender,

Thanks for raising this issue.
I've reproduced the issue on our end, and the library should indeed send in the empty body if the request object is empty.
We will fix this shortly.

However, I would like to point out that this endpoint is part of our Classic Platforms API, which we no longer support or update. I recommend reaching out to our support department to guide you through the upgrade process so you can use our new APIs and their features.

Kind Regards,
Wouter
Adyen
