### ISSUE TITLE
Error message when setting CreateCheckoutSessionRequest.Mode to Hosted

### ISSUE THREAD

**Issue by bffaro** [Adyen/adyen-dotnet-api-library#947]
When setting up a call to /sessions using .Net SDK 13.0.0 to initiate the hosted checkout payment flow on the web, I get an error stating that field "threeDSAuthenticationOnly" is not supported, despite the fact I never set that field anywhere in my code.

To reproduce:
I set up the CreateCheckoutSessionRequest

```
var config = new Adyen.Config();
config.XApiKey = "...........";
config.Environment = Adyen.Model.Environment.Test;
var client = new Adyen.Client(config);
var paymentService = new PaymentsService(client);

var checkoutSessionRequest = new CreateCheckoutSessionRequest
{
.
.
.
	Mode = CreateCheckoutSessionRequest.ModeEnum.Hosted,
.
.
};

CreateCheckoutSessionResponse createCheckoutSessionResponse = 
paymentService.Sessions(checkoutSessionRequest);

```

I get an error:

`The field 'threeDSAuthenticationOnly' is not supported when mode: 'hosted'`

I expected that field to be ignore if not being used by hosted checkout, especially as I did not set its value anywhere in code.

**Comment by jillingk** [comment]
Hi @bffaro,

Thanks for reaching out here. I just checked and it seems indeed that this value is set to false by default in the [constructor](https://github.com/Adyen/adyen-dotnet-api-library/blob/929ec48ddc2b4eb229397c18739c73bbc85ed4ed/Adyen/Model/Checkout/CreateCheckoutSessionRequest.cs#L270C2823-L270C2823). This code is generated based on annotations by our developers so this default value was probably added for a reason, however I'll double check to see why we have this and if we can remove it. For now a fix would be to just set it to null manually :)

Best, Jilling
Adyen

**Comment by bffaro** [comment]
Hi @jillingk thanks for your reply. Setting it to null seems to work.
Although the same issue applies to the fields ShopperInteraction and Channel. Setting them manually to null works too.

Thanks again.

**Comment by jillingk** [comment]
Hi @bffaro,

Glad to hear that worked for you. We will revise these default parameters again, as I see quite some people are having issues with this. 

Best, Jilling
Adyen
