### ISSUE TITLE
Possible DNS Issues when using the Adyen Client classes constructor without passing out own http client

### ISSUE THREAD

**Issue by JuanOG-Kyo** [Adyen/adyen-dotnet-api-library#956]
**The bug**
I don't see any code which would solve the DNS issue mentioned in the Microsoft Documentation
When using a singleton of the HttpClient.

**Additional context**
I don't see any code which sets the pooled connection lifetime for a client.
So isn't it dangerous to use that default constructor without passing our own http client managed by the http client factory or a client with pooled lifetime set from our end in a production application.

Additionally wouldn't there be a performance impact if one client is shared by multiple requests. Wouldn't it significantly decreased speed and number of requests we can handle when compared to using the Httpclientfactory?
Just asking cause I am not sure about that.

**Comment by jillingk** [comment]
Hi @JuanOG-Kyo, 

Thanks for reaching out to us here. Indeed all of the issues you mentioned above are not negated with the default constructor creating this singleton client. This is exactly why we do recommend passing your own client, or factory for that matter. The default setup in our library is just simply there to make it easy to test and experiment with our library, but should not be used in a resilient integration.

If there's any other concerns you have, be sure to let us know!

Best, Jilling
Adyen

**Comment by JuanOG-Kyo** [comment]
Hi @jillingk,
I have noticed for the default constructor you provide you use a custom HttpMessageHandler which I believe is for custom certificate validations. Should we also provide a client with this custom message handler or just the default one used by the Httpclientfactory.
Is there some extra benefits to using the custom one by Adyen.

**Comment by jillingk** [comment]
Hi @JuanOG-Kyo,

Apologies for taking this long to respond. The custom message handler is only used really for the terminal API. So I'd say you definitely would not need to pass this to the client, if you're not using our library for a terminal integration. 

Best, Jilling
Adyen

**Comment by JuanOG-Kyo** [comment]
Hi @jillingk 
Thank you for the response, yes we do integrate the adyen terminal in our workflow.
So would it be recommended to pass this handler to the factory. Also, would there be any issues with terminal APIs if we don't pass it.
