### ISSUE TITLE
Possible missed fundOrigin property of PaymentRequest model

### ISSUE THREAD

**Issue by paf-dev** [Adyen/adyen-dotnet-api-library#959]
The API documentation says about fundOrigin property of the Payment request here https://docs.adyen.com/api-explorer/Checkout/69/post/payments#request-fundOrigin

We are using nuget package 9.2.1 which should support API v.69 
When we check the PaymentRequest model we can't see the fundOrigin property there. This is the model we are using https://github.com/Adyen/adyen-dotnet-api-library/blob/9.2.1/Adyen/Model/Checkout/PaymentRequest.cs

Is the property really missed or did we use the wrong model for the `/payments` request?

**Comment by AlexandrosMor** [comment]
Hello @paf-dev,
Thank you for raising this issue. I see that the [fundOrigin](https://github.com/Adyen/adyen-dotnet-api-library/blob/v11.0.0/Adyen/Model/Checkout/PaymentRequest.cs#L508) is supported from the library since version v11.0.0. I would recommend to update the library to the latest version or on v11.0.0 which supports` fundorigin`

kind regards,
Alexandros
Adyen

**Comment by paf-dev** [comment]
Hello @AlexandrosMor 
Yes, we are on our way to the latest version of the package. We have a migration plan for the next month. Unfortunately, we can't migrate just with one update.

So, I just need a confirmation that fundOrigin is missed in the 9.2.1, isn't it?
In this case, it will be a good push in the direction of the latest nuget version.

**Comment by AlexandrosMor** [comment]
Hello @paf-dev 
For this question indeed it is missing from [paymentrequest](https://github.com/Adyen/adyen-dotnet-api-library/blob/9.2.1/Adyen/Model/Checkout/PaymentRequest.cs) class even if it is v69.
We are going to investigate it internally. The libraries are always moving forward and we are not updating previous version,
Feel free to close the issue if we answer your question :)
kind regards,
Alexandros
Adyen

**Comment by paf-dev** [comment]
Thank you @AlexandrosMor for your help
I'm closing the ticket
