### ISSUE TITLE
Adyen.Model.Recurring.RecurringDetailWrapper.RecurringDetail has wrong case

### ISSUE THREAD

**Issue by paf-dev** [Adyen/adyen-dotnet-api-library#967]
**Describe the bug**
There is Adyen.Model.Recurring.RecurringDetailWrapper that has RecurringDetail  property. The name in the DataMember attribute for the property is in pascal case while others use camel case.

Version 13.2.0

```
[DataContract(Name = "RecurringDetailWrapper")]
  public class RecurringDetailWrapper : IEquatable<
  #nullable disable
  RecurringDetailWrapper>, IValidatableObject
  {
    public RecurringDetailWrapper(RecurringDetail recurringDetail = null) => this.RecurringDetail = recurringDetail;

    [DataMember(Name = "RecurringDetail", EmitDefaultValue = false)]
    public RecurringDetail RecurringDetail { get; set; }
```

**Expected behavior**
Camel case in the name is expected as it is done for other models.

I don't think I could get write permissions for the repository to create a PR for that.

**Comment by jillingk** [comment]
Hi @paf-dev,

Thanks for reaching out here. Actually (unfortunately I should say) this pascal casing is by design, from the libraries perspective at least. The API does this type of nesting for some models, hence it also reflects that here. If you run into any errors because of this, or have any other question let us know!

Best, Jilling
Adyen

**Comment by paf-dev** [comment]
@jillingk thank you for your quick response.
Now I see the point. I checked the API https://docs.adyen.com/api-explorer/Recurring/68/post/listRecurringDetails#responses-200-details-RecurringDetail

We had a small issue with that, but we could fix it. Actually, it helped us to find a problem with our serialization settings.
Anyway, thank you and sorry for bothering you before checking the original API.
