### ISSUE TITLE
Interac missing as type

### ISSUE THREAD

**Issue by nvgogh** [Adyen/adyen-dotnet-api-library#969]
For the payment method interac I want to create a CheckoutPaymentMethod. However interac is not mentioned in any of the TypeEnums of the classes which are defined in CheckoutPaymentMethod. So the method throws the exception.

**To Reproduce**

var obj = new { type = "interac" };
var checkoutPaymentMethod = CheckoutPaymentMethod.FromJson(obj);

--> exception is thrown

I need the paymentmehod since it is a property of the PaymentRequest which is used in the call to PaymentsAsync.

The issues can be solved by adding the enum value "interac" to the TypeEnum of the class `GenericIssuerPaymentMethodDetails`

            /// <summary>
            /// Enum Interac for value: interac
            /// </summary>
            [EnumMember(Value = "interac")]
            Interac = 5

**Comment by wboereboom** [comment]
Hi @nvgogh,

Thanks for raising this issue.
I can verify that `interac` is indeed missing as a payment method in our documentation and API Libraries.

I will forward this issue appropriately, so that this omission will be fixed. Once documented, this change should automatically propagate to the API library.

Kind Regards,
Wouter
Adyen

**Comment by jellevdv** [comment]
Hello @wboereboom 
We experienced the same issue for the `giftcard` type, I assume this is the same problem as the `interac` ? 

Kind regards,
Jelle

**Comment by dietermijle** [comment]
+1

Maybe relates to this one > https://github.com/Adyen/adyen-dotnet-api-library/issues/951

**Comment by wboereboom** [comment]
Hey all,

Sorry for the wait!
@jellevdv; `giftcard` is available as a type and can be set through the `CardDetails` model.
Adding `interac` as a type is still pending, I apologise. As our libraries are updated through automation and code generation, it would be overwritten if we simply add the type to the appropriate clas. 

Kind Regards,
Wouter
Adyen

**Comment by wboereboom** [comment]
@nvgogh ,
an update on interac:
We are no longer onboarding interac as a payment method. It will not be supported by our libraries in the forseeable future.
If you need more information on this topic, or alternatives to interac, please reach out to our Support through our Customer Area.

Kind Regards,
Wouter
Adyen
