### ISSUE TITLE
Allow using encrypted payload with Cloud API

### ISSUE THREAD

**Issue by jsyrjala** [Adyen/adyen-dotnet-api-library#995]
**Is your feature request related to a problem? Please describe.**

We'd like to use encrypted payloads with Cloud API. Especially we'd like to receive encrypted  async responses in Event notifications. And seems that responses would be encrypted if we would encrypt our requests. But currently SDK doesn't allow specifying encryption details.

With local api you can give `EncryptionCredentialDetails`
```csharp
public interface ITerminalLocalApi
  {
    SaleToPOIResponse TerminalRequest(
      SaleToPOIMessage saleToPoiRequest,
      EncryptionCredentialDetails encryptionCredentialDetails);

    Task<SaleToPOIResponse> TerminalRequestAsync(
      SaleToPOIMessage saleToPoiRequest,
      EncryptionCredentialDetails encryptionCredentialDetails,
      CancellationToken cancellationToken = default (CancellationToken));

    SaleToPOIResponse TerminalRequest(
      SaleToPOIMessage saleToPoiRequest,
      EncryptionCredentialDetails encryptionCredentialDetails,
      RemoteCertificateValidationCallback remoteCertificateValidationCallback);

    string DecryptNotification(
      string notification,
      EncryptionCredentialDetails encryptionCredentialDetails);
  }
```

With cloud api there is no way to give `EncryptionCredentialDetails`
```csharp
  public interface ITerminalCloudApi
  {
    SaleToPOIResponse TerminalRequestAsync(SaleToPOIMessage saleToPoiRequest);

    SaleToPOIResponse TerminalRequestSync(SaleToPOIMessage saleToPoiRequest);

    Task<SaleToPOIResponse> TerminalRequestAsynchronousAsync(
      SaleToPOIMessage saleToPoiRequest,
      CancellationToken cancellationToken = default (CancellationToken));

    Task<SaleToPOIResponse> TerminalRequestSynchronousAsync(
      SaleToPOIMessage saleToPoiRequest,
      CancellationToken cancellationToken = default (CancellationToken));
  }
```

**Describe the solution you'd like**

I'd like be able to specify encryption also with Cloud API

**Describe alternatives you've considered**
- Copying large parts of SDK and making it support encryption in Cloud API sound rather lot of work.
- Not having encryption in responses doesn't sound too secure.

**Comment by Kwok-he-Chu** [comment]
Hi @jsyrjala 

- With **Terminal API local communications** your POS app communicates directly with the payment terminal over your local network.

This means you'll need to set up the `EncryptionCredentialDetails` (see [docs](https://docs.adyen.com/point-of-sale/design-your-integration/choose-your-architecture/local/protect-with-library/#use-the-net-library)) as you mentioned.


- With **Terminal API cloud communications** your POS app communicates with the payment terminal through the Adyen payments platform. Adyen in-this-case handles the connection with the terminal for you. 

There are two [endpoints](https://docs.adyen.com/point-of-sale/design-your-integration/choose-your-architecture/cloud/#build-payment-flow):
- The synchronous `/sync`-endpoint
   - For this type of integration, you'll need to keep your https-connection alive (the docs recommend 150seconds+) as Adyen will take care of the connection with your terminal
- The asychronous `/async`-endpoint
  - For this type of integraiton, if you do not want to keep the https connection alive, you need to setup [event notifications](https://docs.adyen.com/point-of-sale/design-your-integration/notifications/event-notifications/). There are two ways in which you can do this:
    - Using the Customer Area, see this [documentation guide](https://docs.adyen.com/point-of-sale/design-your-integration/notifications/event-notifications/#set-up-in-ca)
    - Alternatively, you can also use API calls (Adyen's Management API , see this [documentation page](https://docs.adyen.com/point-of-sale/design-your-integration/notifications/event-notifications/#set-up-event-notifications-using-api-calls)

Looking at the 'Customer Area'-step above, you will not require the `EncryptionCredentialDetails` from the library, but instead, configure the username, password, your server-url and the "enableEncryption"-flag in the Customer Area. Event notifications will now be sent to the endpoint you specified. If you are using cloud communications with an asynchronous result, the Terminal API responses are also sent to this endpoint.

**Comment by jsyrjala** [comment]
This is still an issue

**Comment by DjoykeAbyah** [comment]
Hi @jsyrjala!

Thanks for letting us know you still experience this issue. I'll need to investigate this a bit further and I'll get back to you as soon as I know more.

Regards,

Djoyke
Adyen

**Comment by DjoykeAbyah** [comment]
Hi @jsyrjala,

I wanted to let you know that we are working on a sustainable solution at the moment. I’ll keep you updated once it’s merged.

Kind regards,

Djoyke
Adyen

**Comment by DjoykeAbyah** [comment]
Hi @jsyrjala!

We've just released the feature https://github.com/Adyen/adyen-dotnet-api-library/pull/1060! You can now send and receive encrypted payloads to /sync and /async.
